begin;
-- SSIAP 1 — La sécurité incendie (partie 2, sub 3/3, 15 questions)
insert into public.questions (
  id, module_id, type, question, explanation, correct_answer, correct_answers, tags, display_order
) values
('ssiap1-q128', 'ssiap1-partie2', 'quiz', 'Le niveau sonore minimum requis pour l''alarme générale d''évacuation dans un ERP est de :', 'La norme NF S 61-936 impose un niveau sonore minimum de 75 dB(A) pour les diffuseurs d''alarme d''évacuation, mesuré à 1 mètre du diffuseur. Le signal doit être perceptible en tout point du bâtiment. Dans les zones bruyantes (cuisines industrielles, ateliers), le signal doit être de 5 à 10 dB(A) supérieur au bruit ambiant. Dans les locaux à sommeil (chambres), des dispositions complémentaires sont prises (diffuseurs dans les chambres). Pour les personnes malentendantes, des dispositifs visuels complémentaires (flashs lumineux) peuvent être exigés.', 2, null::integer[], array['theme6','seq5','Issues de secours et dégagements','Issues de secours et balisage']::text[], 40),
('ssiap1-q129', 'ssiap1-partie2', 'multiple-select', 'Quel est le classement de réaction au feu des matériaux de construction selon la norme européenne Euroclasses ? (plusieurs réponses possibles)', 'Le système Euroclasses (EN 13501-1) classe les matériaux de A1 à F selon leur comportement au feu : A1 : non combustible (béton, acier, verre, pierre) ; A2 : quasi non combustible (légère contribution au feu) ; B : très faible contribution au feu ; C : faible contribution ; D : contribution acceptable ; E : réaction acceptable ; F : pas de performance déterminée (les plus inflammables). Les classes A1 et A2 sont les meilleures. Des critères complémentaires s : s1 (peu de fumée), d0 (pas de gouttes/particules) complètent la classification. La classe B est donc la troisième meilleure, non ''incombustible de type 2''.', null, array[0,1,3]::integer[], array['theme7','seq6','Portes coupe-feu et compartimentage','Compartimentage et cloisonnement']::text[], 41),
('ssiap1-q130', 'ssiap1-partie2', 'quiz', 'En cas d''incendie, les escaliers d''évacuation doivent impérativement être :', 'Les escaliers d''évacuation doivent être protégés (escaliers encloisonnés) pour éviter la pénétration des fumées qui rendraient l''évacuation impossible. Les parois coupe-feu avec des portes CF à fermeture automatique créent une protection physique. Le désenfumage de la cage d''escalier (par ouvrant en façade ou mécanique) empêche l''accumulation de fumées. Ce principe est fondamental : si les escaliers sont envahis par les fumées, les occupants des étages sont piégés. Les escaliers ouverts (non encloisonnés) ne sont admis que dans des cas très limités réglementairement.', 1, null::integer[], array['theme4','seq3','Désenfumage naturel et mécanique','Désenfumage']::text[], 42),
('ssiap1-q162', 'ssiap1-partie2', 'quiz', 'Dans un ERP, les locaux à risques particuliers (chaufferie, local électrique) doivent être :', 'Les locaux à risques particuliers (chaufferie, sous-station électrique, local groupe électrogène, stockage de liquides inflammables, etc.) doivent être isolés du reste du bâtiment par des parois coupe-feu de résistance adaptée (EI 60 ou EI 120 selon le risque). Ils doivent rester fermés à clé en permanence pour éviter les intrusions et limiter l''accès aux seules personnes habilitées. Les clés doivent être disponibles au PC sécurité. Ces locaux sont aussi équipés de moyens de détection et d''extinction adaptés à leurs risques spécifiques. L''agent SSIAP doit connaître leur localisation et les risques associés.', 1, null::integer[], array['theme7','seq6','Portes coupe-feu et compartimentage','Compartimentage et cloisonnement']::text[], 43),
('ssiap1-q163', 'ssiap1-partie2', 'quiz', 'Quel est le principe de fonctionnement d''un système d''extinction automatique à gaz inerte (argon, azote, Inergen) ?', 'Les systèmes d''extinction à gaz inertes (argon, azote, Inergen, mélange argon/azote/CO2) agissent par réduction de la teneur en oxygène de l''atmosphère du local en dessous du seuil de combustion (environ 14-15 %). Le gaz inerte, stocké sous haute pression, est libéré rapidement et remplace l''air dans le volume protégé. Ces systèmes sont utilisés pour protéger les salles informatiques, archives, musées, locaux électriques. Ils sont propres (pas de résidu), compatibles avec les équipements sensibles, mais nécessitent une évacuation préalable du personnel (risque d''asphyxie). Un délai de prédécharge (30 secondes) permet l''évacuation.', 1, null::integer[], array['theme2','seq2','Extincteurs - types et utilisation','Moyens d''extinction']::text[], 44),
('ssiap1-q164', 'ssiap1-partie2', 'quiz', 'L''agent SSIAP effectue une ronde et trouve un extincteur dont la goupille a été retirée mais dont la pression indique toujours le vert. Que doit-il faire ?', 'Une goupille retirée indique que l''extincteur a probablement été déclenché, même partiellement. Même si le manomètre indique encore une pression correcte, l''agent extincteur peut avoir été partiellement utilisé et l''extincteur n''est plus fiable. L''agent SSIAP doit : signaler immédiatement l''anomalie à son responsable ; remplacer l''extincteur par un appareil opérationnel provenant du stock de rechange ; consigner l''incident dans la main courante (date, heure, lieu, description, action prise). L''extincteur défaillant sera envoyé en révision/recharge par le technicien habilité. Ne jamais remettre une goupille et déclarer l''extincteur conforme sans vérification professionnelle.', 1, null::integer[], array['theme2','seq2','Extincteurs - types et utilisation','Moyens d''extinction']::text[], 45),
('ssiap1-q165', 'ssiap1-partie2', 'quiz', 'Quelle est la différence entre ''réaction au feu'' et ''résistance au feu'' d''un matériau ?', 'Ce sont deux notions fondamentalement différentes : la Réaction au feu mesure le comportement d''un matériau par rapport à sa propre combustion : contribue-t-il à l''inflammation et à la propagation du feu ? Elle se mesure par les classes Euroclasses (A1 à F). Elle concerne les matériaux de décoration, revêtements de sol, isolants. La Résistance au feu mesure la capacité d''un élément de construction (mur, plancher, porte) à conserver ses fonctions (portance R, étanchéité E, isolation I) pendant une durée déterminée face à un incendie normalisé. Elle s''exprime en minutes : EI 60, REI 120, etc. Un matériau peut avoir une bonne résistance au feu (acier) mais une mauvaise réaction (acier ne brûle pas mais ce n''est pas un classement de réaction).', 1, null::integer[], array['theme7','seq6','Portes coupe-feu et compartimentage','Compartimentage et cloisonnement']::text[], 46),
('ssiap1-q166', 'ssiap1-partie2', 'quiz', 'Les issues de secours d''un ERP doivent s''ouvrir :', 'Les issues de secours des ERP (hors 5ème catégorie en dessous de certains seuils) doivent s''ouvrir dans le sens de l''évacuation, c''est-à-dire vers l''extérieur du bâtiment. Cette règle est fondamentale : lors d''une panique, la foule se presse contre la porte. Si elle s''ouvre vers l''intérieur, la pression de la foule empêche l''ouverture et peut piéger les personnes (drame du Kiss-nightclub à Santa Maria au Brésil, 2013). L''ouverture vers l''extérieur permet à la pression de la foule d''elle-même pousser la porte dans le bon sens. Les portes doivent également être équipées d''une barre anti-panique.', 1, null::integer[], array['theme6','seq5','Issues de secours et dégagements','Issues de secours et balisage']::text[], 47),
('ssiap1-q167', 'ssiap1-partie2', 'quiz', 'Quel est le rôle de la barre anti-panique (ou barre de poussée) sur une issue de secours ?', 'La barre anti-panique (ou barre de poussée, selon la norme EN 1125) permet l''ouverture de la porte depuis l''intérieur par simple pression sur la barre, sans nécessiter de préhension, de clé ou de manipulation complexe. Elle s''ouvre instantanément même par une foule en mouvement ou une personne paniquée. Elle peut être couplée à un dispositif de verrouillage empêchant l''ouverture depuis l''extérieur (sécurité anti-intrusion), mais qui s''ouvre toujours facilement de l''intérieur. La barre anti-panique est obligatoire sur les portes des ERP dont l''effectif dépasse certains seuils. Lors des rondes, l''agent SSIAP vérifie son bon fonctionnement.', 0, null::integer[], array['theme6','seq5','Issues de secours et dégagements','Issues de secours et balisage']::text[], 48),
('ssiap1-q168', 'ssiap1-partie2', 'multiple-select', 'Quelles vérifications l''agent SSIAP doit-il effectuer sur les BAES (Blocs Autonomes d''Éclairage de Sécurité) lors de ses rondes ? (plusieurs réponses possibles)', 'Lors des rondes, l''agent SSIAP vérifie visuellement les BAES : présence du voyant vert de charge (indique que le BAES est alimenté et sa batterie en charge) ; absence de détérioration physique (coque cassée, fixation arrachée, câble apparent) ; positionnement correct et visibilité (non recouvert, non obstrué par un objet ou du mobilier). Il ne doit PAS tester manuellement la durée d''autonomie à chaque ronde (cela déchargerait les batteries et rendrait les BAES indisponibles pendant leur recharge). Les tests automatiques (SATI) ou les tests manuels périodiques sont planifiés. Le câblage interne est vérifié par le technicien qualifié lors des vérifications annuelles.', null, array[0,1,3]::integer[], array['theme6','seq5','Issues de secours et dégagements','Issues de secours et balisage']::text[], 49),
('ssiap1-q169', 'ssiap1-partie2', 'quiz', 'Combien d''extincteurs faut-il installer au minimum dans un ERP de 200 m² sur un seul niveau avec risques courants ?', 'La règle générale est : 1 extincteur portatif pour 200 à 300 m² de superficie, et au minimum 1 extincteur par niveau. Pour un ERP de 200 m² sur un seul niveau avec risques courants, 1 extincteur est le minimum réglementaire. En pratique, la règle de la distance maximale de 15 mètres peut conduire à en installer davantage. Les risques spéciaux (cuisine professionnelle, local électrique) nécessitent des extincteurs supplémentaires adaptés. L''agent SSIAP doit connaître le nombre et la localisation précise de tous les extincteurs de son établissement.', 0, null::integer[], array['theme2','seq2','Extincteurs - types et utilisation','Moyens d''extinction']::text[], 50),
('ssiap1-q170', 'ssiap1-partie2', 'quiz', 'Le système de détection incendie doit faire l''objet d''un essai mensuel. Quel est le but de cet essai ?', 'L''essai mensuel du système de détection incendie consiste à déclencher manuellement une alarme (via un déclencheur manuel ou un bouton test) pour vérifier que : l''alarme sonore fonctionne (diffuseurs actifs) ; le report d''alarme au PC sécurité est fonctionnel (voyant ou message d''alarme affiché) ; si applicable, la transmission vers un télésurveilleur ou les pompiers fonctionne. Cet essai ne teste pas chaque détecteur individuellement (cela est fait lors de la vérification annuelle). Il est consigné dans le registre de sécurité. L''agent SSIAP prévient les occupants avant l''essai pour éviter une fausse alarme stressante.', 1, null::integer[], array['theme5','seq4','Types de détecteurs automatiques','Détection incendie']::text[], 51),
('ssiap1-q171', 'ssiap1-partie2', 'quiz', 'Les sprinklers résidentiels se déclenchent à une température de :', 'Les sprinklers résidentiels (pour habitations) se déclenchent généralement à 57 °C ou 68 °C selon le modèle. Les sprinklers industriels peuvent se déclencher à des températures plus élevées (79, 93, 141, 182, 204, 260 °C) selon les applications. Les températures nominales de 45 °C, 100 °C et 150 °C ne correspondent pas aux calibrations standard des sprinklers résidentiels. Aucune des propositions n''est correcte.', 3, null::integer[], array['theme8','seq7','Système sprinkler','Sprinklers']::text[], 52),
('ssiap1-q189', 'ssiap1-partie2', 'quiz', 'Parmi les agents extincteurs suivants, lequel agit UNIQUEMENT par refroidissement ?', 'L''eau en jet diffusé agit principalement par refroidissement : elle absorbe une grande quantité de chaleur en s''évaporant (2 257 kJ/kg). La poudre ABC agit par inhibition de la réaction en chaîne et étouffement. Le CO2 agit par étouffement (réduction d''O2) et légèrement par refroidissement. La mousse agit par étouffement et refroidissement. L''halon (aujourd''hui interdit car destructeur de la couche d''ozone) agissait par inhibition chimique. L''eau reste l''agent de refroidissement le plus efficace et le moins coûteux pour les feux de classe A.', 1, null::integer[], array['theme2','seq2','Extincteurs - types et utilisation','Moyens d''extinction']::text[], 53),
('ssiap1-q190', 'ssiap1-partie2', 'multiple-select', 'Quel est le diamètre nominal (DN) standard des tuyaux semi-rigides des RIA les plus répandus ? (plusieurs réponses possibles)', 'Les RIA (Robinets d''Incendie Armés) sont installés avec des tuyaux semi-rigides de deux diamètres standards : DN 25 (25 mm de diamètre interne) pour une décharge minimale de 24 l/min, et DN 33 (33 mm) pour 53 l/min minimum. Le DN 25 est le plus courant dans les ERP. Le DN 19 est utilisé dans les installations domestiques non réglementaires. Le DN 50 et DN 100 correspondent aux tuyaux souples des pompiers (tuyaux plats), non aux RIA. La longueur standard des tuyaux de RIA est de 30 mètres.', null, array[1,2]::integer[], array['theme3','seq2','RIA et colonnes sèches/humides','Moyens d''extinction']::text[], 54)
on conflict (id) do update set
  type=excluded.type, question=excluded.question, explanation=excluded.explanation,
  correct_answer=excluded.correct_answer, correct_answers=excluded.correct_answers,
  tags=excluded.tags, display_order=excluded.display_order, updated_at=now();
delete from public.question_options where question_id in ('ssiap1-q128','ssiap1-q129','ssiap1-q130','ssiap1-q162','ssiap1-q163','ssiap1-q164','ssiap1-q165','ssiap1-q166','ssiap1-q167','ssiap1-q168','ssiap1-q169','ssiap1-q170','ssiap1-q171','ssiap1-q189','ssiap1-q190');
insert into public.question_options (question_id, option_index, option_text) values
('ssiap1-q128', 0, '50 dB(A)'),
('ssiap1-q128', 1, '60 dB(A)'),
('ssiap1-q128', 2, '75 dB(A)'),
('ssiap1-q128', 3, '90 dB(A)'),
('ssiap1-q128', 4, '100 dB(A)'),
('ssiap1-q129', 0, 'La classe A1 correspond aux matériaux incombustibles (béton, acier, verre)'),
('ssiap1-q129', 1, 'La classe F correspond aux matériaux les plus inflammables'),
('ssiap1-q129', 2, 'La classe B correspond aux matériaux incombustibles de type 2'),
('ssiap1-q129', 3, 'Les classes A1 et A2 sont les meilleures (non combustibles)'),
('ssiap1-q129', 4, 'La classe E correspond à un niveau de performance acceptable'),
('ssiap1-q130', 0, 'Ouverts (non cloisonnés) pour faciliter l''évacuation rapide'),
('ssiap1-q130', 1, 'Désenfumés et protégés par des parois coupe-feu avec des portes à fermeture automatique'),
('ssiap1-q130', 2, 'Équipés de sprinklers uniquement'),
('ssiap1-q130', 3, 'Accessibles uniquement par les issues de secours marquées en vert'),
('ssiap1-q130', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q162', 0, 'Accessibles librement pour faciliter la maintenance'),
('ssiap1-q162', 1, 'Isolés par des parois coupe-feu et maintenus fermés à clé en permanence'),
('ssiap1-q162', 2, 'Équipés uniquement d''extincteurs supplémentaires'),
('ssiap1-q162', 3, 'Signalés uniquement par un pictogramme d''avertissement'),
('ssiap1-q162', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q163', 0, 'Il refroidit le combustible en dessous de son point d''ignition'),
('ssiap1-q163', 1, 'Il dilue l''oxygène de l''atmosphère du local en dessous de 15 % pour empêcher la combustion'),
('ssiap1-q163', 2, 'Il inhibe chimiquement la réaction en chaîne'),
('ssiap1-q163', 3, 'Il forme un film protecteur sur les équipements'),
('ssiap1-q163', 4, 'Il déclenche une alarme sonore très forte pour étouffer acoustiquement les flammes'),
('ssiap1-q164', 0, 'Remettre une nouvelle goupille et considérer l''extincteur comme opérationnel'),
('ssiap1-q164', 1, 'Signaler immédiatement l''anomalie, remplacer l''extincteur par un autre opérationnel, consigner dans la main courante'),
('ssiap1-q164', 2, 'Attendre la vérification annuelle pour signaler'),
('ssiap1-q164', 3, 'Secouer l''extincteur pour vérifier s''il reste de l''agent extincteur'),
('ssiap1-q164', 4, 'Ne rien faire si la pression est correcte'),
('ssiap1-q165', 0, 'Ce sont deux termes synonymes désignant la même propriété'),
('ssiap1-q165', 1, 'La réaction au feu mesure la contribution d''un matériau à la naissance et à la propagation du feu, la résistance au feu mesure la capacité d''un élément à conserver ses fonctions sous l''effet du feu'),
('ssiap1-q165', 2, 'La résistance au feu concerne uniquement les matériaux métalliques, la réaction au feu les matériaux organiques'),
('ssiap1-q165', 3, 'La réaction au feu s''applique aux extincteurs, la résistance aux structures'),
('ssiap1-q165', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q166', 0, 'Vers l''intérieur pour éviter de blesser les personnes à l''extérieur'),
('ssiap1-q166', 1, 'Dans le sens de la sortie (vers l''extérieur), dans le sens de l''évacuation'),
('ssiap1-q166', 2, 'Dans les deux sens grâce à des portes va-et-vient'),
('ssiap1-q166', 3, 'Par glissement latéral uniquement'),
('ssiap1-q166', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q167', 0, 'Empêcher l''ouverture depuis l''extérieur tout en permettant la sortie depuis l''intérieur'),
('ssiap1-q167', 1, 'Bloquer la porte en position ouverte pendant l''évacuation'),
('ssiap1-q167', 2, 'Renforcer mécaniquement la porte contre l''effraction'),
('ssiap1-q167', 3, 'Mesurer le nombre de personnes passant par l''issue'),
('ssiap1-q167', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q168', 0, 'Vérifier que le voyant de charge est allumé (BAES en charge normale)'),
('ssiap1-q168', 1, 'S''assurer de l''absence de détérioration physique du bloc'),
('ssiap1-q168', 2, 'Tester manuellement l''autonomie de 1 heure à chaque ronde'),
('ssiap1-q168', 3, 'Vérifier que le bloc est bien positionné (non obstrué, bien visible)'),
('ssiap1-q168', 4, 'Contrôler le câblage électrique interne du BAES'),
('ssiap1-q169', 0, '1 extincteur'),
('ssiap1-q169', 1, '2 extincteurs'),
('ssiap1-q169', 2, '3 extincteurs'),
('ssiap1-q169', 3, '5 extincteurs'),
('ssiap1-q169', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q170', 0, 'Vérifier uniquement l''alimentation électrique de secours'),
('ssiap1-q170', 1, 'S''assurer du bon fonctionnement de l''alarme sonore et du report d''alarme au PC sécurité'),
('ssiap1-q170', 2, 'Tester tous les détecteurs un par un simultanément'),
('ssiap1-q170', 3, 'Vérifier les dates de péremption des détecteurs'),
('ssiap1-q170', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q171', 0, '45 °C'),
('ssiap1-q171', 1, '100 °C'),
('ssiap1-q171', 2, '150 °C'),
('ssiap1-q171', 3, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q189', 0, 'Poudre ABC'),
('ssiap1-q189', 1, 'Eau en jet diffusé'),
('ssiap1-q189', 2, 'CO2'),
('ssiap1-q189', 3, 'Mousse'),
('ssiap1-q189', 4, 'Halon'),
('ssiap1-q190', 0, 'DN 19'),
('ssiap1-q190', 1, 'DN 25'),
('ssiap1-q190', 2, 'DN 33'),
('ssiap1-q190', 3, 'DN 50'),
('ssiap1-q190', 4, 'DN 100');
commit;
