begin;
-- SSIAP 1 — La sécurité incendie (partie 2, sub 2/3, 20 questions)
insert into public.questions (
  id, module_id, type, question, explanation, correct_answer, correct_answers, tags, display_order
) values
('ssiap1-q50', 'ssiap1-partie2', 'quiz', 'Qu''est-ce qu''une porte coupe-feu EI 60 ?', 'La résistance au feu des éléments de construction est caractérisée par des critères : E = Étanchéité aux flammes et gaz chauds ; I = Isolation thermique (le côté non exposé ne doit pas dépasser 140°C en moyenne ou 180°C localement) ; R = Résistance mécanique (pour les éléments porteurs). Le chiffre indique la durée en minutes : EI 30 = 30 min, EI 60 = 60 min, EI 120 = 2 heures. Une porte REI 60 satisfait les 3 critères pendant 60 min. Les portes coupe-feu doivent se fermer automatiquement (dispositif de fermeture automatique) et ne jamais être bloquées ouvertes.', 1, null::integer[], array['theme7','seq6','Portes coupe-feu et compartimentage','Compartimentage et cloisonnement']::text[], 20),
('ssiap1-q51', 'ssiap1-partie2', 'quiz', 'Le compartimentage coupe-feu a pour objectif de :', 'Le compartimentage coupe-feu consiste à diviser un bâtiment en compartiments (ou secteurs) indépendants, séparés par des éléments constructifs résistants au feu (murs, planchers, portes coupe-feu). L''objectif est de confiner l''incendie dans le compartiment d''origine, empêchant sa propagation aux autres zones pendant un temps suffisant pour l''évacuation et l''intervention des secours. Les portes coupe-feu doivent toujours être maintenues fermées (jamais calées ouvertes). Les passages de câbles, gaines techniques constituent des points faibles du compartimentage qui nécessitent des protections spécifiques.', 1, null::integer[], array['theme7','seq6','Portes coupe-feu et compartimentage','Compartimentage et cloisonnement']::text[], 21),
('ssiap1-q52', 'ssiap1-partie2', 'quiz', 'Lors d''une ronde, un agent SSIAP constate qu''une porte coupe-feu est maintenue ouverte par un extincteur. Quelle est la bonne réaction ?', 'Une porte coupe-feu calée ouverte compromet totalement le compartimentage coupe-feu. L''agent SSIAP doit immédiatement retirer l''obstacle (extincteur ou tout autre cale), refermer la porte et s''assurer qu''elle se ferme correctement. Il consigne l''anomalie dans la main courante (date, heure, localisation, action prise) et en informe sa hiérarchie. Si la porte est défectueuse (ne se ferme plus correctement), il doit le signaler en urgence et suivre la procédure de signalement d''anomalie du POI.', 1, null::integer[], array['theme7','seq6','Portes coupe-feu et compartimentage','Compartimentage et cloisonnement']::text[], 22),
('ssiap1-q53', 'ssiap1-partie2', 'quiz', 'Un sprinkler (tête d''aspersion automatique) se déclenche :', 'Un sprinkler contient un élément thermosensible : soit un alliage fusible (soudure), soit une ampoule de verre remplie d''un liquide thermolatent. Quand la température au niveau de la tête sprinkler atteint une température calibrée (57°C, 68°C, 79°C, 93°C, 141°C, 182°C selon les applications), l''élément fond ou se brise, libérant le jet d''eau. Seules les têtes situées au-dessus du foyer se déclenchent. Contrairement aux idées reçues, les sprinklers ne se déclenchent PAS tous simultanément lors d''une alarme incendie.', 1, null::integer[], array['theme8','seq7','Système sprinkler','Sprinklers']::text[], 23),
('ssiap1-q85', 'ssiap1-partie2', 'multiple-select', 'Quels établissements relèvent de la réglementation ERP ? (plusieurs réponses possibles)', 'Relèvent de la réglementation ERP tous les bâtiments où des personnes extérieures sont admises : un supermarché (type M), un hôtel (type O), un cinéma (type L) sont des ERP. Un atelier industriel sans accueil du public relève de la réglementation des ICPE (Installations Classées pour la Protection de l''Environnement) et de la réglementation du travail (code du travail). Un entrepôt logistique fermé au public est également soumis à la réglementation du travail et des ICPE selon sa taille et son activité, mais pas à la réglementation ERP.', null, array[0,2,3]::integer[], array['theme1','seq1','Catégories et types d''ERP','Réglementation - ERP/IGH']::text[], 24),
('ssiap1-q86', 'ssiap1-partie2', 'quiz', 'Un ERP de type J correspond à :', 'Le type J correspond aux structures d''accueil pour personnes âgées ou personnes handicapées (maisons de retraite, EHPAD, foyers d''accueil médicalisé). Ces établissements ont des règles renforcées car les occupants ont des capacités d''évacuation réduites. Type J est considéré comme un établissement ''à sommeil'' avec des contraintes particulières (évacuation horizontale, compartimentage renforcé). Les types non listés ici incluent : G (gares), H (garages), I (salles de danses et jeux - non, c''est P), etc.', 1, null::integer[], array['theme1','seq1','Catégories et types d''ERP','Réglementation - ERP/IGH']::text[], 25),
('ssiap1-q87', 'ssiap1-partie2', 'multiple-select', 'Parmi les extincteurs suivants, lesquels sont adaptés aux feux d''équipements électriques sous tension ? (plusieurs réponses possibles)', 'Pour les feux sur équipements électriques sous tension : le CO2 est le plus adapté (gaz non conducteur, propre, pas de résidu) ; certains extincteurs à eau additionnée sont homologués pour les risques électriques (vérifier l''homologation sur l''étiquette). La poudre ABC est techniquement non conductrice à faible pression mais dégrade irrémédiablement les équipements électroniques. L''eau sans additif et la mousse sont conductrices et présentent un risque d''électrocution grave. Avant toute intervention sur matériel électrique, couper l''alimentation si possible.', null, array[0,3]::integer[], array['theme2','seq2','Extincteurs - types et utilisation','Moyens d''extinction']::text[], 26),
('ssiap1-q88', 'ssiap1-partie2', 'multiple-select', 'Lors de la vérification visuelle d''un extincteur en ronde, quels points l''agent SSIAP doit-il contrôler ? (plusieurs réponses possibles)', 'Lors d''un contrôle visuel en ronde, l''agent SSIAP vérifie : la présence de l''extincteur à son emplacement (non déplacé), l''intégrité du sceau/goupille (si déclenché, à signaler immédiatement), la date de vérification annuelle (étiquette à jour), l''absence de détérioration (corrosion, bosses, fissures). Il ne doit PAS ouvrir la valve ni déclencher partiellement l''extincteur pour vérifier la charge : cela vide l''appareil et le rend inutilisable. La vérification de charge est effectuée par le technicien lors de la visite annuelle (pesée ou indicateur de pression).', null, array[0,1,2,4]::integer[], array['theme2','seq2','Extincteurs - types et utilisation','Moyens d''extinction']::text[], 27),
('ssiap1-q89', 'ssiap1-partie2', 'multiple-select', 'Un extincteur à CO2 a les avantages suivants : (plusieurs réponses possibles)', 'Les avantages du CO2 : pas de résidu (agent propre, idéal pour archives, matériel électronique, musées), non conducteur d''électricité (utilisable sur risques électriques), adapté aux espaces sensibles. Ses limites : il se dissipe très rapidement en extérieur ou par vent (inefficace), il ne refroidit pas suffisamment pour prévenir la reprise sur les feux de classe A (pas d''effet refroidissant durable), sa courte durée de décharge (10-15 s) impose d''être précis. En espace confiné, il présente un risque d''asphyxie.', null, array[0,1,4]::integer[], array['theme2','seq2','Extincteurs - types et utilisation','Moyens d''extinction']::text[], 28),
('ssiap1-q90', 'ssiap1-partie2', 'multiple-select', 'Le déclenchement d''un seul sprinkler lors d''un incendie prouve que : (plusieurs réponses possibles)', 'Contrairement aux idées reçues, un seul sprinkler se déclenche à la fois lors d''un incendie : uniquement celui dont la température de déclenchement est atteinte (au-dessus du foyer). Les autres têtes ne se déclenchent pas. Cela prouve que le système fonctionne correctement et que le déclenchement est localisé. L''avantage est de limiter les dégâts des eaux à la zone du foyer. Les sprinklers ne détectent pas la fumée mais la chaleur. Le déclenchement simultané de tous les sprinklers (déluge) n''existe que dans des systèmes spéciaux (déluge ou préaction) utilisés dans des applications particulières.', null, array[0,2]::integer[], array['theme8','seq7','Système sprinkler','Sprinklers']::text[], 29),
('ssiap1-q91', 'ssiap1-partie2', 'multiple-select', 'Quels éléments doivent impérativement rester dégagés dans un ERP ? (plusieurs réponses possibles)', 'Doivent impérativement rester dégagés : les issues de secours et couloirs d''évacuation (jamais encombrés, bloqués ou cadenassés), les voies d''accès pour les engins des pompiers (zones de stationnement des véhicules de secours, voies ''pompiers''), les emplacements des extincteurs et RIA (accessibles immédiatement). Les locaux techniques doivent être fermés à clé (pour éviter les intrusions) mais les clés doivent être accessibles au PC sécurité. Les bureaux de direction ne sont pas soumis à des exigences de dégagement spécifiques liées à la sécurité incendie.', null, array[0,2,3]::integer[], array['theme6','seq5','Issues de secours et dégagements','Issues de secours et balisage']::text[], 30),
('ssiap1-q92', 'ssiap1-partie2', 'multiple-select', 'Concernant les portes coupe-feu, quelles affirmations sont vraies ? (plusieurs réponses possibles)', 'Les vérités sur les portes coupe-feu : elles doivent être fermées en permanence ou équipées d''un ferme-porte automatique ; elles peuvent être maintenues ouvertes légalement via des électroaimants reliés au SSI (qui les relâchent automatiquement en cas d''alarme) ; un rideau coupe-feu peut en remplacement dans certains cas réglementaires. En revanche, les bloquer avec une cale physique (bois, extincteur) est formellement interdit et supprime toute protection. Les portes CF n''ont pas d''obligation d''ouvrir dans le sens de l''évacuation (c''est une règle pour les issues de secours, pas spécifique aux CF).', null, array[0,1,4]::integer[], array['theme7','seq6','Portes coupe-feu et compartimentage','Compartimentage et cloisonnement']::text[], 31),
('ssiap1-q93', 'ssiap1-partie2', 'quiz', 'Le désenfumage naturel fonctionne grâce à quel phénomène physique ?', 'Le désenfumage naturel exploite la poussée thermique (ou tirage thermique) : les fumées chaudes sont moins denses que l''air froid et montent naturellement. Des exutoires de désenfumage (EFC - Évacuateurs de Fumées et de Chaleur) placés en partie haute du local s''ouvrent pour laisser sortir les fumées. Des entrées d''air frais en partie basse compensent la sortie des fumées. Ce principe simple et fiable (pas de partie mécanique) est utilisé en toiture des halls, entrepôts et ERP. Le désenfumage mécanique (ventilateurs) est utilisé quand la géométrie des locaux ne permet pas le naturel (parkings souterrains, tunnels).', 1, null::integer[], array['theme4','seq3','Désenfumage naturel et mécanique','Désenfumage']::text[], 32),
('ssiap1-q121', 'ssiap1-partie2', 'quiz', 'Parmi les propositions suivantes, laquelle correspond à la définition d''un IGH classe GHA ?', 'GHA correspond aux immeubles à usage d''habitation dépassant 50 m. Les IGH sont classés par lettres : GHA (habitation), GHB (bureaux), GHC (commerces), GHD (hôtels), GHE (enseignement), GHF (établissements sanitaires), GHO (hôtels de grande hauteur), GHR (résidences), GHS (dépôts d''archives), GHU (usage mixte), GHZ (à usage principal d''habitation mais avec autres activités). Aucune des trois propositions ne correspond correctement à GHA (qui est HABITATION, non bureaux, commerces ou enseignement).', 3, null::integer[], array['theme1','seq1','Catégories et types d''ERP','Réglementation - ERP/IGH']::text[], 33),
('ssiap1-q122', 'ssiap1-partie2', 'quiz', 'Quelle est la largeur d''une Unité de Passage (UP) utilisée pour calculer les dégagements dans les ERP ?', 'Une Unité de Passage (UP) est la largeur minimale pour le passage d''une personne, soit 0,60 m. Les dégagements (portes, couloirs, escaliers) sont calculés en UP selon l''effectif à évacuer. Règle générale : 1 UP pour 100 personnes (avec des règles spécifiques selon le type d''ERP). La largeur minimale d''un dégagement principal est de 2 UP (1,20 m à 1,40 m selon la tolérance de construction). Les UP permettent de standardiser les calculs et de s''assurer que les flux d''évacuation sont suffisants.', 1, null::integer[], array['theme6','seq5','Issues de secours et dégagements','Issues de secours et balisage']::text[], 34),
('ssiap1-q123', 'ssiap1-partie2', 'quiz', 'Lors de la mise en place du désenfumage mécanique dans un parking souterrain, les ventilateurs de soufflage et d''extraction doivent fonctionner selon quel principe ?', 'Dans le désenfumage mécanique d''un parking souterrain, le principe est : soufflage d''air frais en partie basse (pour pousser les fumées vers le haut et maintenir une couche d''air respirable au niveau des personnes) et extraction des fumées en partie haute (les fumées chaudes et légères se concentrent en hauteur). Ce principe respecte la stratification naturelle des fumées. Les ventilateurs utilisés dans ce contexte doivent être certifiés F400 (fonctionnement à 400 °C pendant 120 minutes) pour garantir leur efficacité pendant l''intervention des secours.', 1, null::integer[], array['theme4','seq3','Désenfumage naturel et mécanique','Désenfumage']::text[], 35),
('ssiap1-q124', 'ssiap1-partie2', 'multiple-select', 'Quels types de détecteurs sont les mieux adaptés aux risques d''incendie dans une salle informatique (serveurs, baies de brassage) ? (plusieurs réponses possibles)', 'Dans une salle informatique, les incendies débutent souvent par une surchauffe lente des composants électroniques avant l''apparition de flammes. Les détecteurs les mieux adaptés sont : le détecteur à aspiration (ou DIF - Détecteur Incendie à aspiration de Fumée) qui aspire l''air dans les conduits et détecte des concentrations infimes de fumée (très haute sensibilité, idéal sous plancher technique et dans les faux-plafonds) ; le détecteur optique linéaire (faisceau infrarouge) pour couvrir de grands volumes. Les détecteurs de flamme et thermovelocimétriques réagissent trop tard (feu déjà développé) dans ce contexte.', null, array[0,3]::integer[], array['theme5','seq4','Types de détecteurs automatiques','Détection incendie']::text[], 36),
('ssiap1-q125', 'ssiap1-partie2', 'quiz', 'Un déclencheur manuel d''alarme incendie (boîtier rouge brise-glace) doit être positionné :', 'Les déclencheurs manuels d''alarme (boîtiers rouges à brise-glace) doivent être placés à chaque niveau du bâtiment, à proximité des escaliers et sorties, accessibles en permanence (jamais derrière une porte fermée à clé). La hauteur de pose est de 1,30 m du sol (accessible à une personne en fauteuil roulant, conforme à l''accessibilité). Tout occupant doit pouvoir atteindre un déclencheur manuel sans parcourir plus de 30 à 40 mètres. Ils sont de couleur rouge normalisé (RAL 3001) et clairement identifiables.', 1, null::integer[], array['theme5','seq4','Types de détecteurs automatiques','Détection incendie']::text[], 37),
('ssiap1-q126', 'ssiap1-partie2', 'quiz', 'Les colonnes sèches dans les bâtiments sont obligatoires à partir de quelle hauteur de plancher ?', 'Les colonnes sèches sont obligatoires dans les bâtiments dont le plancher bas du dernier niveau accessible dépasse 18 m... non, plus précisément : elles sont obligatoires pour les bâtiments dont au moins un niveau est à plus de 18 m de la voie (pour les immeubles d''habitation) ou dans certains ERP selon la réglementation. Pour les IGH, dès 28 m. La règle précise varie selon le type de bâtiment. Pour les ERP, l''obligation de colonne sèche intervient quand certains niveaux ne sont plus accessibles aux engins-pompes. Le plancher à plus de 28 m est le seuil IGH qui déclenche l''obligation systématique.', 2, null::integer[], array['theme3','seq2','RIA et colonnes sèches/humides','Moyens d''extinction']::text[], 38),
('ssiap1-q127', 'ssiap1-partie2', 'quiz', 'Un RIA (Robinet d''Incendie Armé) DN25 peut délivrer un débit d''eau d''environ :', 'Un RIA DN25 (diamètre nominal 25 mm) délivre un débit de 24 litres par minute minimum sous une pression résiduelle de 2,5 bars. Un RIA DN33 délivre environ 53 l/min. Ces débits sont suffisants pour un premier attaque sur un feu naissant de classe A. Pour comparaison, une lance de pompier à main délivre 250 à 500 l/min. Le RIA est conçu pour être utilisé par des non-professionnels avant l''arrivée des pompiers. La pression doit être maintenue dans toute l''installation pour garantir ce débit.', 1, null::integer[], array['theme3','seq2','RIA et colonnes sèches/humides','Moyens d''extinction']::text[], 39)
on conflict (id) do update set
  type=excluded.type, question=excluded.question, explanation=excluded.explanation,
  correct_answer=excluded.correct_answer, correct_answers=excluded.correct_answers,
  tags=excluded.tags, display_order=excluded.display_order, updated_at=now();
delete from public.question_options where question_id in ('ssiap1-q50','ssiap1-q51','ssiap1-q52','ssiap1-q53','ssiap1-q85','ssiap1-q86','ssiap1-q87','ssiap1-q88','ssiap1-q89','ssiap1-q90','ssiap1-q91','ssiap1-q92','ssiap1-q93','ssiap1-q121','ssiap1-q122','ssiap1-q123','ssiap1-q124','ssiap1-q125','ssiap1-q126','ssiap1-q127');
insert into public.question_options (question_id, option_index, option_text) values
('ssiap1-q50', 0, 'Une porte résistant à la chaleur pendant 60 secondes'),
('ssiap1-q50', 1, 'Une porte assurant l''étanchéité aux flammes et l''isolation thermique pendant 60 minutes'),
('ssiap1-q50', 2, 'Une porte s''ouvrant automatiquement en 60 secondes lors d''une alerte'),
('ssiap1-q50', 3, 'Une porte homologuée pour résister à 60 tonnes'),
('ssiap1-q51', 0, 'Accélérer l''évacuation des occupants'),
('ssiap1-q51', 1, 'Limiter la propagation du feu et des fumées en divisant le bâtiment en zones indépendantes'),
('ssiap1-q51', 2, 'Automatiser le déclenchement des sprinklers'),
('ssiap1-q51', 3, 'Faciliter l''accès des pompiers dans le bâtiment'),
('ssiap1-q52', 0, 'Laisser tel quel, la porte doit rester ouverte pour la circulation'),
('ssiap1-q52', 1, 'Retirer immédiatement l''obstacle, refermer la porte et consigner l''anomalie dans la main courante'),
('ssiap1-q52', 2, 'Condamner définitivement la porte'),
('ssiap1-q52', 3, 'Attendre la fin de sa ronde avant d''intervenir'),
('ssiap1-q53', 0, 'Lors de la détection de fumée'),
('ssiap1-q53', 1, 'Sous l''effet de la chaleur qui fait fondre ou briser son élément fusible ou l''ampoule de verre thermostatique'),
('ssiap1-q53', 2, 'Lors du déclenchement de l''alarme générale'),
('ssiap1-q53', 3, 'Manuellement depuis le poste de sécurité'),
('ssiap1-q85', 0, 'Un supermarché ouvert au public'),
('ssiap1-q85', 1, 'Un atelier industriel sans accueil du public'),
('ssiap1-q85', 2, 'Un hôtel de tourisme'),
('ssiap1-q85', 3, 'Un cinéma'),
('ssiap1-q85', 4, 'Un entrepôt logistique fermé au public'),
('ssiap1-q86', 0, 'Les salles de jeux vidéo'),
('ssiap1-q86', 1, 'Les structures d''accueil pour personnes âgées et personnes handicapées'),
('ssiap1-q86', 2, 'Les jardins botaniques et parcs zoologiques'),
('ssiap1-q86', 3, 'Les établissements judiciaires (tribunaux, prisons)'),
('ssiap1-q86', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q87', 0, 'Extincteur CO2 (dioxyde de carbone)'),
('ssiap1-q87', 1, 'Extincteur à eau pulvérisée sans additif'),
('ssiap1-q87', 2, 'Extincteur à poudre ABC'),
('ssiap1-q87', 3, 'Extincteur à eau avec additif homologué pour risque électrique'),
('ssiap1-q87', 4, 'Extincteur à mousse'),
('ssiap1-q88', 0, 'La présence de l''extincteur à son emplacement réglementaire'),
('ssiap1-q88', 1, 'L''intégrité du sceau ou de la goupille de sécurité'),
('ssiap1-q88', 2, 'La date de la dernière vérification annuelle sur l''étiquette'),
('ssiap1-q88', 3, 'Le remplissage de l''extincteur en ouvrant la valve'),
('ssiap1-q88', 4, 'L''absence de détérioration visible (corrosion, déformation)'),
('ssiap1-q89', 0, 'Il ne laisse pas de résidu après utilisation'),
('ssiap1-q89', 1, 'Il est non conducteur d''électricité'),
('ssiap1-q89', 2, 'Il est efficace en extérieur par grand vent'),
('ssiap1-q89', 3, 'Il peut être utilisé sur les feux de classe A sans risque de reprise'),
('ssiap1-q89', 4, 'Il est adapté aux archives, musées et matériels informatiques'),
('ssiap1-q90', 0, 'L''installation fonctionne correctement car seule la tête au-dessus du foyer se déclenche'),
('ssiap1-q90', 1, 'Tous les sprinklers se déclenchent simultanément dans le bâtiment'),
('ssiap1-q90', 2, 'L''incendie est localisé et les dégâts des eaux sont limités à la zone du foyer'),
('ssiap1-q90', 3, 'Le système a détecté une fumée dans tout le bâtiment'),
('ssiap1-q91', 0, 'Les issues de secours et les dégagements'),
('ssiap1-q91', 1, 'Les locaux techniques (chaufferie, local électrique)'),
('ssiap1-q91', 2, 'Les voies d''accès pour les engins des pompiers'),
('ssiap1-q91', 3, 'Les emplacements des extincteurs'),
('ssiap1-q91', 4, 'Les bureaux de direction'),
('ssiap1-q92', 0, 'Elles doivent toujours être maintenues fermées ou équipées d''un dispositif de fermeture automatique'),
('ssiap1-q92', 1, 'Elles peuvent être maintenues ouvertes par des dispositifs magnétiques reliés au SSI'),
('ssiap1-q92', 2, 'Il est autorisé de les bloquer ouvertes avec une cale en bois pour faciliter la circulation'),
('ssiap1-q92', 3, 'Une porte CF doit s''ouvrir dans le sens de l''évacuation'),
('ssiap1-q92', 4, 'Elles peuvent être remplacées par un rideau coupe-feu'),
('ssiap1-q93', 0, 'La pression mécanique créée par des ventilateurs'),
('ssiap1-q93', 1, 'La poussée thermique : les fumées chaudes et légères montent naturellement vers les exutoires hauts'),
('ssiap1-q93', 2, 'La centrifugation de l''air par des turbines'),
('ssiap1-q93', 3, 'Le différentiel de pression entre l''intérieur et l''extérieur'),
('ssiap1-q93', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q121', 0, 'Immeuble de bureaux de grande hauteur'),
('ssiap1-q121', 1, 'Immeuble commercial de grande hauteur'),
('ssiap1-q121', 2, 'Immeuble d''enseignement de grande hauteur'),
('ssiap1-q121', 3, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q122', 0, '0,40 m'),
('ssiap1-q122', 1, '0,60 m'),
('ssiap1-q122', 2, '0,80 m'),
('ssiap1-q122', 3, '1,00 m'),
('ssiap1-q122', 4, '1,20 m'),
('ssiap1-q123', 0, 'Soufflage en partie haute, extraction en partie basse'),
('ssiap1-q123', 1, 'Soufflage d''air frais en partie basse, extraction des fumées en partie haute'),
('ssiap1-q123', 2, 'Extraction seulement, sans soufflage'),
('ssiap1-q123', 3, 'Soufflage et extraction simultanés au même niveau'),
('ssiap1-q123', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q124', 0, 'Détecteur de fumée à aspiration (détection précoce de fumées invisibles)'),
('ssiap1-q124', 1, 'Détecteur de flamme ultraviolet/infrarouge'),
('ssiap1-q124', 2, 'Détecteur thermovélocimétrique'),
('ssiap1-q124', 3, 'Détecteur optique de fumée linéaire (faisceau infrarouge)'),
('ssiap1-q124', 4, 'Détecteur de gaz naturel'),
('ssiap1-q125', 0, 'Dans les locaux techniques uniquement'),
('ssiap1-q125', 1, 'À chaque niveau, à proximité des escaliers et des sorties, à une hauteur de 1,30 m du sol environ'),
('ssiap1-q125', 2, 'Uniquement à l''entrée principale du bâtiment'),
('ssiap1-q125', 3, 'Dans les locaux à risques (cuisine, chaufferie)'),
('ssiap1-q125', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q126', 0, '7 m'),
('ssiap1-q126', 1, '18 m'),
('ssiap1-q126', 2, '28 m'),
('ssiap1-q126', 3, '50 m'),
('ssiap1-q126', 4, '100 m'),
('ssiap1-q127', 0, '10 l/min'),
('ssiap1-q127', 1, '24 l/min'),
('ssiap1-q127', 2, '100 l/min'),
('ssiap1-q127', 3, '500 l/min'),
('ssiap1-q127', 4, '1 000 l/min');
commit;
