begin;
-- SSIAP 2 — Réglementation approfondie (partie 2, sub 3/3, 6 questions)
insert into public.questions (
  id, module_id, type, question, explanation, correct_answer, correct_answers, tags, display_order
) values
('ssiap2-q163', 'ssiap2-partie2', 'multiple-select', 'Quelles informations le SSIAP 2 doit-il impérativement consigner dans la main courante lors de chaque prise de service ? (plusieurs réponses possibles)', 'La main courante est le document de traçabilité central du service SSIAP. Lors de chaque prise de service, le SSIAP 2 doit y consigner : l''heure précise de prise de service et l''identité de l''agent entrant (et sortant, avec signature des deux) pour établir la continuité de responsabilité ; tous les équipements en défaut ou indisponibles (SSI en inhibition, extincteur en recharge, BAES défaillant) avec les mesures compensatoires en place ; les travaux en cours et leurs impacts sur la sécurité (zones avec permis de feu actif, issues temporairement condamnées, modifications du chemin de ronde) ; les consignes particulières (présence de personnalités, événements programmés, interventions techniques attendues). La météo peut être notée si elle a une influence sur la sécurité (tempête, verglas) mais n''est pas une information standard obligatoire.', null, array[0,1,2,3]::integer[], array['theme1','seq1','Dossier de sécurité et obligations réglementaires','ERP - Réglementation avancée']::text[], 40),
('ssiap2-q164', 'ssiap2-partie2', 'quiz', 'Le SSIAP 2 doit expliquer à un nouveau gestionnaire la différence entre l''ERP et l''IGH pour un bâtiment donné. Quels critères permettent de classer un bâtiment en IGH ?', 'La classification en IGH (Immeuble de Grande Hauteur) est définie par l''article R122-2 du code de la construction et de l''habitation selon la hauteur du plancher du dernier niveau accessible : habitations (résidentiels) : IGH si ce plancher dépasse 50 m de hauteur ; autres immeubles (bureaux, commerces, hôtels, etc.) : IGH si ce plancher dépasse 28 m. Ces seuils correspondent approximativement à la hauteur maximale d''intervention des échelles des pompiers (30 m environ). Au-dessus, les pompiers ne peuvent plus intervenir en façade et des mesures internes renforcées compensent cette limitation. Un même bâtiment peut être classé IGH ET contenir des ERP : dans ce cas, les deux réglementations s''appliquent simultanément en prenant la plus contraignante. Ce n''est pas le nombre d''étages ni la superficie qui détermine le classement.', 1, null::integer[], array['theme3','seq2','Particularités des IGH','IGH - Réglementation spécifique']::text[], 41),
('ssiap2-q165', 'ssiap2-partie2', 'multiple-select', 'Le registre de sécurité doit mentionner les formations du personnel à la sécurité incendie. Quelles informations doit-il contenir à ce sujet ? (plusieurs réponses possibles)', 'Le registre de sécurité doit comporter un volet formation selon la réglementation ERP (article GE 3 du règlement de sécurité). Les mentions obligatoires concernant les formations : la date de chaque action de formation ; le contenu ou thème de la formation (utilisation extincteurs, procédures d''évacuation, levée de doute...) ; le nom et les qualifications du formateur (formateur SSIAP 2 ou 3, ou intervenant externe habilité) ; la liste des personnes présentes avec leur signature attestant leur participation. Les résultats individuels d''évaluation ne sont généralement pas consignés dans le registre de sécurité (ils peuvent l''être dans les dossiers individuels RH) et la date de la prochaine formation n''est pas une mention obligatoire du registre (elle peut figurer dans un planning de formation).', null, array[0,1,2]::integer[], array['theme1','seq1','Dossier de sécurité et obligations réglementaires','ERP - Réglementation avancée']::text[], 42),
('ssiap2-q166', 'ssiap2-partie2', 'multiple-select', 'La ''ronde de fermeture'' réalisée par le SSIAP 2 en fin d''exploitation doit systématiquement vérifier : (plusieurs réponses possibles)', 'La ronde de fermeture est une procédure critique pour la sécurité nocturne, elle doit vérifier : l''absence de personne dans l''établissement (personnes endormies dans un fauteuil, visiteurs attardés dans les sanitaires) ; la fermeture sécurisée des accès (fenêtres, Velux, portes de service) pour prévenir les intrusions et l''exposition au vent (risque de courant d''air sur des flammes) ; l''extinction des sources de chaleur non surveillées (machine à café, bouilloire, four, repasseuse) qui représentent une cause fréquente d''incendie nocturne ; la fermeture des portes CF en position fermée (elles doivent être fermées hors exploitation pour assurer le compartimentage). Désactiver le SSI la nuit est une faute grave qui prive l''établissement de toute protection en cas de départ de feu nocturne.', null, array[0,1,2,3]::integer[], array['theme1','seq1','Dossier de sécurité et obligations réglementaires','ERP - Réglementation avancée']::text[], 43),
('ssiap2-q167', 'ssiap2-partie2', 'quiz', 'Le SSIAP 2 est chargé de mettre à jour le registre de sécurité après une visite de la commission de sécurité. Quelles informations doit-il y consigner ?', 'Après une visite de la commission de sécurité, le registre de sécurité doit comporter une entrée complète : la date de la visite et la composition de la commission (présidents et membres présents) ; l''avis global rendu (favorable, favorable avec observations, défavorable) ; la liste exhaustive de toutes les observations et prescriptions émises par la commission (même celles qui semblent mineures) ; les délais impartis pour lever chaque observation ou exécuter chaque prescription ; ultérieurement, les dates et modalités de levée de chaque observation. Ce compte-rendu est généralement joint au registre sous forme du procès-verbal officiel de visite que la commission adresse à l''exploitant. La transparence totale s''impose : toutes les observations, y compris défavorables, doivent être consignées. Ce registre peut être demandé lors d''une enquête judiciaire post-sinistre.', 1, null::integer[], array['theme1','seq1','Dossier de sécurité et obligations réglementaires','ERP - Réglementation avancée']::text[], 44),
('ssiap2-q168', 'ssiap2-partie2', 'quiz', 'Dans un ERP, certains locaux sont dits ''à risques particuliers''. Quels locaux entrent généralement dans cette catégorie et quelles exigences spécifiques s''y appliquent ?', 'Les locaux à risques particuliers sont définis par les dispositions générales du règlement de sécurité ERP (article GN 7) et les dispositions par type. Ils regroupent notamment : les chaufferies, sous-stations, locaux de machinerie et de stockage d''énergies ; les locaux électriques (TGBT, groupes électrogènes, locaux onduleurs) ; les cuisines professionnelles et offices ; les locaux de stockage d''archives ou de produits inflammables ; les ateliers et locaux de maintenance. Les exigences spécifiques : isolation par des parois coupe-feu (EI 60 ou EI 120 selon les cas), portes CF avec fermeture automatique, désenfumage adapté, parfois systèmes d''extinction automatique. L''objectif est de confiner un incendie démarrant dans ces zones à fort potentiel calorifique.', 1, null::integer[], array['theme1','seq1','Dossier de sécurité et obligations réglementaires','ERP - Réglementation avancée']::text[], 45)
on conflict (id) do update set
  type=excluded.type, question=excluded.question, explanation=excluded.explanation,
  correct_answer=excluded.correct_answer, correct_answers=excluded.correct_answers,
  tags=excluded.tags, display_order=excluded.display_order, updated_at=now();
delete from public.question_options where question_id in ('ssiap2-q163','ssiap2-q164','ssiap2-q165','ssiap2-q166','ssiap2-q167','ssiap2-q168');
insert into public.question_options (question_id, option_index, option_text) values
('ssiap2-q163', 0, 'L''heure de prise de service et l''identité de l''agent prenant le poste'),
('ssiap2-q163', 1, 'Les équipements en défaut ou indisponibles au moment de la relève'),
('ssiap2-q163', 2, 'Les travaux en cours dans l''établissement et les zones concernées'),
('ssiap2-q163', 3, 'Les consignes particulières transmises par le service précédent'),
('ssiap2-q163', 4, 'La météo du jour'),
('ssiap2-q164', 0, 'Un bâtiment est IGH si son nombre de niveaux dépasse 10 étages'),
('ssiap2-q164', 1, 'Un bâtiment est IGH si le plancher de son dernier niveau accessible au public dépasse 28 m (hors habitation) ou si des personnes habitent à plus de 50 m du sol'),
('ssiap2-q164', 2, 'Un bâtiment est IGH si sa superficie dépasse 10 000 m²'),
('ssiap2-q164', 3, 'Un bâtiment est toujours IGH et ERP simultanément dès qu''il dépasse 5 niveaux'),
('ssiap2-q165', 0, 'La date et le contenu des formations dispensées'),
('ssiap2-q165', 1, 'Le nom et la qualification du formateur'),
('ssiap2-q165', 2, 'L''identité des personnes formées et leur signature de présence'),
('ssiap2-q165', 3, 'Le résultat des évaluations (réussite/échec de chaque individu)'),
('ssiap2-q165', 4, 'La prochaine date de formation planifiée'),
('ssiap2-q166', 0, 'L''absence de personne oubliée dans les locaux (WC, salles isolées)'),
('ssiap2-q166', 1, 'La fermeture des fenêtres et ouvertures permettant une intrusion'),
('ssiap2-q166', 2, 'L''extinction de toutes les sources de chaleur non sécurisées (machine à café, appareils de cuisson)'),
('ssiap2-q166', 3, 'La fermeture des portes coupe-feu en position fermée'),
('ssiap2-q166', 4, 'La désactivation totale du SSI pour économiser l''électricité la nuit'),
('ssiap2-q167', 0, 'Uniquement les observations défavorables de la commission'),
('ssiap2-q167', 1, 'La date de la visite, la composition de la commission, l''avis rendu (favorable ou défavorable), la liste des observations et des prescriptions émises, et les délais impartis pour y répondre'),
('ssiap2-q167', 2, 'Seulement l''avis favorable ou défavorable sans détail'),
('ssiap2-q167', 3, 'Les informations sont confidentielles et ne doivent pas figurer dans le registre'),
('ssiap2-q168', 0, 'Uniquement les cuisines professionnelles'),
('ssiap2-q168', 1, 'Les locaux présentant des risques d''incendie ou d''explosion plus élevés (chaufferies, locaux électriques, dépôts inflammables, cuisines) qui doivent être isolés par des parois et portes CF, recoupés des autres locaux'),
('ssiap2-q168', 2, 'Tous les locaux en sous-sol'),
('ssiap2-q168', 3, 'Les locaux de plus de 300 m² quelle que soit leur destination');
commit;
