begin;
-- SSIAP 2 — Installations techniques approfondies (partie 3, sub 3/3, 6 questions)
insert into public.questions (
  id, module_id, type, question, explanation, correct_answer, correct_answers, tags, display_order
) values
('ssiap2-q178', 'ssiap2-partie3', 'quiz', 'Lors d''une inspection, le SSIAP 2 constate qu''une cloison en plâtre a été percée pour faire passer une gaine de ventilation, mais le passage n''a pas été rebouché avec un matériau coupe-feu. De quelle non-conformité s''agit-il et quelle est son importance ?', 'Le calfeutrement des pénétrations dans les parois coupe-feu est une obligation réglementaire fondamentale : une paroi EI 60 percée pour faire passer une gaine sans rebouchage coupe-feu perd totalement sa résistance au feu sur ce point — en quelques minutes, les flammes et les gaz chauds peuvent traverser par le vide annulaire entre la gaine et la paroi. Les matériaux de calfeutrement (mousse intumescente, manchons coupe-feu sur les gaines plastiques, mortier coupe-feu, blocs préfabriqués à insert intumescent) reconstituent la résistance au feu requise. Les gaines de ventilation elles-mêmes ne sont pas exemptées : si elles traversent une paroi CF, elles doivent être équipées d''un clapet coupe-feu (DAS) qui se ferme en cas de sinistre. Cette non-conformité doit être signalée et corrigée en urgence avec un matériau certifié.', 1, null::integer[], array['theme10','seq7','Protections passives des structures','Protection passive']::text[], 40),
('ssiap2-q179', 'ssiap2-partie3', 'multiple-select', 'Le SSIAP 2 doit expliquer à la direction pourquoi les extincteurs CO2 doivent être vérifiés et rechargés périodiquement même s''ils n''ont jamais été utilisés. Quels sont les arguments ? (plusieurs réponses possibles)', 'Les extincteurs CO2 nécessitent une maintenance régulière malgré leur non-utilisation pour plusieurs raisons : la pression interne peut diminuer progressivement par micro-fuites (des tests de pesée permettent de détecter une perte de charge) — un extincteur sous-pressurisé ne projette pas le CO2 à la distance et durée requises ; la bouteille en acier haute pression peut se corroder intérieurement (condensation) ou extérieurement (environnement humide), créant un risque de rupture à la prochaine utilisation ou lors d''une recharge ; la réglementation (arrêté du 5 janvier 2016 et norme NF EN 3) impose une vérification périodique annuelle par un technicien habilité et une recharge basée sur la pesée. Le CO2 en lui-même ne se dégrade pas chimiquement, et la vérification de marquage seule ne justifie pas la périodicité.', null, array[1,2,3]::integer[], array['theme3','seq1','Maintenance et vérification des installations','SSI - Expertise technique']::text[], 41),
('ssiap2-q180', 'ssiap2-partie3', 'quiz', 'Qu''est-ce qu''un ''clapet coupe-feu'' (CCF) et où est-il installé dans un bâtiment ?', 'Le clapet coupe-feu (CCF), aussi appelé volet coupe-feu ou DAS (Dispositif Actionné de Sécurité), est un volet métallique installé dans les conduits de ventilation ou de climatisation au passage des parois coupe-feu. Son rôle est de reconstituer la barrière coupe-feu que le conduit de ventilation perceraient sinon. En temps normal, il est ouvert pour permettre la circulation d''air. En cas de sinistre, il se ferme : soit thermiquement (un élément fusible fond à 70°C libérant le volet qui se ferme par ressort) ; soit par commande électrique déclenchée par le SSI (DAS électrothermique ou électrique). Sa vérification doit être effectuée régulièrement (test d''ouverture/fermeture) et son positionnement exact doit figurer sur les plans. C''est un élément clé du compartimentage dans les bâtiments ventilés.', 1, null::integer[], array['theme1','seq1','Catégories SSI et fonctionnement avancé','SSI - Expertise technique']::text[], 42),
('ssiap2-q181', 'ssiap2-partie3', 'multiple-select', 'Le SSIAP 2 doit assurer le suivi des RIA (Robinets d''Incendie Armés). Lors de la vérification annuelle, quels éléments sont contrôlés ? (plusieurs réponses possibles)', 'La vérification annuelle des RIA (règle APSAD R4) comprend : mesure de la pression et du débit disponibles au robinet (le débit minimal exigé est de 24 l/min avec une pression résiduelle de 2,5 bars pour les DN 25, 45 l/min pour les DN 33) pour s''assurer que le réseau est correctement dimensionné et sans obstruction ; inspection visuelle complète du dévidoir (rotation fluide, absence de grippage ou de déformation), du tuyau semi-rigide (absence de détérioration, de rigidification, de craquelures sur toute la longueur), du jet/lance (non obstrué, joint intact) ; test du robinet d''arrêt (manœuvre pour s''assurer qu''il s''ouvre et se ferme correctement sans fuite). Le mode d''emploi est recommandé mais n''est pas un critère de vérification réglementaire standard. Il n''y a pas de bac de rétention réglementaire sous les RIA.', null, array[0,1,3]::integer[], array['theme3','seq1','Maintenance et vérification des installations','SSI - Expertise technique']::text[], 43),
('ssiap2-q182', 'ssiap2-partie3', 'quiz', 'Lors d''une panne du réseau électrique principal, comment le SSI est-il alimenté et pendant combien de temps doit-il fonctionner ?', 'La norme NF S 61-930 et les dispositions réglementaires imposent que le SSI dispose de sa propre Alimentation Électrique de Sécurité (AES) indépendante du réseau principal : les centrales de détection et les CMSI doivent être équipés de batteries permettant : 12 heures de fonctionnement en veille (surveillance normale sans alarme) + 1 heure de fonctionnement en état d''alarme (toutes les sirènes actives, tous les DAS commandés). Cette autonomie garantit que le SSI reste opérationnel lors d''une coupure électrique suffisamment longtemps pour permettre une intervention et une évacuation complète. Au-delà, si la coupure persiste, un groupe électrogène de sécurité (GES) prend le relais. Les batteries doivent être testées régulièrement (test de décharge) pour vérifier leur capacité réelle.', 1, null::integer[], array['theme5','seq4','Groupe électrogène et AES','Alimentations électriques de sécurité']::text[], 44),
('ssiap2-q183', 'ssiap2-partie3', 'quiz', 'Le SSIAP 2 doit gérer un défaut d''alimentation électrique de sécurité (AES) du SSI signalé par la centrale. Quelle est sa procédure ?', 'Un défaut AES (problème de batteries : batterie faible, déconnectée, défaillante, ou chargeur défaillant) est une non-conformité grave car elle prive le SSI de son autonomie en cas de coupure secteur. La procédure du SSIAP 2 : ne pas réinitialiser (cela masquerait le problème sans le résoudre) ; signaler immédiatement à la direction et au prestataire de maintenance du SSI pour intervention urgente ; consigner dans le registre (date, heure, nature du défaut, actions prises) ; pendant l''indisponibilité de l''AES, augmenter la surveillance humaine du bâtiment (rondes plus fréquentes) et vérifier l''état du réseau électrique de l''établissement (si le réseau est instable, le risque de coupure est plus élevé). Un défaut AES non traité peut conduire à une coupure complète du SSI lors d''une coupure secteur, au pire moment possible.', 1, null::integer[], array['theme5','seq4','Groupe électrogène et AES','Alimentations électriques de sécurité']::text[], 45)
on conflict (id) do update set
  type=excluded.type, question=excluded.question, explanation=excluded.explanation,
  correct_answer=excluded.correct_answer, correct_answers=excluded.correct_answers,
  tags=excluded.tags, display_order=excluded.display_order, updated_at=now();
delete from public.question_options where question_id in ('ssiap2-q178','ssiap2-q179','ssiap2-q180','ssiap2-q181','ssiap2-q182','ssiap2-q183');
insert into public.question_options (question_id, option_index, option_text) values
('ssiap2-q178', 0, 'C''est une non-conformité esthétique sans impact sur la sécurité'),
('ssiap2-q178', 1, 'C''est une non-conformité au compartimentage coupe-feu : le calfeutrement des pénétrations (conduits, câbles) dans les parois CF est obligatoire pour maintenir l''intégrité de la barrière coupe-feu ; sans calfeutrement, le feu peut traverser la paroi par ce passage en quelques minutes'),
('ssiap2-q178', 2, 'C''est une non-conformité mineure à traiter lors du prochain ravalement'),
('ssiap2-q178', 3, 'Les gaines de ventilation sont exemptées de calfeutrement car l''air circule dedans'),
('ssiap2-q179', 0, 'Le CO2 liquéfié se dégrade chimiquement avec le temps'),
('ssiap2-q179', 1, 'La pression interne peut diminuer par micro-fuites au niveau du robinet ou de la valve, réduisant l''efficacité à l''utilisation'),
('ssiap2-q179', 2, 'La bouteille métallique peut se corroder intérieurement ou extérieurement, risquant une rupture en service'),
('ssiap2-q179', 3, 'Les normes réglementaires imposent une vérification tous les 5 ans et une recharge selon la perte de pression'),
('ssiap2-q179', 4, 'Pour vérifier la conformité du marquage sur l''extincteur'),
('ssiap2-q180', 0, 'Un robinet sur les colonnes sèches permettant de couper l''eau'),
('ssiap2-q180', 1, 'Un dispositif mécanique installé dans les conduits de ventilation au droit des parois coupe-feu, qui se ferme automatiquement en cas d''incendie (action thermique ou électrique) pour empêcher la propagation du feu par les gaines'),
('ssiap2-q180', 2, 'Une porte coupe-feu avec loquet automatique'),
('ssiap2-q180', 3, 'Un fusible électrique protégeant le SSI'),
('ssiap2-q181', 0, 'La pression disponible au robinet (débit et pression résiduels conformes à la norme)'),
('ssiap2-q181', 1, 'L''état du dévidoir (rotation sans blocage), du tuyau (absence de détérioration, de craquelures) et du jet'),
('ssiap2-q181', 2, 'La présence du mode d''emploi affiché à proximité'),
('ssiap2-q181', 3, 'Le bon fonctionnement du robinet d''arrêt (ouverture et fermeture)'),
('ssiap2-q181', 4, 'La conformité du bac de rétention sous le RIA'),
('ssiap2-q182', 0, 'Le SSI s''arrête lors d''une coupure secteur'),
('ssiap2-q182', 1, 'Le SSI est alimenté par ses propres alimentations électriques de sécurité (batteries ou alimentation sur source de sécurité) avec une autonomie minimale de 1 heure en alarme après avoir maintenu la veille pendant 12 heures'),
('ssiap2-q182', 2, 'Le SSI passe sur groupe électrogène immédiatement'),
('ssiap2-q182', 3, 'L''autonomie est de 72 heures sur batterie'),
('ssiap2-q183', 0, 'Réinitialiser la centrale pour effacer le défaut'),
('ssiap2-q183', 1, 'Signaler immédiatement à la direction et au prestataire de maintenance, consigner dans le registre, renforcer la surveillance manuelle du bâtiment car le SSI peut se retrouver sans autonomie en cas de coupure secteur, et programmer une intervention urgente'),
('ssiap2-q183', 2, 'Attendre que le défaut s''efface de lui-même'),
('ssiap2-q183', 3, 'Ce défaut n''est pas grave et peut attendre la prochaine vérification annuelle');
commit;
