begin;
-- SSIAP 3 — Coordination institutionnelle (partie 4, sub 1/1, 7 questions)
insert into public.modules (id, level, title, subtitle, icon, color, display_order, is_active)
values ('ssiap3-partie4', 3, 'Coordination institutionnelle', '7 questions', '👨‍🚒', 'from-emerald-500 to-teal-600', 3, true)
on conflict (id) do update set title=excluded.title, subtitle=excluded.subtitle, icon=excluded.icon, color=excluded.color, display_order=excluded.display_order;
insert into public.questions (
  id, module_id, type, question, explanation, correct_answer, correct_answers, tags, display_order
) values
('ssiap3-q16', 'ssiap3-partie4', 'quiz', 'Le SSIAP 3 entretient des relations institutionnelles avec le SDIS local. Dans quel cadre et dans quel but ?', 'La relation entre le SSIAP 3 et le SDIS (Service Départemental d''Incendie et de Secours) est fondamentale pour l''efficacité de la réponse aux sinistres : partage régulier des plans d''intervention (le SDIS possède les plans de l''établissement et les met à jour lors de modifications) ; définition de procédures de coordination claires (qui fait quoi à l''arrivée des pompiers, point de rendez-vous, transmission d''informations) ; participation aux exercices communs (incl. exercices SSIAP/SDIS qui testent l''interface des deux services) ; interopérabilité des communications (radio compatibles ANTARES dans les IGH et grands ERP) ; pour les IGH, des visites de reconnaissance des pompiers dans le bâtiment sont organisées périodiquement. Cette relation est proactive et régulière, pas uniquement réactive lors des sinistres.', 1, null::integer[], array['theme1','seq1','Partenariat SSIAP 3 - SDIS','Relations avec les services de secours']::text[], 0),
('ssiap3-q17', 'ssiap3-partie4', 'multiple-select', 'En cas de sinistre grave nécessitant la fermeture temporaire d''un ERP, le SSIAP 3 doit gérer la communication de crise. Quels acteurs doit-il informer et dans quel ordre de priorité ? (plusieurs réponses possibles)', 'La gestion des communications après un sinistre grave suit une hiérarchie : en priorité absolue, alerter les pompiers (18) si le sinistre est actif ; informer la direction immédiatement après la sécurisation des personnes (la direction décide des orientations stratégiques : fermeture, communication externe) ; l''autorité de police (maire ou préfet selon l''ERP) doit être informée en cas de fermeture même temporaire (l''exploitant est tenu de signaler toute situation mettant en cause la sécurité publique) ; la commission de sécurité doit être informée si la fermeture est prolongée (au-delà de quelques jours, une visite de la commission conditionne la réouverture). Les médias relèvent de la direction de la communication, pas du SSIAP 3 directement.', null, array[0,1,2,4]::integer[], array['theme2','seq2','Communication de crise','Gestion de crise institutionnelle']::text[], 1),
('ssiap3-q18', 'ssiap3-partie4', 'quiz', 'Le SSIAP 3 est confronté à un désaccord technique avec le bureau de contrôle lors d''une vérification. Quelle est la procédure adéquate ?', 'Un désaccord technique avec un bureau de contrôle doit être géré de manière professionnelle et documentée : analyser précisément les observations (sont-elles fondées réglementairement ? Y a-t-il ambiguïté dans le texte ?) ; argumenter techniquement en citant les textes réglementaires précis (articles du règlement de sécurité, normes applicables) pour les points contestés ; chercher un accord documenté (compte-rendu de réunion technique précisant les points d''accord et de désaccord) ; en cas de désaccord persistant sur l''interprétation réglementaire, solliciter l''avis de la commission de sécurité ou d''un expert indépendant. Cette démarche professionnelle est préférable à la confrontation ou à la capitulation systématique. Le SSIAP 3 doit avoir une solide maîtrise réglementaire pour tenir ce rôle.', 2, null::integer[], array['theme3','seq3','Gestion des relations avec bureaux de contrôle','Relations avec les organismes de contrôle']::text[], 2),
('ssiap3-q19', 'ssiap3-partie4', 'multiple-select', 'Quels sont les enjeux éthiques et déontologiques propres à la fonction de SSIAP 3 chef de service ? (plusieurs réponses possibles)', 'La fonction de SSIAP 3 comporte des enjeux éthiques forts : indépendance de jugement (ne pas céder aux pressions commerciales pour accepter des non-conformités ou réduire les effectifs) ; obligation de signalement (le SSIAP 3 a le devoir légal de signaler les situations dangereuses même si cela nuit commercialement ou révèle des manquements de la direction - sa responsabilité pénale est engagée s''il tait sciemment un danger) ; impartialité dans les appels d''offres (éviter les conflits d''intérêt avec les prestataires) ; formation continue (la réglementation évolue, les techniques aussi). La confidentialité sur les non-conformités identifiées n''est pas un principe éthique valable : les non-conformités doivent être documentées et escaladées, jamais cachées.', null, array[0,2,3,4]::integer[], array['theme4','seq4','Éthique du chef de service SSIAP 3','Éthique et déontologie professionnelle']::text[], 3),
('ssiap3-q23', 'ssiap3-partie4', 'quiz', 'Le document ''ORSEC'' (Organisation de la Réponse de Sécurité Civile) implique les ERP dans :', 'Le plan ORSEC est le cadre général de la planification et de la gestion des situations de catastrophe ou de crise (catastrophes naturelles, accidents industriels, événements climatiques extrêmes). Il prévoit la mobilisation des acteurs publics et privés (dont les ERP grands établissements) pour contribuer à la gestion de crise (accueil de sinistrés, points de rassemblement, soutien logistique). Le SSIAP 3 d''un grand ERP peut être impliqué dans les plans ORSEC de sa commune. Aucune des propositions (trafic routier, marchés publics, crues uniquement) ne correspond correctement à la portée large d''ORSEC.', 3, null::integer[], array['theme1','seq1','Partenariat SSIAP 3 - SDIS','Relations avec les services de secours']::text[], 4),
('ssiap3-q38', 'ssiap3-partie4', 'multiple-select', 'Le SSIAP 3 d''un ERP organise un exercice de crise majeure en collaboration avec les autorités locales (préfecture, SDIS, SAMU). Comment structure-t-il cet exercice ? (plusieurs réponses possibles)', 'Un exercice de crise majeure multi-acteurs bien structuré comprend : un scénario réaliste et documenté (avec une fiche de déroulement, des injectants planifiés - ''à 10h15 : simulation d''une victime inconsciente en zone C'') ; toutes les phases du sinistre (détection, alarme, levée de doute, évacuation, accueil SDIS/SAMU, tri des victimes, communication de crise) ; évaluation croisée de chaque acteur et de leurs interfaces (le délai de remontée d''information du SSIAP au COS est-il satisfaisant ?) ; compte-rendu partagé permettant à chaque partenaire d''identifier ses propres points faibles. Les exercices surprises totaux sont déconseillés pour les grands ERP (risque de débordement, paniques réelles) mais une surprise partielle (heure non connue dans une fenêtre annoncée) est pertinente. La transparence totale (tout le monde sait tout à l''avance) réduit la valeur testante.', null, array[0,1,2,4]::integer[], array['theme5','seq5','Exercices de grande ampleur','Exercices de crise multi-acteurs']::text[], 5),
('ssiap3-q39', 'ssiap3-partie4', 'multiple-select', 'Lors d''une enquête judiciaire après un sinistre grave dans son établissement, le SSIAP 3 est convoqué pour audition. Quelles précautions doit-il avoir prises en amont pour se protéger ? (plusieurs réponses possibles)', 'En cas d''enquête judiciaire post-sinistre, la protection du SSIAP 3 repose sur la traçabilité irréprochable de ses actes professionnels : registre de sécurité complet prouvant que toutes les vérifications ont été effectuées, toutes les anomalies signalées et toutes les mesures compensatoires mises en place ; traces écrites des alertes et recommandations à la direction (un courriel non-répondu recommandant un investissement de sécurité refusé par la direction dégage considérablement la responsabilité du SSIAP 3) ; documentation de chaque intervention, décision et vérification avec dates et signatures ; rapports de vérification signés prouvant que les contrôles ont bien eu lieu. La destruction de documents en prévision d''une enquête est une infraction pénale grave (obstruction à la justice, destruction de preuves) qui aggraverait considérablement la situation.', null, array[0,1,2,4]::integer[], array['theme4','seq4','Éthique du chef de service SSIAP 3','Éthique et déontologie professionnelle']::text[], 6)
on conflict (id) do update set
  type=excluded.type, question=excluded.question, explanation=excluded.explanation,
  correct_answer=excluded.correct_answer, correct_answers=excluded.correct_answers,
  tags=excluded.tags, display_order=excluded.display_order, updated_at=now();
delete from public.question_options where question_id in ('ssiap3-q16','ssiap3-q17','ssiap3-q18','ssiap3-q19','ssiap3-q23','ssiap3-q38','ssiap3-q39');
insert into public.question_options (question_id, option_index, option_text) values
('ssiap3-q16', 0, 'Pour éviter d''appeler les pompiers en cas d''incendie'),
('ssiap3-q16', 1, 'Pour partager les plans d''intervention, définir des procédures de coordination, participer aux exercices communs et s''assurer de l''interopérabilité des systèmes de communication'),
('ssiap3-q16', 2, 'Les SDIS n''entretiennent aucune relation préalable avec les SSIAP'),
('ssiap3-q16', 3, 'Uniquement pour obtenir des formations gratuites'),
('ssiap3-q16', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap3-q17', 0, 'Les pompiers en premier (18) si le sinistre est en cours'),
('ssiap3-q17', 1, 'La direction de l''établissement immédiatement après la mise en sécurité des personnes'),
('ssiap3-q17', 2, 'L''autorité de police (préfet ou maire) en cas de fermeture administrative'),
('ssiap3-q17', 3, 'Les médias pour maîtriser l''information'),
('ssiap3-q17', 4, 'La commission de sécurité si la fermeture excède un certain délai'),
('ssiap3-q18', 0, 'Refuser le rapport de vérification et chasser le bureau de contrôle'),
('ssiap3-q18', 1, 'Accepter sans discussion toutes les observations du bureau de contrôle'),
('ssiap3-q18', 2, 'Analyser les observations, discuter techniquement les points contestés avec des références réglementaires, trouver un accord documenté ou saisir une expertise tierce si le désaccord persiste'),
('ssiap3-q18', 3, 'Porter le désaccord directement devant le tribunal'),
('ssiap3-q18', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap3-q19', 0, 'Indépendance de jugement vis-à-vis des pressions commerciales de la direction'),
('ssiap3-q19', 1, 'Confidentialité sur les non-conformités identifiées dans l''établissement'),
('ssiap3-q19', 2, 'Obligation de signalement des situations dangereuses même si cela va à l''encontre des intérêts de l''employeur'),
('ssiap3-q19', 3, 'Impartialité dans les appels d''offres de prestataires de sécurité'),
('ssiap3-q19', 4, 'Mise à jour continue de ses connaissances réglementaires et techniques'),
('ssiap3-q23', 0, 'Les plans de gestion du trafic routier'),
('ssiap3-q23', 1, 'La réglementation des marchés publics'),
('ssiap3-q23', 2, 'La gestion des crues et inondations uniquement'),
('ssiap3-q23', 3, 'Aucune de ces réponses n''est correcte'),
('ssiap3-q38', 0, 'Définir un scénario réaliste incluant un sinistre incendie avec plusieurs victimes'),
('ssiap3-q38', 1, 'Intégrer toutes les phases : détection, alerte, évacuation, accueil des secours, gestion des victimes'),
('ssiap3-q38', 2, 'Évaluer l''efficacité des procédures de chaque acteur et de leurs interfaces'),
('ssiap3-q38', 3, 'Ne pas informer les participants du scénario à l''avance (exercice surprise partiel)'),
('ssiap3-q38', 4, 'Rédiger un compte-rendu partagé avec toutes les parties pour le retour d''expérience'),
('ssiap3-q39', 0, 'Avoir maintenu un registre de sécurité complet et rigoureusement tenu à jour'),
('ssiap3-q39', 1, 'Conserver les traces écrites de ses recommandations et alertes à la direction (courriels, notes de service)'),
('ssiap3-q39', 2, 'Avoir réalisé et documenté toutes les vérifications et mesures compensatoires requises'),
('ssiap3-q39', 3, 'Avoir détruit les documents compromettants avant l''enquête'),
('ssiap3-q39', 4, 'Avoir signé les rapports de vérification prouvant la réalité des contrôles effectués');
commit;
