begin;
-- SSIAP 1 — La sécurité incendie (partie 2, sub 1/3, 20 questions)
insert into public.modules (id, level, title, subtitle, icon, color, display_order, is_active)
values ('ssiap1-partie2', 1, 'La sécurité incendie', '55 questions', '🏛️', 'from-blue-600 to-indigo-700', 1, true)
on conflict (id) do update set title=excluded.title, subtitle=excluded.subtitle, icon=excluded.icon, color=excluded.color, display_order=excluded.display_order;
insert into public.questions (
  id, module_id, type, question, explanation, correct_answer, correct_answers, tags, display_order
) values
('ssiap1-q30', 'ssiap1-partie2', 'quiz', 'Qu''est-ce qu''un ERP (Établissement Recevant du Public) ?', 'Selon l''article R.123-2 du Code de la Construction et de l''Habitation, un ERP est tout bâtiment, local ou enceinte dans lequel des personnes extérieures à l''entreprise ou à la famille sont admises, que l''accès soit payant ou gratuit, libre ou restreint. Les hôtels, restaurants, supermarchés, cinémas, hôpitaux, musées, administrations sont des ERP. La réglementation ERP impose des règles strictes de sécurité incendie proportionnelles à l''effectif et à la nature de l''activité.', 1, null::integer[], array['theme1','seq1','Catégories et types d''ERP','Réglementation - ERP/IGH']::text[], 0),
('ssiap1-q31', 'ssiap1-partie2', 'quiz', 'Les ERP sont classés en 5 catégories selon leur effectif. À quelle catégorie appartient un ERP de 2ème catégorie ?', 'Le classement des ERP par catégorie selon l''effectif : 1ère catégorie : > 1500 personnes ; 2ème catégorie : de 701 à 1500 personnes ; 3ème catégorie : de 301 à 700 personnes ; 4ème catégorie : ≤ 300 personnes (sauf la 5ème cat.) ; 5ème catégorie : effectifs inférieurs aux seuils réglementaires définis par type. Les 4 premières catégories sont soumises aux prescriptions du règlement de sécurité ERP. La 5ème catégorie a des obligations allégées.', 1, null::integer[], array['theme1','seq1','Catégories et types d''ERP','Réglementation - ERP/IGH']::text[], 1),
('ssiap1-q32', 'ssiap1-partie2', 'quiz', 'Un cinéma est classé dans quel type d''ERP ?', 'Les ERP sont classés par types selon leur activité. Type L : Salles d''auditions, de conférences, de réunions, de spectacles ou à usage multiple (cinémas, théâtres, salles polyvalentes). Type M : Magasins de vente et centres commerciaux. Type N : Restaurants et débits de boissons. Type O : Hôtels et pensions de famille. Type P : Salles de danse et de jeux. Type R : Établissements d''enseignement. Type S : Bibliothèques, centres de documentation. Type U : Établissements sanitaires. Type W : Administrations, banques, bureaux.', 0, null::integer[], array['theme1','seq1','Catégories et types d''ERP','Réglementation - ERP/IGH']::text[], 2),
('ssiap1-q33', 'ssiap1-partie2', 'quiz', 'Qu''est-ce qu''un Immeuble de Grande Hauteur (IGH) ?', 'Selon la loi du 7 janvier 1983, un IGH est un bâtiment dont le plancher bas du dernier niveau accessible est situé à plus de 50 m du sol pour les immeubles d''habitation, ou à plus de 28 m pour les autres usages (bureaux, hôtels, commerces, etc.). Les IGH sont soumis à une réglementation spécifique très stricte (article R.122 du CCH) en raison des difficultés d''évacuation et d''intervention des secours. Les IGH sont classés en plusieurs classes (GHA, GHB, GHC, GHD, GHE, GHF, GHZ).', 1, null::integer[], array['theme1','seq1','Catégories et types d''ERP','Réglementation - ERP/IGH']::text[], 3),
('ssiap1-q34', 'ssiap1-partie2', 'quiz', 'La commission de sécurité dans un ERP a pour rôle principal de :', 'La commission de sécurité est une instance administrative présidée par le représentant de l''État (préfet ou sous-préfet) qui visite les ERP pour vérifier la conformité avec la réglementation sécurité incendie. Elle délivre un avis favorable ou défavorable sur l''ouverture ou la poursuite de l''exploitation d''un ERP. En cas d''avis défavorable, le maire peut prononcer la fermeture. Les commissions se réunissent périodiquement et lors de travaux importants ou d''accidents.', 1, null::integer[], array['theme1','seq1','Catégories et types d''ERP','Réglementation - ERP/IGH']::text[], 4),
('ssiap1-q35', 'ssiap1-partie2', 'quiz', 'Quelle est la distance maximale à parcourir pour atteindre un extincteur dans un ERP ?', 'La réglementation ERP impose que tout point d''un bâtiment doit se trouver à moins de 15 mètres d''un extincteur (distance à parcourir de 15 m). En pratique, pour garantir cela, les extincteurs sont positionnés de façon à ce que la distance maximale de parcours soit de 15 m pour les feux de classe B et 20 m pour les feux de classe A. Les extincteurs doivent être visibles, accessibles et signalés. En règle générale, on prévoit au minimum 1 extincteur pour 200 m² et par niveau.', 2, null::integer[], array['theme2','seq2','Extincteurs - types et utilisation','Moyens d''extinction']::text[], 5),
('ssiap1-q36', 'ssiap1-partie2', 'quiz', 'Quel type d''extincteur est contre-indiqué sur un feu d''origine électrique sous tension ?', 'L''eau est conductrice d''électricité. Un extincteur à eau (jet plein ou pulvérisé sans additif) ne doit pas être utilisé sur un équipement électrique sous tension en raison du risque d''électrocution. Les extincteurs adaptés aux risques électriques sont : le CO2 (gaz non conducteur, idéal pour le matériel électronique), et la poudre (mais qui dégrade irrémédiablement l''équipement). Avant d''intervenir sur un équipement électrique, il faut idéalement couper le courant. Certains extincteurs à eau additionnée sont homologués pour risques électriques.', 1, null::integer[], array['theme2','seq2','Extincteurs - types et utilisation','Moyens d''extinction']::text[], 6),
('ssiap1-q37', 'ssiap1-partie2', 'quiz', 'Un extincteur CO2 de 5 kg permet d''éteindre un feu de classe B. Quelle est sa durée de décharge approximative ?', 'La durée de décharge d''un extincteur CO2 de 5 kg est d''environ 10 à 15 secondes. Cette durée courte impose d''être précis et rapide lors de l''utilisation. Le CO2 agit par étouffement (réduction de l''oxygène) et par refroidissement. Ses avantages : gaz propre (pas de résidu), non conducteur d''électricité, adapté aux archives, matériels électroniques. Ses inconvénients : refroidissement rapide (risque de re-ignition), efficacité réduite en extérieur (le gaz se dissipe), risque d''asphyxie dans les espaces confinés.', 1, null::integer[], array['theme2','seq2','Extincteurs - types et utilisation','Moyens d''extinction']::text[], 7),
('ssiap1-q38', 'ssiap1-partie2', 'quiz', 'Quelle est la fréquence de vérification réglementaire des extincteurs ?', 'La réglementation impose une vérification annuelle des extincteurs par un technicien qualifié. Cette vérification comprend : contrôle visuel de l''état général, vérification de la pression (pour les extincteurs à pression permanente), contrôle du scellement du dispositif de sécurité et de l''étiquette. La révision (déchargement, nettoyage, recharge) est effectuée selon les préconisations du fabricant et au minimum tous les 5 à 10 ans. L''agent SSIAP doit effectuer des contrôles visuels réguliers entre les vérifications officielles.', 1, null::integer[], array['theme2','seq2','Extincteurs - types et utilisation','Moyens d''extinction']::text[], 8),
('ssiap1-q39', 'ssiap1-partie2', 'quiz', 'Quelle est la technique correcte d''utilisation d''un extincteur à poudre ?', 'La technique d''utilisation d''un extincteur se résume par l''acronyme DIPA : Dégoupiller (retirer la goupille de sécurité), Inspecter (vérifier visuellement), Pointer (diriger le jet à la base des flammes), Appuyer (sur la manette). Il faut diriger le jet à la BASE des flammes (et non vers le haut) et balayer en mouvement de va-et-vient. Se positionner vent dans le dos, à 2-3 mètres du feu minimum. Ne jamais se mettre seul en danger : si le feu est trop important, évacuer et alerter les secours.', 1, null::integer[], array['theme2','seq2','Extincteurs - types et utilisation','Moyens d''extinction']::text[], 9),
('ssiap1-q40', 'ssiap1-partie2', 'quiz', 'Qu''est-ce qu''un Robinet d''Incendie Armé (RIA) ?', 'Le RIA (Robinet d''Incendie Armé) est un équipement fixe de lutte contre l''incendie constitué d''un dévidoir (enrouleur), d''un tuyau semi-rigide de 25 ou 33 mm de diamètre et d''une lance d''incendie. Il est alimenté par un réseau d''eau permanent sous pression. Le RIA est utilisable par tout occupant (formation minimale requise). Il est efficace sur les feux de classe A et permet une intervention rapide sans manipulation complexe. Les RIA sont vérifiés annuellement et une pression minimale de 2,5 bars doit être maintenue.', 1, null::integer[], array['theme3','seq2','RIA et colonnes sèches/humides','Moyens d''extinction']::text[], 10),
('ssiap1-q41', 'ssiap1-partie2', 'quiz', 'Quelle est la différence entre une colonne sèche et une colonne humide ?', 'La colonne sèche est une canalisation verticale noyée dans les parois du bâtiment, vide en temps normal, avec une prise de raccordement en façade (alimentée par les pompiers avec leur autopompe) et des prises d''incendie à chaque niveau. Elle est obligatoire dans les bâtiments de plus de 28 m. La colonne humide est une canalisation sous pression permanente (eau) avec des robinets de décharge à chaque niveau. Obligatoire au-delà de 50 m (IGH) ou dans certains ERP. Les deux systèmes sont réservés aux sapeurs-pompiers.', 1, null::integer[], array['theme3','seq2','RIA et colonnes sèches/humides','Moyens d''extinction']::text[], 11),
('ssiap1-q42', 'ssiap1-partie2', 'quiz', 'Quel est l''objectif principal du désenfumage dans un bâtiment en feu ?', 'Le désenfumage a pour objectif de maintenir praticables les cheminements d''évacuation (couloirs, escaliers) et de faciliter l''intervention des secours en évacuant ou en limitant la propagation des fumées. Il existe deux types : le désenfumage naturel (exutoires de fumées, ouvrants en façade) qui exploite la poussée thermique, et le désenfumage mécanique (ventilateurs d''extraction) utilisé dans les parkings souterrains, tunnels et grands bâtiments. Le désenfumage est déclenché automatiquement par le SSI ou manuellement.', 1, null::integer[], array['theme4','seq3','Désenfumage naturel et mécanique','Désenfumage']::text[], 12),
('ssiap1-q43', 'ssiap1-partie2', 'quiz', 'Un exutoire de désenfumage (EFC) est déclenché. Quelle est la procédure pour l''agent SSIAP ?', 'Face au déclenchement d''un exutoire de désenfumage, l''agent SSIAP doit : 1) Identifier la zone de déclenchement sur le tableau de signalisation ; 2) Se rendre sur les lieux pour lever le doute (vérifier s''il y a réellement un feu) ; 3) Ne pas refermer l''exutoire si un feu est confirmé (il remplit sa fonction) ; 4) Alerter les secours si nécessaire ; 5) Mettre en œuvre le POI (Plan Opérationnel d''Intervention). Les exutoires peuvent se déclencher sur déclenchement automatique (détecteur de fumée) ou manuel (commande depuis le PC sécurité).', 1, null::integer[], array['theme4','seq3','Désenfumage naturel et mécanique','Désenfumage']::text[], 13),
('ssiap1-q44', 'ssiap1-partie2', 'quiz', 'Quel type de détecteur est le plus adapté à une cuisine professionnelle où de la fumée de cuisson est fréquente ?', 'Dans une cuisine professionnelle, la présence fréquente de fumées de cuisson rendrait un détecteur de fumée inutilisable (déclenchements intempestifs). Le détecteur thermovélocimétrique (ou détecteur de chaleur) réagit à la variation rapide de température (plus de 3 à 5 °C/min) plutôt qu''aux fumées, ce qui le rend adapté aux environnements poussiéreux ou avec fumées non liées à un incendie. Il existe aussi le détecteur thermostatique qui se déclenche quand la température dépasse un seuil fixe (57, 68 ou 90 °C).', 2, null::integer[], array['theme5','seq4','Types de détecteurs automatiques','Détection incendie']::text[], 14),
('ssiap1-q45', 'ssiap1-partie2', 'quiz', 'Un détecteur optique de fumée fonctionne selon quel principe ?', 'Le détecteur optique de fumée (ou photoélectrique) utilise une source lumineuse (LED infrarouge) et un récepteur. En absence de fumée, le faisceau lumineux n''atteint pas le récepteur (chambres à diffusion - Tyndall). Quand des particules de fumée entrent dans la chambre, elles dévient le faisceau vers le récepteur et déclenchent l''alarme. Ce type est efficace pour les fumées visibles (combustion lente, plastiques, bois). Le détecteur ionique utilise une source radioactive pour ioniser l''air et est plus sensible aux combustions vives avec peu de fumée visible.', 1, null::integer[], array['theme5','seq4','Types de détecteurs automatiques','Détection incendie']::text[], 15),
('ssiap1-q46', 'ssiap1-partie2', 'quiz', 'Quelle doit être la largeur minimale d''une issue de secours dans un ERP de 1ère catégorie ?', 'Les sorties et dégagements dans les ERP sont calculés en unités de passage (UP). Une UP = 0,60 m. La largeur minimale d''un dégagement est de 2 UP (1,20 m à 1,40 m selon le type d''ERP). Dans les ERP importants (1ère et 2ème catégorie), les calculs sont plus exigeants. La largeur totale des sorties est proportionnelle à l''effectif. Règle générale : 1 UP pour 100 personnes maximum. Les portes d''issues de secours doivent toujours s''ouvrir dans le sens de l''évacuation (poussée vers l''extérieur).', 3, null::integer[], array['theme6','seq5','Issues de secours et dégagements','Issues de secours et balisage']::text[], 16),
('ssiap1-q47', 'ssiap1-partie2', 'quiz', 'Qu''est-ce qu''un BAES (Bloc Autonome d''Éclairage de Sécurité) ?', 'Le BAES (Bloc Autonome d''Éclairage de Sécurité) est un appareil d''éclairage intégrant sa propre source d''énergie (batterie) qui s''allume automatiquement lors d''une coupure de l''alimentation électrique normale. Il assure l''évacuation des personnes (éclairage d''évacuation) et la surveillance des locaux (éclairage d''ambiance/anti-panique). La durée minimale de fonctionnement est d''1 heure. Les BAES font l''objet de tests périodiques (automatiques pour les modèles SATI, ou manuels). L''agent SSIAP doit vérifier leur état lors de ses rondes.', 1, null::integer[], array['theme6','seq5','Issues de secours et dégagements','Issues de secours et balisage']::text[], 17),
('ssiap1-q48', 'ssiap1-partie2', 'quiz', 'Quelle est la durée minimale d''autonomie des BAES (Blocs Autonomes d''Éclairage de Sécurité) ?', 'La durée minimale d''autonomie d''un BAES est de 1 heure (60 minutes), conformément à la norme NF EN 60598-2-22. Cette durée est calculée pour permettre l''évacuation de tous les occupants et l''intervention initiale des secours. Les BAES d''ambiance (anti-panique) ont la même durée. Après un fonctionnement sur batterie, les BAES doivent se recharger dans un délai maximum de 12 heures. L''agent SSIAP signale immédiatement tout BAES défaillant et consigne l''anomalie dans la main courante.', 1, null::integer[], array['theme6','seq5','Issues de secours et dégagements','Issues de secours et balisage']::text[], 18),
('ssiap1-q49', 'ssiap1-partie2', 'quiz', 'La signalisation de sécurité incendie (flèches d''évacuation, sorties de secours) est de quelle couleur réglementaire ?', 'La signalisation de sécurité incendie (voies d''évacuation, sorties de secours) est réglementairement de couleur blanche sur fond vert (ISO 7010). Le vert signifie sécurité, sauvetage, premiers secours. Les pictogrammes sur fond vert indiquent les issues de secours, les voies d''évacuation, les équipements de secours (douches de sécurité, etc.). La signalisation de prohibition (interdiction de fumer, etc.) est rouge. Les avertissements sont jaunes. Les équipements de lutte contre l''incendie (extincteurs) sont signalés en rouge.', 1, null::integer[], array['theme6','seq5','Issues de secours et dégagements','Issues de secours et balisage']::text[], 19)
on conflict (id) do update set
  type=excluded.type, question=excluded.question, explanation=excluded.explanation,
  correct_answer=excluded.correct_answer, correct_answers=excluded.correct_answers,
  tags=excluded.tags, display_order=excluded.display_order, updated_at=now();
delete from public.question_options where question_id in ('ssiap1-q30','ssiap1-q31','ssiap1-q32','ssiap1-q33','ssiap1-q34','ssiap1-q35','ssiap1-q36','ssiap1-q37','ssiap1-q38','ssiap1-q39','ssiap1-q40','ssiap1-q41','ssiap1-q42','ssiap1-q43','ssiap1-q44','ssiap1-q45','ssiap1-q46','ssiap1-q47','ssiap1-q48','ssiap1-q49');
insert into public.question_options (question_id, option_index, option_text) values
('ssiap1-q30', 0, 'Tout bâtiment de plus de 5 étages'),
('ssiap1-q30', 1, 'Tout bâtiment, local ou enceinte dans lequel des personnes extérieures à l''entreprise sont admises'),
('ssiap1-q30', 2, 'Uniquement les bâtiments accueillant plus de 1000 personnes'),
('ssiap1-q30', 3, 'Les bâtiments industriels et commerciaux uniquement'),
('ssiap1-q31', 0, 'Plus de 1500 personnes'),
('ssiap1-q31', 1, 'De 701 à 1500 personnes'),
('ssiap1-q31', 2, 'De 301 à 700 personnes'),
('ssiap1-q31', 3, 'De 201 à 300 personnes'),
('ssiap1-q32', 0, 'Type L'),
('ssiap1-q32', 1, 'Type M'),
('ssiap1-q32', 2, 'Type N'),
('ssiap1-q32', 3, 'Type P'),
('ssiap1-q33', 0, 'Tout bâtiment de plus de 10 étages'),
('ssiap1-q33', 1, 'Bâtiment dont le plancher bas du dernier niveau habitable dépasse 50 m (habitation) ou 28 m (autres)'),
('ssiap1-q33', 2, 'Immeuble de plus de 20 étages quelle que soit sa destination'),
('ssiap1-q33', 3, 'Tout bâtiment classé en 1ère catégorie ERP'),
('ssiap1-q34', 0, 'Former le personnel à la sécurité incendie'),
('ssiap1-q34', 1, 'Vérifier que l''établissement respecte les règles de sécurité incendie et délivrer un avis sur l''ouverture'),
('ssiap1-q34', 2, 'Gérer les sinistres et indemnisations'),
('ssiap1-q34', 3, 'Certifier les extincteurs et équipements de sécurité'),
('ssiap1-q35', 0, '10 mètres'),
('ssiap1-q35', 1, '15 mètres'),
('ssiap1-q35', 2, '20 mètres'),
('ssiap1-q35', 3, '30 mètres'),
('ssiap1-q36', 0, 'CO2 (dioxyde de carbone)'),
('ssiap1-q36', 1, 'Eau pulvérisée sans additif'),
('ssiap1-q36', 2, 'Poudre ABC'),
('ssiap1-q36', 3, 'Mousse'),
('ssiap1-q37', 0, '5 à 8 secondes'),
('ssiap1-q37', 1, '10 à 15 secondes'),
('ssiap1-q37', 2, '30 à 45 secondes'),
('ssiap1-q37', 3, '1 à 2 minutes'),
('ssiap1-q38', 0, 'Tous les 6 mois'),
('ssiap1-q38', 1, 'Tous les ans'),
('ssiap1-q38', 2, 'Tous les 2 ans'),
('ssiap1-q38', 3, 'Tous les 5 ans'),
('ssiap1-q39', 0, 'Diriger le jet vers le sommet des flammes en faisant des mouvements circulaires'),
('ssiap1-q39', 1, 'Dégoupiller, pointer le diffuseur à la base des flammes, appuyer sur la manette et balayer en mouvement de va-et-vient'),
('ssiap1-q39', 2, 'Retourner l''extincteur pour le déclencher, diriger vers le centre du feu'),
('ssiap1-q39', 3, 'Approcher au maximum avant de déclencher pour maximiser l''efficacité'),
('ssiap1-q40', 0, 'Un robinet de coupure d''eau principal du bâtiment'),
('ssiap1-q40', 1, 'Un équipement fixe de lutte contre l''incendie composé d''un dévidoir, d''un tuyau semi-rigide et d''une lance'),
('ssiap1-q40', 2, 'Un système de sprinklers automatiques'),
('ssiap1-q40', 3, 'Une colonne sèche pour l''alimentation des pompiers'),
('ssiap1-q41', 0, 'La colonne sèche est réservée aux pompiers, la colonne humide est accessible aux occupants'),
('ssiap1-q41', 1, 'La colonne sèche est vide en permanence et alimentée par les pompiers, la colonne humide est sous pression permanente'),
('ssiap1-q41', 2, 'La colonne sèche est en acier, la colonne humide est en plastique'),
('ssiap1-q41', 3, 'Il n''y a pas de différence, ce sont des synonymes'),
('ssiap1-q42', 0, 'Éteindre le feu par dilution des gaz combustibles'),
('ssiap1-q42', 1, 'Maintenir praticables les voies d''évacuation et faciliter l''intervention des secours en évacuant les fumées'),
('ssiap1-q42', 2, 'Refroidir les structures du bâtiment'),
('ssiap1-q42', 3, 'Réduire la pression à l''intérieur du bâtiment'),
('ssiap1-q43', 0, 'Le refermer immédiatement pour éviter l''entrée de pluie'),
('ssiap1-q43', 1, 'Vérifier l''origine du déclenchement, se rendre sur place pour évaluer la situation, alerter si nécessaire'),
('ssiap1-q43', 2, 'Couper l''alimentation électrique du bâtiment'),
('ssiap1-q43', 3, 'Déclencher l''alarme générale sans vérification'),
('ssiap1-q44', 0, 'Détecteur optique de fumée'),
('ssiap1-q44', 1, 'Détecteur ionique de fumée'),
('ssiap1-q44', 2, 'Détecteur thermovélocimétrique'),
('ssiap1-q44', 3, 'Détecteur de flamme'),
('ssiap1-q45', 0, 'La mesure de la température ambiante'),
('ssiap1-q45', 1, 'La déviation ou l''absorption d''un faisceau lumineux par les particules de fumée'),
('ssiap1-q45', 2, 'L''ionisation de l''air par les produits de combustion'),
('ssiap1-q45', 3, 'La détection des rayonnements UV et IR des flammes'),
('ssiap1-q46', 0, '0,60 m'),
('ssiap1-q46', 1, '0,80 m'),
('ssiap1-q46', 2, '0,90 m'),
('ssiap1-q46', 3, '1,40 m (2 UP)'),
('ssiap1-q47', 0, 'Un détecteur de fumée avec batterie de secours'),
('ssiap1-q47', 1, 'Un appareil d''éclairage alimenté par batterie interne qui s''allume automatiquement en cas de coupure d''alimentation'),
('ssiap1-q47', 2, 'Un système de génération électrique de secours'),
('ssiap1-q47', 3, 'Un extincteur à déclenchement automatique'),
('ssiap1-q48', 0, '30 minutes'),
('ssiap1-q48', 1, '1 heure'),
('ssiap1-q48', 2, '2 heures'),
('ssiap1-q48', 3, '6 heures'),
('ssiap1-q49', 0, 'Rouge sur fond blanc'),
('ssiap1-q49', 1, 'Blanc sur fond vert'),
('ssiap1-q49', 2, 'Noir sur fond jaune'),
('ssiap1-q49', 3, 'Blanc sur fond rouge');
commit;
