begin;
-- SSIAP 1 — Les installations techniques (partie 3, sub 1/2, 20 questions)
insert into public.modules (id, level, title, subtitle, icon, color, display_order, is_active)
values ('ssiap1-partie3', 1, 'Les installations techniques', '22 questions', '⚙️', 'from-cyan-500 to-blue-600', 2, true)
on conflict (id) do update set title=excluded.title, subtitle=excluded.subtitle, icon=excluded.icon, color=excluded.color, display_order=excluded.display_order;
insert into public.questions (
  id, module_id, type, question, explanation, correct_answer, correct_answers, tags, display_order
) values
('ssiap1-q54', 'ssiap1-partie3', 'quiz', 'Que signifie SSI dans le domaine de la sécurité incendie ?', 'Le SSI (Système de Sécurité Incendie) est l''ensemble des équipements automatiques et manuels dont la fonction est d''assurer la mise en sécurité d''un bâtiment en cas d''incendie. Il comprend deux sous-systèmes : le SDI (Système de Détection Incendie) qui détecte le sinistre, et le SMSI (Système de Mise en Sécurité Incendie) qui commande les actions de mise en sécurité (alarme, compartimentage, désenfumage, déverrouillage des issues). La norme NF S 61-931 définit les règles de conception et d''installation.', 1, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 0),
('ssiap1-q55', 'ssiap1-partie3', 'quiz', 'Le SMSI (Système de Mise en Sécurité Incendie) comprend notamment quel équipement central ?', 'Le SMSI comprend notamment l''ECS (Équipement de Contrôle et de Signalisation) qui reçoit les ordres du SDI (via la centrale de détection) et commande les DAS (Dispositifs Actionnés de Sécurité) : fermeture des portes coupe-feu, ouverture des exutoires de désenfumage, mise en route de la ventilation de désenfumage mécanique, déclenchement de l''alarme générale, déverrouillage des issues de secours. L''ECS est généralement implanté dans le poste central de sécurité.', 2, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 1),
('ssiap1-q56', 'ssiap1-partie3', 'quiz', 'Un DAS (Dispositif Actionné de Sécurité) peut être :', 'Un DAS (Dispositif Actionné de Sécurité) est tout équipement commandé par le SMSI pour assurer la mise en sécurité d''un bâtiment lors d''un incendie. Les DAS comprennent : les portes coupe-feu (CF) et leurs blocs portes (BP), les clapets coupe-feu dans les gaines de ventilation, les trappes et exutoires de désenfumage, les volets de désenfumage, les déverrouillages électriques des issues de secours, les arrêts des équipements de ventilation et climatisation. Les DAS fonctionnent généralement en position de sécurité : ils se ferment (CF, clapets) ou s''ouvrent (exutoires) lors d''une coupure de courant.', 1, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 2),
('ssiap1-q57', 'ssiap1-partie3', 'quiz', 'Les SSI sont classés en catégories de A à E. Que signifie un SSI de catégorie A ?', 'Les SSI sont classés de A (le plus exigeant) à E (le plus simple). Un SSI de catégorie A comporte une détection automatique généralisée dans tous les locaux, un SMSI avec ECS, et commande toutes les fonctions de mise en sécurité (compartimentage, désenfumage, alarme). Il est obligatoire dans les ERP de 1ère et 2ème catégorie. Les catégories B, C, D, E ont des niveaux décroissants d''exigence. La catégorie E est la plus simple (alarme seule par déclencheurs manuels dans les petits ERP de 5ème catégorie).', 1, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 3),
('ssiap1-q58', 'ssiap1-partie3', 'quiz', 'Quelle est la différence entre une alarme de type 1 et une alarme de type 4 ?', 'Les systèmes d''alarme incendie sont classés en 4 types : Type 1 : le plus élaboré, comprend un SDI (détection automatique) + SMSI avec ECS, obligatoire dans les grands ERP ; Type 2a : détection automatique + diffuseurs sonores, sans SMSI complet ; Type 2b : déclencheurs manuels + diffuseurs sonores avec centrale ; Type 3 : déclencheurs manuels + diffuseurs sonores sans centrale ; Type 4 : le plus simple, un seul déclencheur manuel relié directement à un ou plusieurs timbres ou cloches (autonome, sans câblage complexe). Adapté aux petits ERP de 5ème catégorie.', 1, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 4),
('ssiap1-q59', 'ssiap1-partie3', 'quiz', 'Lors de sa ronde, un agent SSIAP constate qu''un détecteur de fumée au plafond a son voyant LED rouge allumé en permanence. Cela signifie :', 'Sur la plupart des détecteurs automatiques d''incendie, le voyant LED rouge allumé en permanence indique un état d''alarme ou de défaut. Un clignotement lent du LED (toutes les 5 à 10 secondes) indique un fonctionnement normal en mode de surveillance. Face à un LED rouge permanent, l''agent SSIAP doit : 1) Identifier le détecteur et sa zone sur le tableau de signalisation ; 2) Se rendre sur place pour lever le doute (y a-t-il de la fumée, un début d''incendie ?) ; 3) Informer le PC sécurité ; 4) Consigner l''anomalie dans la main courante.', 1, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 5),
('ssiap1-q94', 'ssiap1-partie3', 'multiple-select', 'Que doit faire l''agent SSIAP lorsqu''une alarme incendie se déclenche au PC sécurité ? (plusieurs réponses possibles)', 'Lors d''une alarme au PC sécurité, la procédure standard est : 1) Identifier la zone d''alarme sur le tableau (quelle boucle, quel détecteur) ; 2) Effectuer la levée de doute en se rendant sur place RAPIDEMENT ; 3) Prévenir son responsable selon le POI. Le déclenchement immédiat de l''alarme générale sans vérification est réservé aux cas où le feu est visuellement confirmé ou si le POI le prescrit. L''appel immédiat aux pompiers sans vérification peut générer des interventions inutiles et mobiliser des ressources sans raison. Le POI de chaque établissement définit précisément la procédure à suivre.', null, array[0,2,4]::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 6),
('ssiap1-q95', 'ssiap1-partie3', 'quiz', 'Un clapet coupe-feu dans une gaine de ventilation a pour rôle de :', 'Le clapet coupe-feu (CCF) est un DAS (Dispositif Actionné de Sécurité) installé dans les traversées de parois par les gaines de ventilation/climatisation. En temps normal, il est ouvert pour permettre la circulation de l''air. En cas d''incendie, il se ferme automatiquement (par fusion d''un fusible thermique ou par commande électrique du SSI) pour bloquer la propagation du feu et des fumées à travers les gaines. Les gaines de ventilation constituent en effet des voies de propagation redoutables pour les fumées et les flammes. La résistance au feu des clapets est de 30, 60 ou 120 minutes.', 1, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 7),
('ssiap1-q96', 'ssiap1-partie3', 'quiz', 'L''alarme générale d''évacuation dans un ERP doit être perceptible :', 'L''alarme générale d''évacuation doit être audible dans l''ensemble des locaux de l''établissement accessibles au public et dans les locaux de travail. Le niveau sonore minimal est de 75 dB(A) en tout point du bâtiment (ou 5 dB(A) au-dessus du bruit ambiant si celui-ci est élevé). Dans les établissements à sommeil (hôtels, hôpitaux), des diffuseurs sonores sont également installés dans les chambres. Des dispositifs lumineux peuvent compléter le signal sonore pour les personnes malentendantes. L''alarme restreinte (PC sécurité seulement) précède l''alarme générale dans les établissements avec personnel de sécurité.', 1, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 8),
('ssiap1-q97', 'ssiap1-partie3', 'multiple-select', 'Parmi les équipements suivants, lesquels font partie du Système de Mise en Sécurité Incendie (SMSI) ? (plusieurs réponses possibles)', 'Le SSI se divise en deux sous-systèmes : le SDI (Système de Détection Incendie) qui comprend les détecteurs automatiques et les déclencheurs manuels, et le SMSI (Système de Mise en Sécurité Incendie) qui comprend l''ECS (Équipement de Contrôle et de Signalisation qui traite les ordres) et tous les DAS (Dispositifs Actionnés de Sécurité : portes CF, exutoires, clapets, déverrouillages, etc.). Les détecteurs et boîtiers brise-glace appartiennent au SDI, pas au SMSI.', null, array[0,2,4]::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 9),
('ssiap1-q98', 'ssiap1-partie3', 'quiz', 'Quel est le rôle du Tableau de Report d''Alarme (TRA) dans un hôtel ?', 'Le TRA (Tableau de Report d''Alarme) est un équipement qui reporte les informations d''alarme de la centrale de détection vers un point de permanence humaine (réception d''hôtel, loge de gardien). Il permet au personnel de permanence de visualiser les alarmes sans avoir à se rendre au PC sécurité principal. Dans les hôtels, il est souvent installé à la réception pour que le réceptionniste (présent 24h/24) puisse lever le doute et déclencher les procédures d''évacuation. Il est distinct de la centrale de détection et n''a généralement pas de capacité de commande des DAS.', 1, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 10),
('ssiap1-q131', 'ssiap1-partie3', 'quiz', 'Qu''est-ce qu''un CMSI (Centralisateur de Mise en Sécurité Incendie) ?', 'Le CMSI (Centralisateur de Mise en Sécurité Incendie) est le composant central du SMSI. Il reçoit les informations d''alarme provenant du SDI (centrale de détection) et commande en conséquence les DAS (Dispositifs Actionnés de Sécurité) : fermeture des portes CF, ouverture des exutoires de désenfumage, mise en route du désenfumage mécanique, déverrouillage des issues, arrêt de la ventilation normale. Le CMSI est distinct de la centrale de détection (ECS) et peut être intégré ou séparé selon les configurations. Il est défini par la norme NF S 61-934.', 1, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 11),
('ssiap1-q132', 'ssiap1-partie3', 'multiple-select', 'Le test annuel du SSI doit vérifier quels points ? (plusieurs réponses possibles)', 'La vérification annuelle du SSI par un technicien qualifié comprend : le test de chaque détecteur (par aérosol simulateur de fumée ou source de chaleur pour les thermo) ; la vérification de la transmission des signaux d''alarme et de défaut à la centrale et au PC sécurité ; le test des DAS (vérifier que les portes CF se ferment, que les exutoires s''ouvrent, que le désenfumage mécanique se met en route) ; vérification des batteries de secours de l''alimentation électrique de sécurité (AES). Ces vérifications sont consignées dans le registre de sécurité avec les résultats. La couleur des voyants et le contenu du registre ne font pas partie des vérifications techniques.', null, array[0,1,2]::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 12),
('ssiap1-q133', 'ssiap1-partie3', 'quiz', 'L''Alimentation Électrique de Sécurité (AES) du SSI doit garantir le fonctionnement du système pendant combien de temps en cas de coupure secteur ?', 'L''AES (Alimentation Électrique de Sécurité) du SSI doit garantir le fonctionnement complet du système pendant au minimum 1 heure en mode alarme (batteries de secours chargées). En veille (surveillance normale), la durée est de 12 heures minimum. Ces durées permettent de gérer la situation le temps de l''intervention des secours et d''une évacuation complète. Les batteries doivent être vérifiées régulièrement et remplacées selon les préconisations du fabricant (généralement tous les 4 à 5 ans). En cas de coupure EDF prolongée, un groupe électrogène peut prendre le relais pour les systèmes critiques.', 2, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 13),
('ssiap1-q134', 'ssiap1-partie3', 'quiz', 'Parmi les propositions suivantes, laquelle décrit un SSI de catégorie B ?', 'Un SSI de catégorie B comporte une détection automatique dans certaines zones seulement (zones à risques particuliers) plus des déclencheurs manuels, avec un SMSI comprenant une centrale et des DAS dans les zones concernées. Aucune des trois propositions ne correspond exactement : la catégorie A est la détection généralisée avec SMSI complet ; la catégorie E ou type 3 correspond aux déclencheurs manuels seuls ; les sprinklers ne constituent pas un SSI à eux seuls. La bonne définition de la catégorie B n''est donc dans aucune des options proposées.', 1, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 14),
('ssiap1-q135', 'ssiap1-partie3', 'quiz', 'Un DAI (Déclencheur d''Alarme Incendie) manuel doit être de quelle couleur réglementaire ?', 'Les déclencheurs manuels d''alarme incendie (boîtiers brise-glace ou à membrane) sont de couleur rouge normalisé (RAL 3001 rouge sécurité) selon la norme EN 54-11 et la réglementation française. Le rouge est la couleur internationale associée à la lutte contre l''incendie et aux équipements de sécurité incendie actifs (extincteurs, colonnes sèches, déclencheurs). Les pictogrammes de signalisation des équipements anti-incendie sont également sur fond rouge. Le vert est la couleur des équipements de secours et d''évacuation (issues de secours, BAES).', 1, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 15),
('ssiap1-q136', 'ssiap1-partie3', 'multiple-select', 'La vidéosurveillance dans le PC sécurité permet à l''agent SSIAP de : (plusieurs réponses possibles)', 'La vidéosurveillance (CCTV) est un outil complémentaire précieux pour l''agent SSIAP : elle permet une levée de doute rapide depuis le PC sur les zones couvertes par les caméras, la surveillance des accès et zones à risques, et l''observation du comportement des occupants (attroupements suspects, comportements dangereux). En revanche, elle ne remplace pas les rondes physiques (zones sans caméras, détails non visibles à l''écran, contact humain) ni les détecteurs automatiques (qui couvrent l''ensemble du bâtiment en permanence, y compris les zones non visibles). Son installation et son utilisation sont encadrées par la réglementation CNIL/RGPD.', null, array[0,1,3]::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 16),
('ssiap1-q172', 'ssiap1-partie3', 'quiz', 'L''adressage des détecteurs dans un SSI de catégorie A permet :', 'L''adressage des détecteurs (systèmes adressés ou intelligents) permet d''identifier individuellement chaque détecteur sur le tableau de signalisation avec sa localisation précise (ex : ''Détecteur 047 - Bureau 312 - 3ème étage aile B''). Cela permet à l''agent SSIAP de localiser immédiatement la zone exacte d''alarme sans avoir à interpréter une zone groupée. Les systèmes non adressés (conventionnels) indiquent seulement la boucle (zone) en alarme, sans identifier le détecteur précis. Les systèmes adressés facilitent aussi la maintenance et la vérification individuelle. Ils ne remplacent pas les rondes et n''ont pas de connexion internet en standard.', 0, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 17),
('ssiap1-q173', 'ssiap1-partie3', 'quiz', 'Un agent SSIAP est seul au PC et l''alarme incendie se déclenche pour la zone ''sous-sol parking''. La levée de doute prend du temps. Quelles sont les limites temporelles à respecter ?', 'La levée de doute doit être rapide. Le délai généralement admis est de 3 à 5 minutes maximum (selon le POI de l''établissement) avant de déclencher l''alarme générale si aucune information ne permet d''infirmer l''alarme. Pendant ce temps, l''agent se rend sur les lieux (ou y envoie un collègue si l''équipe le permet). Si le feu est confirmé avant ce délai, l''alarme générale est déclenchée immédiatement. Si l''agent est seul au PC et que la zone est éloignée, le POI doit prévoir une procédure adaptée (contact téléphonique avec un occupant de la zone, caméra de surveillance, etc.). En cas de doute persistant = alarme générale.', 1, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 18),
('ssiap1-q174', 'ssiap1-partie3', 'quiz', 'Que signifie l''indication ''DEFAUT'' sur le tableau de signalisation du SSI ?', 'Un signal ''DÉFAUT'' (voyant jaune ou orange sur la plupart des centrales) indique un dysfonctionnement dans le système de détection ou de mise en sécurité : câble coupé ou en court-circuit, détecteur défaillant ou absent de son support, alimentation électrique anormale, batterie déchargée, DAS ne répondant pas. Le défaut ne signifie pas qu''un incendie est en cours (c''est l''ALARME) mais que la surveillance est partiellement compromise. L''agent SSIAP doit consigner le défaut dans la main courante et alerter son responsable pour intervention technique. Un défaut non traité peut conduire à une non-détection d''un incendie réel.', 1, null::integer[], array['theme1','seq1','SSI - composants et fonctionnement','Système de Sécurité Incendie (SSI)']::text[], 19)
on conflict (id) do update set
  type=excluded.type, question=excluded.question, explanation=excluded.explanation,
  correct_answer=excluded.correct_answer, correct_answers=excluded.correct_answers,
  tags=excluded.tags, display_order=excluded.display_order, updated_at=now();
delete from public.question_options where question_id in ('ssiap1-q54','ssiap1-q55','ssiap1-q56','ssiap1-q57','ssiap1-q58','ssiap1-q59','ssiap1-q94','ssiap1-q95','ssiap1-q96','ssiap1-q97','ssiap1-q98','ssiap1-q131','ssiap1-q132','ssiap1-q133','ssiap1-q134','ssiap1-q135','ssiap1-q136','ssiap1-q172','ssiap1-q173','ssiap1-q174');
insert into public.question_options (question_id, option_index, option_text) values
('ssiap1-q54', 0, 'Service de Surveillance Incendie'),
('ssiap1-q54', 1, 'Système de Sécurité Incendie'),
('ssiap1-q54', 2, 'Surveillance et Sécurité Intégrée'),
('ssiap1-q54', 3, 'Signal Sonore d''Incendie'),
('ssiap1-q55', 0, 'Le Tableau de Signalisation (TS)'),
('ssiap1-q55', 1, 'La Centrale de Détection Incendie (CDI)'),
('ssiap1-q55', 2, 'L''Équipement de Contrôle et de Signalisation (ECS)'),
('ssiap1-q55', 3, 'Le Tableau Général Basse Tension (TGBT)'),
('ssiap1-q56', 0, 'Uniquement une porte coupe-feu'),
('ssiap1-q56', 1, 'Un clapet coupe-feu, une porte coupe-feu, un exutoire de désenfumage, une trappe de désenfumage'),
('ssiap1-q56', 2, 'Uniquement les sprinklers'),
('ssiap1-q56', 3, 'Tout équipement électrique du bâtiment'),
('ssiap1-q57', 0, 'Le niveau le plus bas, réservé aux petits ERP'),
('ssiap1-q57', 1, 'Le niveau le plus exigeant, avec détection automatique généralisée et mise en sécurité complète'),
('ssiap1-q57', 2, 'Un SSI uniquement composé d''extincteurs'),
('ssiap1-q57', 3, 'Un SSI sans détection automatique'),
('ssiap1-q58', 0, 'Le type 1 est pour les petits ERP, le type 4 pour les grandes surfaces'),
('ssiap1-q58', 1, 'Le type 1 est le plus complet (SDI + SMSI), le type 4 est le plus simple (timbre ou cloche autonome)'),
('ssiap1-q58', 2, 'Le type 1 est manuel, le type 4 est automatique'),
('ssiap1-q58', 3, 'Il n''y a pas de différence fonctionnelle'),
('ssiap1-q59', 0, 'Le détecteur fonctionne normalement'),
('ssiap1-q59', 1, 'Le détecteur est en défaut ou en alarme, il faut lever le doute et informer le PC sécurité'),
('ssiap1-q59', 2, 'La batterie du détecteur est chargée'),
('ssiap1-q59', 3, 'Un test automatique est en cours'),
('ssiap1-q94', 0, 'Identifier la zone d''alarme sur le tableau de signalisation'),
('ssiap1-q94', 1, 'Déclencher immédiatement l''alarme générale d''évacuation sans vérification'),
('ssiap1-q94', 2, 'Effectuer la levée de doute en se rendant physiquement sur la zone concernée'),
('ssiap1-q94', 3, 'Alerter les pompiers avant toute vérification'),
('ssiap1-q94', 4, 'Prévenir son responsable hiérarchique'),
('ssiap1-q95', 0, 'Filtrer l''air pour éviter la propagation des fumées'),
('ssiap1-q95', 1, 'Se fermer automatiquement pour empêcher la propagation du feu et des fumées par les gaines'),
('ssiap1-q95', 2, 'Accélérer le désenfumage en augmentant le débit d''air'),
('ssiap1-q95', 3, 'Mesurer la température dans les gaines'),
('ssiap1-q95', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q96', 0, 'Uniquement dans la zone sinistrée'),
('ssiap1-q96', 1, 'Dans tous les locaux accessibles au public et dans les locaux de travail'),
('ssiap1-q96', 2, 'Seulement aux agents SSIAP'),
('ssiap1-q96', 3, 'Dans un rayon de 50 mètres autour du foyer'),
('ssiap1-q96', 4, 'Uniquement dans les couloirs et zones de circulation'),
('ssiap1-q97', 0, 'Les portes coupe-feu à fermeture automatique (DAS)'),
('ssiap1-q97', 1, 'Les détecteurs automatiques de fumée'),
('ssiap1-q97', 2, 'Les exutoires de désenfumage (DAS)'),
('ssiap1-q97', 3, 'Les déclencheurs manuels (boîtiers brise-glace)'),
('ssiap1-q97', 4, 'L''Équipement de Contrôle et de Signalisation (ECS)'),
('ssiap1-q98', 0, 'Commander l''extinction automatique par sprinklers'),
('ssiap1-q98', 1, 'Permettre à la réception (ou au personnel de veille) de visualiser les alarmes et d''effectuer la levée de doute sans se rendre au PC sécurité'),
('ssiap1-q98', 2, 'Afficher les plans d''évacuation pour les clients'),
('ssiap1-q98', 3, 'Gérer la vidéosurveillance de l''établissement'),
('ssiap1-q98', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q131', 0, 'Un extincteur centralisé commandant toute l''installation de désenfumage'),
('ssiap1-q131', 1, 'L''équipement central du SMSI qui reçoit les informations du SDI et commande les DAS'),
('ssiap1-q131', 2, 'Un système de vidéosurveillance centralisé'),
('ssiap1-q131', 3, 'Un organe de coupure général de l''alimentation électrique'),
('ssiap1-q131', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q132', 0, 'Le bon fonctionnement de chaque détecteur (test par fumée ou chaleur simulée)'),
('ssiap1-q132', 1, 'La transmission de l''alarme au PC sécurité'),
('ssiap1-q132', 2, 'Le déclenchement effectif des DAS (portes CF, exutoires)'),
('ssiap1-q132', 3, 'La couleur du signal lumineux des détecteurs'),
('ssiap1-q132', 4, 'Le contenu du registre de sécurité'),
('ssiap1-q133', 0, '15 minutes'),
('ssiap1-q133', 1, '30 minutes'),
('ssiap1-q133', 2, '1 heure'),
('ssiap1-q133', 3, '12 heures'),
('ssiap1-q133', 4, '24 heures'),
('ssiap1-q134', 0, 'Détection automatique dans quelques locaux + alarm générale avec SMSI complet'),
('ssiap1-q134', 1, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q134', 2, 'Déclencheurs manuels uniquement + diffuseurs sonores sans centrale'),
('ssiap1-q134', 3, 'Système de détection par sprinklers uniquement'),
('ssiap1-q135', 0, 'Orange'),
('ssiap1-q135', 1, 'Rouge'),
('ssiap1-q135', 2, 'Jaune'),
('ssiap1-q135', 3, 'Blanc'),
('ssiap1-q135', 4, 'Vert'),
('ssiap1-q136', 0, 'Effectuer une levée de doute visuelle depuis le PC sans se déplacer dans certains cas'),
('ssiap1-q136', 1, 'Surveiller les zones à risques et les accès du bâtiment'),
('ssiap1-q136', 2, 'Remplacer totalement les rondes physiques'),
('ssiap1-q136', 3, 'Observer le comportement des occupants en temps réel'),
('ssiap1-q136', 4, 'Se substituer aux détecteurs automatiques de fumée'),
('ssiap1-q172', 0, 'De nommer chaque détecteur pour l''identifier précisément sur le tableau de signalisation'),
('ssiap1-q172', 1, 'De programmer la sensibilité de chaque détecteur à distance'),
('ssiap1-q172', 2, 'De remplacer les rondes physiques'),
('ssiap1-q172', 3, 'De connecter le système à internet'),
('ssiap1-q172', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q173', 0, 'Il n''y a pas de limite, l''agent doit prendre le temps nécessaire'),
('ssiap1-q173', 1, 'La levée de doute ne doit pas dépasser 3 à 5 minutes avant déclenchement de l''alarme générale'),
('ssiap1-q173', 2, 'L''agent doit attendre 15 minutes pour éviter les fausses alarmes'),
('ssiap1-q173', 3, 'Il doit déclencher l''alarme générale immédiatement sans levée de doute'),
('ssiap1-q173', 4, 'Il doit attendre le retour de son collègue en ronde'),
('ssiap1-q174', 0, 'Un incendie est en cours'),
('ssiap1-q174', 1, 'Un composant du système (détecteur, câble, alimentation) ne fonctionne pas correctement'),
('ssiap1-q174', 2, 'Le système est en cours de test'),
('ssiap1-q174', 3, 'La batterie de secours est pleinement chargée'),
('ssiap1-q174', 4, 'Aucune de ces réponses n''est correcte');
commit;
