begin;
-- SSIAP 1 — Le feu et ses conséquences (partie 1, sub 3/3, 20 questions)
insert into public.questions (
  id, module_id, type, question, explanation, correct_answer, correct_answers, tags, display_order
) values
('ssiap1-q113', 'ssiap1-partie1', 'quiz', 'La teneur normale en oxygène dans l''air atmosphérique est de :', 'La teneur normale en oxygène dans l''air atmosphérique est de 21 % (plus précisément 20,9 %). Aucune des propositions (16 %, 18 %, 25 %, 30 %) n''est correcte. En dessous de 15 %, la combustion ne peut plus être entretenue. En dessous de 16 %, les premiers effets physiologiques apparaissent chez l''homme (essoufflement). Les systèmes d''extinction par réduction d''oxygène maintiennent l''atmosphère entre 15 % et 16 % pour empêcher la combustion tout en permettant au personnel d''intervenir brièvement.', 3, null::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 40),
('ssiap1-q114', 'ssiap1-partie1', 'multiple-select', 'Un feu de voiture en parking souterrain implique quelles classes de feu ? (plusieurs réponses possibles)', 'Un incendie de véhicule peut impliquer plusieurs classes de feu simultanément : Classe A (matières solides : plastiques de l''habitacle, tissus, mousse des sièges, caoutchoucs) ; Classe B (liquides inflammables : essence ou diesel, huile moteur, liquide de frein, liquide de refroidissement si inflammable) ; Classe C (gaz) si le véhicule fonctionne au GPL ou GNV (fuite possible). La carrosserie en acier et aluminium ne brûle pas dans des conditions normales d''incendie de véhicule (classe D non applicable ici). Les huiles de cuisson (classe F) n''ont rien à voir avec un véhicule.', null, array[0,1,2]::integer[], array['theme4','seq1','Classes de feu','La combustion']::text[], 41),
('ssiap1-q115', 'ssiap1-partie1', 'quiz', 'La teneur en CO (monoxyde de carbone) devient immédiatement mortelle à partir de quelle concentration dans l''air ?', 'Les seuils de danger du CO : 100 ppm : maux de tête après 2-3 heures ; 400 ppm : maux de tête violents après 3 heures ; 1 500 ppm : dangereux après 1 heure d''exposition ; 6 400 ppm : mort en moins de 30 minutes ; 12 800 ppm (1,28 %) : mort immédiate. Pour référence, une atmosphère d''incendie contient souvent entre 1 000 et 10 000 ppm de CO. Les détecteurs de CO domestiques sonnent l''alarme à 50-70 ppm (seuil sur 8 heures). Le CO est indétectable par l''homme sans appareil de mesure.', 3, null::integer[], array['theme3','seq1','Produits de la combustion et effets','La combustion']::text[], 42),
('ssiap1-q116', 'ssiap1-partie1', 'multiple-select', 'La mousse extinctrice agit principalement sur le feu par : (plusieurs réponses possibles)', 'La mousse extinctrice agit par deux mécanismes principaux : l''étouffement, en formant un tapis de mousse imperméable qui sépare la surface du liquide inflammable de l''oxygène de l''air ; et le refroidissement, car la mousse contient une forte proportion d''eau qui absorbe la chaleur en s''évaporant. Elle n''agit pas directement sur la réaction en chaîne (contrairement à la poudre) ni ne dilue les gaz. Elle est particulièrement efficace sur les feux de classe B (liquides inflammables) et certains feux de classe A. Elle est déconseillée sur les feux de métaux et équipements électriques sous tension.', null, array[0,1]::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 43),
('ssiap1-q117', 'ssiap1-partie1', 'quiz', 'Lors d''un feu de forêt (végétation, broussailles, arbres), quelle classe de feu s''applique principalement ?', 'Les feux de forêt (feux de végétation, broussailles, herbe sèche, bois) sont des feux de classe A : combustion de matières solides d''origine organique produisant des braises. L''eau reste le meilleur agent extincteur (refroidissement et pénétration des braises). La propagation par projection (brandons portés par le vent) est un risque majeur dans les feux de forêt. La lutte contre les feux de forêt est assurée par les SDIS (Services Départementaux d''Incendie et de Secours) avec des moyens spécialisés (canadairs, bombardiers d''eau, VLHR).', 0, null::integer[], array['theme4','seq1','Classes de feu','La combustion']::text[], 44),
('ssiap1-q118', 'ssiap1-partie1', 'quiz', 'Un feu se propage de l''appartement du 3ème étage vers les niveaux supérieurs par les gaines de vide-ordures. Ce mode de propagation est principalement :', 'Les gaines verticales (vide-ordures, gaines techniques, gaines de ventilation) constituent des voies de propagation privilégiées par convection : les gaz chauds et les flammes remontent naturellement dans ces espaces confinés et verticaux, pouvant enflammer chaque niveau qu''ils traversent. Ce phénomène explique pourquoi les gaines doivent être équipées de clapets coupe-feu à chaque niveau. Les vides d''ordures ont été progressivement supprimés des immeubles modernes en partie pour cette raison. La conduction est possible mais plus lente, le rayonnement est limité dans un espace confiné.', 1, null::integer[], array['theme2','seq1','Modes de propagation de la chaleur','La combustion']::text[], 45),
('ssiap1-q119', 'ssiap1-partie1', 'quiz', 'Quels matériaux sont considérés comme bons conducteurs thermiques et favorisent la propagation du feu par conduction ? (plusieurs réponses possibles)', 'Les métaux (acier, aluminium, cuivre) sont d''excellents conducteurs thermiques et peuvent transmettre la chaleur à travers les parois ou structures qu''ils traversent. C''est pourquoi les poutres et colonnes métalliques traversant les planchers coupe-feu doivent être protégées (manchons coupe-feu, encoffrement). Le béton, le verre, le bois et les matériaux isolants sont de mauvais conducteurs thermiques. Paradoxalement, le bois est un meilleur isolant thermique que l''acier, même s''il est combustible. Les matériaux isolants ont été justement conçus pour limiter les transferts de chaleur.', 0, null::integer[], array['theme2','seq1','Modes de propagation de la chaleur','La combustion']::text[], 46),
('ssiap1-q120', 'ssiap1-partie1', 'multiple-select', 'L''acide cyanhydrique (HCN) se distingue du monoxyde de carbone (CO) car : (plusieurs réponses possibles)', 'L''HCN (acide cyanhydrique ou prussique) est produit par la combustion de matières azotées (polyuréthanes, nylons, laine, soie, certains plastiques). Sa toxicité est 25 fois supérieure à celle du CO. Contrairement au CO qui bloque le transport de l''oxygène, l''HCN bloque la respiration cellulaire en inhibant la cytochrome oxydase (chaîne respiratoire mitochondriale) : les cellules ne peuvent plus utiliser l''oxygène même si celui-ci est présent. L''odeur d''amandes amères est caractéristique mais beaucoup de personnes ne peuvent pas la détecter génétiquement (anosmie à l''HCN). L''HCN reste dangereux quelle que soit la température.', null, array[0,1,3]::integer[], array['theme3','seq1','Produits de la combustion et effets','La combustion']::text[], 47),
('ssiap1-q152', 'ssiap1-partie1', 'quiz', 'Qu''est-ce que l''auto-inflammation par accumulation de chaleur ? Donnez un exemple concret.', 'L''auto-inflammation par accumulation de chaleur (ou combustion spontanée) est le phénomène par lequel un matériau s''enflamme sans source d''ignition externe, par élévation progressive de sa température due à une réaction exothermique interne. Exemple classique : les chiffons imprégnés d''huile siccative (lin, teck, tung) qui s''oxydent en dégageant de la chaleur. Si entassés, la chaleur s''accumule et peut atteindre la température d''auto-inflammation. D''autres exemples : tas de foin humide (fermentation), charbon de bois stocké en masse, certains engrais. C''est pourquoi ces matériaux doivent être stockés à plat, séchés, dans des contenants ouverts.', 0, null::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 48),
('ssiap1-q153', 'ssiap1-partie1', 'multiple-select', 'La densité de fumée affecte directement l''évacuation des occupants. Quelles en sont les conséquences ? (plusieurs réponses possibles)', 'Les fumées denses ont plusieurs effets néfastes sur l''évacuation : réduction de la visibilité (parfois à quelques centimètres), rendant les pictogrammes et cheminements invisibles ; irritation intense des voies respiratoires (toux, suffocation) et des yeux (larmoiement, brûlures), ralentissant les déplacements ; création de panique chez les occupants, augmentant le risque de bousculades et de chutes. Des études montrent que la vitesse de déplacement peut chuter de 1,2 m/s en conditions normales à 0,3 m/s dans les fumées. C''est pourquoi il est recommandé de se baisser pour trouver l''air plus frais et de ramper si nécessaire.', null, array[0,1,2]::integer[], array['theme3','seq1','Produits de la combustion et effets','La combustion']::text[], 49),
('ssiap1-q154', 'ssiap1-partie1', 'quiz', 'La température d''auto-inflammation du bois sec est d''environ :', 'La température d''auto-inflammation du bois sec est d''environ 250 à 300 °C selon l''essence et le degré de séchage. La pyrolyse (décomposition thermique sans oxygène) commence vers 200-250 °C, et les gaz produits s''enflamment spontanément autour de 250-300 °C. Aucune des propositions (100°C, 150°C, 600°C) n''est correcte. Pour information : l''essence s''enflamme spontanément vers 280 °C, le papier vers 233 °C (d''où le titre du roman ''Fahrenheit 451'' de Ray Bradbury), le polyéthylène vers 350 °C.', 0, null::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 50),
('ssiap1-q155', 'ssiap1-partie1', 'quiz', 'Le phénomène de stratification des fumées lors d''un incendie signifie que :', 'La stratification des fumées est un phénomène physique résultant de la différence de densité entre les gaz chauds (légers) et l''air froid (lourd). Les fumées chaudes montent et s''accumulent en couche sous le plafond, tandis que l''air plus frais reste en partie basse. Ce phénomène explique pourquoi il faut se baisser voire ramper lors d''une évacuation dans un couloir enfumé : l''air respirant se trouve près du sol. La stratification disparaît progressivement quand la fumée se refroidit ou quand l''apport de fumées est très important.', 1, null::integer[], array['theme3','seq1','Produits de la combustion et effets','La combustion']::text[], 51),
('ssiap1-q156', 'ssiap1-partie1', 'multiple-select', 'Un feu de cuisine dans une friteuse professionnelle s''enflamme. Quelles actions sont correctes ? (plusieurs réponses possibles)', 'Pour un feu de friteuse : utiliser un extincteur classe F (à acétate de potassium) conçu spécifiquement pour les huiles de cuisson ; couvrir avec un couvercle ou une plaque métallique (étouffement, suppression du comburant) ; couper l''alimentation (électricité ou gaz) pour stopper le chauffage. Si le feu ne peut être maîtrisé immédiatement, appeler les pompiers. Jeter de l''eau dans une friteuse en feu est EXTRÊMEMENT DANGEREUX : l''eau se vaporise instantanément au contact de l''huile surchauffée (300-400 °C), créant une explosion de gouttelettes d''huile enflammées projetées à plusieurs mètres (boule de feu). C''est l''une des causes les plus fréquentes de brûlures graves en restauration.', null, array[0,1,3,4]::integer[], array['theme4','seq1','Classes de feu','La combustion']::text[], 52),
('ssiap1-q157', 'ssiap1-partie1', 'quiz', 'La résistance au feu d''un élément de construction REI 120 signifie :', 'La classification de résistance au feu européenne (EN 13501-2) utilise trois critères : R (Résistance mécanique - capacité portante), E (Étanchéité aux flammes et gaz chauds), I (Isolation thermique - face non exposée < 140°C en moyenne). Le nombre indique la durée en minutes. REI 120 = les 3 critères sont satisfaits pendant 120 minutes (2 heures). Les éléments porteurs de planchers sont REI, les cloisons non porteuses peuvent être EI. Les durées réglementaires courantes sont 30, 60, 90, 120, 180 et 240 minutes.', 1, null::integer[], array['theme7','seq3','Effets du feu sur les structures','Conséquences sur les personnes et les biens']::text[], 53),
('ssiap1-q158', 'ssiap1-partie1', 'multiple-select', 'Quelles sont les principales causes d''incendie dans les ERP ? (plusieurs réponses possibles)', 'Les principales causes d''incendie dans les ERP et bâtiments sont : les défauts électriques (première cause en France : court-circuit, surcharge de câble, arc électrique, vieillissement des installations) ; les imprudences liées au tabac (mégots mal éteints dans les corbeilles, sur les balcons) ; les travaux par points chauds (brûlures de matériaux isolants, projections de métal fondu) ; la malveillance (incendies volontaires, 2ème ou 3ème cause selon les secteurs). Les systèmes de protection comme les sprinklers sont des moyens de lutte, non des causes d''incendie.', null, array[0,1,2,3]::integer[], array['theme7','seq3','Effets du feu sur les structures','Conséquences sur les personnes et les biens']::text[], 54),
('ssiap1-q159', 'ssiap1-partie1', 'quiz', 'Le ''feu de nappe'' est caractéristique des feux de :', 'Le feu de nappe est un type de feu de classe B caractéristique des liquides inflammables répandus en nappe sur le sol (ou sur l''eau). La nappe de liquide inflammable (essence, solvants, huiles) brûle en surface avec des flammes plates et s''étend facilement. Les extincteurs à mousse sont particulièrement efficaces car ils forment un tapis imperméable sur toute la surface de la nappe. Le feu de nappe est très difficile à circonscrire car le liquide peut s''écouler et propager l''incendie. Les bacs de rétention sont obligatoires pour les stockages de liquides inflammables afin d''éviter la formation de nappe.', 1, null::integer[], array['theme4','seq1','Classes de feu','La combustion']::text[], 55),
('ssiap1-q160', 'ssiap1-partie1', 'quiz', 'Quel est l''effet de l''humidité sur la combustibilité d''un matériau solide ?', 'L''humidité d''un matériau retarde ou empêche sa combustion pour deux raisons : l''eau contenue doit d''abord être vaporisée avant que la pyrolyse puisse commencer (ce qui absorbe de l''énergie : 2 257 kJ/kg pour la vaporisation de l''eau) ; la vapeur d''eau diluele les gaz combustibles et le comburant. C''est pourquoi le bois vert brûle mal, le foin humide couve plutôt qu''il ne flambe, et qu''un incendie se propage moins vite par temps humide. En revanche, l''humidité peut favoriser la combustion lente (couvante) dans certains matériaux organiques.', 2, null::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 56),
('ssiap1-q161', 'ssiap1-partie1', 'multiple-select', 'Quels sont les effets physiologiques du dioxyde de carbone (CO2) à haute concentration lors d''un incendie ? (plusieurs réponses possibles)', 'Le CO2 n''est pas directement toxique mais ses effets à haute concentration sont dangereux : à 3-5 %, il accélère le rythme respiratoire (hyperventilation), augmentant ainsi l''absorption de tous les autres gaz toxiques présents ; à 7-10 %, maux de tête intenses, perte de conscience possible ; à >10 %, asphyxie par manque d''oxygène et sensation de brûlure dans les voies respiratoires (réaction acide de l''acide carbonique). De plus, chaque inspiration dans une atmosphère enrichie en CO2 entraîne davantage d''inhalation de CO, HCN et autres gaz toxiques. Le CO2 n''est donc pas inoffensif à haute concentration.', null, array[0,1,2,3]::integer[], array['theme3','seq1','Produits de la combustion et effets','La combustion']::text[], 57),
('ssiap1-q194', 'ssiap1-partie1', 'multiple-select', 'Quels sont les effets des hautes températures des fumées sur les voies respiratoires ? (plusieurs réponses possibles)', 'Les gaz et fumées à haute température causent des lésions graves des voies respiratoires : brûlures thermiques des muqueuses nasales, pharyngées, trachéales et bronchiques ; œdème glottique (gonflement de la glotte et des cordes vocales) pouvant survenir plusieurs heures après l''exposition et obstruer complètement les voies aériennes ; bronchospasme réflexe (contraction des muscles bronchiques) réduisant le calibre des bronches et provoquant une détresse respiratoire. Ces lésions peuvent apparaître avec un délai de quelques heures et être mortelles même après évacuation. Les victimes exposées à des fumées chaudes doivent être systématiquement examinées par les secours médicaux même si elles semblent bien.', null, array[0,1,3]::integer[], array['theme7','seq3','Effets du feu sur les structures','Conséquences sur les personnes et les biens']::text[], 58),
('ssiap1-q197', 'ssiap1-partie1', 'multiple-select', 'Quels sont les 3 principes d''extinction d''un feu correspondant aux 3 côtés du triangle du feu ? (plusieurs réponses possibles)', 'Les trois principes d''extinction correspondent exactement aux trois côtés du triangle du feu : 1) Refroidissement = suppression de l''énergie d''activation (l''eau refroidit le combustible en dessous de son point d''ignition) ; 2) Étouffement = suppression du comburant (la mousse ou le CO2 réduisent l''oxygène disponible) ; 3) Isolation/Séparation = suppression du combustible (couper l''alimentation en gaz, débroussailler, éloigner les matières combustibles). Le 4ème principe, inhibition de la réaction en chaîne (poudre), correspond au 4ème côté du tétraèdre du feu. La pressurisation et la dilution sont des effets secondaires, non des principes d''extinction primaires.', null, array[0,1,2]::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 59)
on conflict (id) do update set
  type=excluded.type, question=excluded.question, explanation=excluded.explanation,
  correct_answer=excluded.correct_answer, correct_answers=excluded.correct_answers,
  tags=excluded.tags, display_order=excluded.display_order, updated_at=now();
delete from public.question_options where question_id in ('ssiap1-q113','ssiap1-q114','ssiap1-q115','ssiap1-q116','ssiap1-q117','ssiap1-q118','ssiap1-q119','ssiap1-q120','ssiap1-q152','ssiap1-q153','ssiap1-q154','ssiap1-q155','ssiap1-q156','ssiap1-q157','ssiap1-q158','ssiap1-q159','ssiap1-q160','ssiap1-q161','ssiap1-q194','ssiap1-q197');
insert into public.question_options (question_id, option_index, option_text) values
('ssiap1-q113', 0, '16 %'),
('ssiap1-q113', 1, '18 %'),
('ssiap1-q113', 2, '25 %'),
('ssiap1-q113', 3, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q113', 4, '30 %'),
('ssiap1-q114', 0, 'Classe A (plastiques, textiles de la sellerie, bois du tableau de bord)'),
('ssiap1-q114', 1, 'Classe B (carburant, huiles de moteur)'),
('ssiap1-q114', 2, 'Classe C (si fuite de gaz sur véhicule GPL)'),
('ssiap1-q114', 3, 'Classe D (métaux de la carrosserie)'),
('ssiap1-q114', 4, 'Classe F (huile de friture)'),
('ssiap1-q115', 0, '100 ppm'),
('ssiap1-q115', 1, '400 ppm'),
('ssiap1-q115', 2, '1 500 ppm'),
('ssiap1-q115', 3, '12 800 ppm'),
('ssiap1-q115', 4, '6 400 ppm'),
('ssiap1-q116', 0, 'Étouffement (séparation combustible/comburant par le tapis de mousse)'),
('ssiap1-q116', 1, 'Refroidissement de la surface du combustible'),
('ssiap1-q116', 2, 'Action inhibitrice sur la réaction en chaîne'),
('ssiap1-q116', 3, 'Dilution des gaz combustibles dans l''air'),
('ssiap1-q116', 4, 'Solidification du combustible en surface'),
('ssiap1-q117', 0, 'Classe A'),
('ssiap1-q117', 1, 'Classe B'),
('ssiap1-q117', 2, 'Classe C'),
('ssiap1-q117', 3, 'Classe D'),
('ssiap1-q117', 4, 'Classe F'),
('ssiap1-q118', 0, 'La conduction thermique des parois'),
('ssiap1-q118', 1, 'La convection par déplacement des gaz chauds dans les gaines'),
('ssiap1-q118', 2, 'Le rayonnement thermique'),
('ssiap1-q118', 3, 'La projection de brandons'),
('ssiap1-q118', 4, 'L''auto-inflammation spontanée'),
('ssiap1-q119', 0, 'L''acier et les métaux en général'),
('ssiap1-q119', 1, 'Le béton non armé'),
('ssiap1-q119', 2, 'Le verre'),
('ssiap1-q119', 3, 'Le bois'),
('ssiap1-q119', 4, 'Les matériaux isolants (laine de roche, polystyrène)'),
('ssiap1-q120', 0, 'Il est produit par la combustion de matières azotées (polyuréthanes, nylon, soie)'),
('ssiap1-q120', 1, 'Il est beaucoup plus toxique que le CO à concentrations équivalentes'),
('ssiap1-q120', 2, 'Il est facilement détectable à l''odeur (amandes amères) dans toutes les conditions'),
('ssiap1-q120', 3, 'Il agit en bloquant la respiration cellulaire (chaîne respiratoire mitochondriale)'),
('ssiap1-q120', 4, 'Il est inefficace en atmosphère chaude'),
('ssiap1-q152', 0, 'Un chiffon imprégné d''huile siccative (huile de lin) peut s''enflammer spontanément si entassé en tas compact'),
('ssiap1-q152', 1, 'Un bidon d''essence peut s''enflammer seul à température ambiante'),
('ssiap1-q152', 2, 'Le bois sec peut s''enflammer seul à 20 °C si exposé au soleil'),
('ssiap1-q152', 3, 'L''acier peut s''enflammer seul sans apport de chaleur externe'),
('ssiap1-q152', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q153', 0, 'Réduction de la visibilité, rendant les cheminements d''évacuation difficiles à suivre'),
('ssiap1-q153', 1, 'Irritation des voies respiratoires et des yeux, ralentissant l''évacuation'),
('ssiap1-q153', 2, 'Augmentation de la panique et des risques de bousculades'),
('ssiap1-q153', 3, 'Amélioration de la résistance thermique des structures'),
('ssiap1-q153', 4, 'Augmentation de la luminosité dans les couloirs'),
('ssiap1-q154', 0, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q154', 1, '100 °C'),
('ssiap1-q154', 2, '150 °C'),
('ssiap1-q154', 3, '600 °C'),
('ssiap1-q155', 0, 'Les fumées froides et denses descendent vers le sol'),
('ssiap1-q155', 1, 'Les fumées chaudes et légères s''accumulent en couche sous le plafond, avec de l''air plus frais en partie basse'),
('ssiap1-q155', 2, 'Les fumées se répartissent uniformément dans le local'),
('ssiap1-q155', 3, 'Les fumées traversent les parois par osmose'),
('ssiap1-q155', 4, 'Les fumées restent au niveau du foyer d''incendie'),
('ssiap1-q156', 0, 'Utiliser un extincteur de classe F'),
('ssiap1-q156', 1, 'Couvrir la friteuse avec un couvercle pour étouffer le feu'),
('ssiap1-q156', 2, 'Jeter de l''eau dans la friteuse pour refroidir l''huile'),
('ssiap1-q156', 3, 'Couper l''alimentation électrique ou gaz de la friteuse'),
('ssiap1-q156', 4, 'Appeler les pompiers si le feu ne peut être maîtrisé'),
('ssiap1-q157', 0, 'Résistance mécanique, Étanchéité aux flammes et Isolation thermique pendant 12 minutes'),
('ssiap1-q157', 1, 'Résistance mécanique, Étanchéité aux flammes et Isolation thermique pendant 120 minutes'),
('ssiap1-q157', 2, 'Résistance à un séisme de magnitude 1,2'),
('ssiap1-q157', 3, 'Résistance à une pression de 120 bars'),
('ssiap1-q157', 4, 'Résistance Électrique et Ignifuge pendant 120 heures'),
('ssiap1-q158', 0, 'Défauts électriques (court-circuit, surcharge, arc électrique)'),
('ssiap1-q158', 1, 'Imprudences liées au tabac (mégots mal éteints)'),
('ssiap1-q158', 2, 'Travaux par points chauds (soudure, meulage)'),
('ssiap1-q158', 3, 'Malveillance et incendies volontaires'),
('ssiap1-q158', 4, 'La présence de systèmes sprinklers défaillants'),
('ssiap1-q159', 0, 'Gaz sous pression'),
('ssiap1-q159', 1, 'Liquides inflammables répandus sur le sol'),
('ssiap1-q159', 2, 'Matériaux solides en poudre fine'),
('ssiap1-q159', 3, 'Métaux alcalins'),
('ssiap1-q159', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q160', 0, 'L''humidité favorise la combustion en augmentant la conductivité thermique'),
('ssiap1-q160', 1, 'L''humidité n''a aucun effet sur la combustibilité'),
('ssiap1-q160', 2, 'L''humidité retarde ou empêche la combustion en abaissant la température et en nécessitant plus d''énergie pour la vaporisation'),
('ssiap1-q160', 3, 'L''humidité accélère la propagation des fumées'),
('ssiap1-q160', 4, 'L''humidité rend le matériau plus explosif'),
('ssiap1-q161', 0, 'Accélération du rythme respiratoire'),
('ssiap1-q161', 1, 'Augmentation de l''absorption des autres gaz toxiques'),
('ssiap1-q161', 2, 'Sensation de brûlure dans les poumons à concentration élevée'),
('ssiap1-q161', 3, 'Asphyxie par manque d''oxygène si concentration > 10 %'),
('ssiap1-q161', 4, 'Il est totalement inoffensif quelle que soit la concentration'),
('ssiap1-q194', 0, 'Brûlures des muqueuses du nez, de la gorge et des bronches'),
('ssiap1-q194', 1, 'Œdème glottique (gonflement des cordes vocales pouvant obstruer les voies aériennes)'),
('ssiap1-q194', 2, 'Renforcement du système immunitaire'),
('ssiap1-q194', 3, 'Bronchospasme (contraction des bronches) réduisant le passage de l''air'),
('ssiap1-q194', 4, 'Augmentation de la capacité pulmonaire'),
('ssiap1-q197', 0, 'Refroidissement (suppression de l''énergie)'),
('ssiap1-q197', 1, 'Étouffement (suppression du comburant)'),
('ssiap1-q197', 2, 'Isolation / Séparation (suppression du combustible)'),
('ssiap1-q197', 3, 'Pressurisation (augmentation de la pression)'),
('ssiap1-q197', 4, 'Dilution (réduction de la concentration en gaz)');
commit;
