begin;
-- SSIAP 1 — Le feu et ses conséquences (partie 1, sub 1/3, 20 questions)
insert into public.modules (id, level, title, subtitle, icon, color, display_order, is_active)
values ('ssiap1-partie1', 1, 'Le feu et ses conséquences', '60 questions', '🔥', 'from-red-500 to-orange-600', 0, true)
on conflict (id) do update set title=excluded.title, subtitle=excluded.subtitle, icon=excluded.icon, color=excluded.color, display_order=excluded.display_order;
insert into public.questions (
  id, module_id, type, question, explanation, correct_answer, correct_answers, tags, display_order
) values
('ssiap1-q0', 'ssiap1-partie1', 'quiz', 'Quels sont les trois éléments indispensables à la combustion selon le triangle du feu ?', 'Le triangle du feu représente les trois éléments nécessaires à la combustion : le combustible (matière qui brûle), le comburant (généralement l''oxygène de l''air) et l''énergie d''activation (chaleur ou étincelle nécessaire pour amorcer la réaction). L''absence de l''un de ces trois éléments empêche ou éteint le feu.', 0, null::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 0),
('ssiap1-q1', 'ssiap1-partie1', 'quiz', 'Le tétraèdre du feu ajoute un quatrième élément au triangle du feu. Lequel ?', 'Le tétraèdre du feu est une évolution du triangle du feu. Il ajoute un quatrième élément : la réaction en chaîne (ou chaîne de combustion). Cette réaction en chaîne correspond à la propagation des radicaux libres qui entretiennent la combustion. Les agents extincteurs halogénés agissent spécifiquement sur cet élément.', 0, null::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 1),
('ssiap1-q2', 'ssiap1-partie1', 'quiz', 'Quelle est la teneur minimale en oxygène dans l''air nécessaire pour qu''une combustion soit possible ?', 'L''air contient normalement 21 % d''oxygène. La combustion est possible jusqu''à une teneur de 15 % environ. En dessous de 15 %, la combustion s''arrête faute de comburant suffisant. C''est le principe des systèmes d''extinction par réduction d''oxygène (hypoxie) utilisés dans certaines salles techniques.', 1, null::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 2),
('ssiap1-q3', 'ssiap1-partie1', 'quiz', 'Comment appelle-t-on le phénomène de décomposition thermique d''un combustible solide ou liquide avant inflammation ?', 'La pyrolyse est la décomposition thermique d''un matériau sous l''effet de la chaleur, sans présence d''oxygène. Elle produit des gaz combustibles qui, mélangés à l''air, pourront s''enflammer. La pyrolyse du bois, par exemple, produit des gaz inflammables à partir de 250–300 °C. Comprendre la pyrolyse est essentiel pour anticiper le comportement des matériaux en feu.', 1, null::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 3),
('ssiap1-q4', 'ssiap1-partie1', 'quiz', 'Qu''est-ce que le point éclair d''un liquide inflammable ?', 'Le point éclair (ou point d''éclair) est la température minimale à laquelle un liquide inflammable émet suffisamment de vapeurs pour former, avec l''air ambiant, un mélange qui s''enflamme momentanément au contact d''une source d''allumage. Il ne faut pas confondre avec le point d''auto-inflammation, où le liquide s''enflamme sans apport extérieur. Le point éclair est crucial pour le classement des liquides inflammables (ex : essence ≈ -40 °C, gazole ≈ 55 °C).', 1, null::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 4),
('ssiap1-q5', 'ssiap1-partie1', 'quiz', 'Parmi les propositions suivantes, laquelle décrit correctement la combustion vive ?', 'La combustion vive est une combustion rapide caractérisée par la présence de flammes et un fort dégagement de chaleur et de lumière. Elle s''oppose à la combustion lente (ou couvante) qui se déroule sans flamme visible, avec des braises et des fumées. L''incendie classique est une combustion vive. La combustion lente peut précéder l''embrasement général dans certaines situations.', 1, null::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 5),
('ssiap1-q6', 'ssiap1-partie1', 'quiz', 'La conduction est un mode de propagation de la chaleur. Comment se propage-t-elle ?', 'La conduction thermique est le transfert de chaleur qui se produit par contact direct entre les molécules d''un matériau ou entre deux matériaux en contact. Elle est particulièrement efficace dans les métaux (bons conducteurs). Un exemple classique : une barre métallique chauffée à une extrémité transmet la chaleur à l''autre extrémité par conduction. Dans un incendie, les structures métalliques peuvent conduire la chaleur à travers les cloisons.', 1, null::integer[], array['theme2','seq1','Modes de propagation de la chaleur','La combustion']::text[], 6),
('ssiap1-q7', 'ssiap1-partie1', 'quiz', 'La convection est responsable de la majorité des décès lors d''un incendie. Par quoi se caractérise-t-elle ?', 'La convection est le mode de propagation de la chaleur par déplacement de masses fluides (gaz chauds, fumées). Les fumées et gaz chauds montent naturellement et se propagent horizontalement sous les plafonds. La convection est le principal vecteur de propagation d''un incendie d''un local à un autre (par les couloirs, cages d''escalier, gaines techniques). Elle est responsable d''une grande partie des victimes car les fumées toxiques progressent rapidement et silencieusement.', 1, null::integer[], array['theme2','seq1','Modes de propagation de la chaleur','La combustion']::text[], 7),
('ssiap1-q8', 'ssiap1-partie1', 'quiz', 'Le rayonnement thermique peut provoquer un incendie à distance. Quelle est sa caractéristique principale ?', 'Le rayonnement thermique est un transfert de chaleur par ondes électromagnétiques (infrarouges). Sa particularité est de ne nécessiter aucun support matériel : il peut se propager dans le vide. Lors d''un incendie, le rayonnement peut enflammer des matériaux situés à plusieurs mètres du foyer initial, même sans contact ou convection. C''est pourquoi il faut maintenir des distances de sécurité entre les bâtiments (principes de compartimentage).', 2, null::integer[], array['theme2','seq1','Modes de propagation de la chaleur','La combustion']::text[], 8),
('ssiap1-q9', 'ssiap1-partie1', 'quiz', 'Des escarbilles portées par le vent allument un feu à 200 mètres du foyer principal. De quel mode de propagation s''agit-il ?', 'La projection (ou transport de brandons) est un mode de propagation particulier aux incendies de grande ampleur (feux de forêt, incendies industriels). Des particules enflammées ou des brandons sont transportés par le vent ou les courants thermiques et peuvent allumer de nouveaux foyers à grande distance. C''est l''un des modes de propagation les plus redoutés car il peut créer des foyers simultanés dans plusieurs zones.', 3, null::integer[], array['theme2','seq1','Modes de propagation de la chaleur','La combustion']::text[], 9),
('ssiap1-q10', 'ssiap1-partie1', 'quiz', 'Lors d''un incendie dans un immeuble, les fumées se propagent principalement vers :', 'Les fumées chaudes, plus légères que l''air ambiant, montent naturellement (phénomène de convection). Elles se propagent vers les niveaux supérieurs via les cages d''escalier, les gaines techniques et les vides de construction. Horizontalement, elles s''accumulent en couche sous les plafonds. C''est pourquoi les plans d''évacuation prévoient de se maintenir le plus bas possible (l''air plus frais reste près du sol) et de ne pas utiliser les ascenseurs.', 1, null::integer[], array['theme2','seq1','Modes de propagation de la chaleur','La combustion']::text[], 10),
('ssiap1-q11', 'ssiap1-partie1', 'quiz', 'Quelle est la principale cause de décès lors des incendies ?', 'L''intoxication par les fumées et gaz toxiques est la principale cause de décès lors des incendies (environ 80 % des victimes). La fumée contient du monoxyde de carbone (CO), du dioxyde de carbone (CO2), et de nombreux gaz toxiques issus de la combustion des matériaux synthétiques (acide cyanhydrique HCN, chlorure d''hydrogène HCl, etc.). Ces gaz peuvent provoquer la mort en quelques minutes même loin du foyer.', 1, null::integer[], array['theme3','seq1','Produits de la combustion et effets','La combustion']::text[], 11),
('ssiap1-q12', 'ssiap1-partie1', 'quiz', 'Le monoxyde de carbone (CO) est particulièrement dangereux lors d''un incendie. Pourquoi ?', 'Le monoxyde de carbone (CO) est un gaz incolore et inodore, produit par la combustion incomplète. Il est extrêmement toxique car il se fixe sur l''hémoglobine du sang avec une affinité 200 fois supérieure à l''oxygène (O2). Il empêche ainsi le transport de l''oxygène vers les organes, provoquant une asphyxie chimique. Son caractère imperceptible le rend d''autant plus dangereux : les victimes peuvent perdre connaissance sans s''en rendre compte.', 1, null::integer[], array['theme3','seq1','Produits de la combustion et effets','La combustion']::text[], 12),
('ssiap1-q13', 'ssiap1-partie1', 'quiz', 'Quels sont les principaux produits d''une combustion complète d''un hydrocarbure ?', 'La combustion complète d''un hydrocarbure (composé de carbone et d''hydrogène) produit du dioxyde de carbone (CO2) et de la vapeur d''eau (H2O). Cette combustion nécessite un apport suffisant en oxygène. En cas de manque d''oxygène, la combustion devient incomplète et produit du monoxyde de carbone (CO), de la suie et d''autres substances toxiques. Les pompiers mesurent la teneur en CO2 et CO dans l''atmosphère pour évaluer la dangerosité.', 1, null::integer[], array['theme3','seq1','Produits de la combustion et effets','La combustion']::text[], 13),
('ssiap1-q14', 'ssiap1-partie1', 'quiz', 'La combustion de matières plastiques (PVC, polyuréthane) est particulièrement dangereuse car :', 'Les matières synthétiques contiennent des éléments chimiques complexes qui, en brûlant, produisent des gaz hautement toxiques. Le PVC (chlorure de polyvinyle) dégage du chlorure d''hydrogène (HCl). Les polyuréthanes et matières azotées libèrent de l''acide cyanhydrique (HCN), extrêmement mortel même en faible concentration. Les plastiques ignifugés bromés produisent des dibromures très toxiques. La généralisation des matériaux synthétiques dans les bâtiments a considérablement augmenté la toxicité des fumées d''incendie.', 2, null::integer[], array['theme3','seq1','Produits de la combustion et effets','La combustion']::text[], 14),
('ssiap1-q15', 'ssiap1-partie1', 'quiz', 'A quelle classe de feu correspond la combustion de bois, papier, carton et textiles ?', 'La classe A regroupe les feux de matières solides, généralement d''origine organique, dont la combustion produit des braises. Exemples : bois, papier, carton, textiles, paille, certains plastiques. L''extincteur à eau (pulvérisée ou additif) est le plus efficace sur les feux de classe A. L''eau agit par refroidissement et étouffement.', 0, null::integer[], array['theme4','seq1','Classes de feu','La combustion']::text[], 15),
('ssiap1-q16', 'ssiap1-partie1', 'quiz', 'Un feu d''essence, de fuel ou de solvants organiques correspond à quelle classe ?', 'La classe B regroupe les feux de liquides ou de solides liquéfiables inflammables : hydrocarbures (essence, fioul, gazole), solvants, alcools, peintures, huiles minérales. Les extincteurs à mousse ou à CO2 sont adaptés aux feux de classe B. L''eau seule est contre-indiquée car elle peut projeter le liquide enflammé et aggraver l''incendie.', 1, null::integer[], array['theme4','seq1','Classes de feu','La combustion']::text[], 16),
('ssiap1-q17', 'ssiap1-partie1', 'quiz', 'Les feux de gaz (propane, butane, méthane) appartiennent à quelle classe ?', 'La classe C regroupe les feux de gaz inflammables : propane, butane, gaz naturel (méthane), hydrogène, acétylène. La priorité absolue sur un feu de gaz est de couper l''alimentation en gaz. Il ne faut pas éteindre les flammes sans couper le gaz car cela crée un risque d''explosion (accumulation de gaz puis inflammation). Les extincteurs à poudre polyvalente conviennent pour les feux de classe C.', 2, null::integer[], array['theme4','seq1','Classes de feu','La combustion']::text[], 17),
('ssiap1-q18', 'ssiap1-partie1', 'quiz', 'Les feux de métaux (magnésium, aluminium, titane) appartiennent à la classe D. Quel agent extincteur est adapté ?', 'Les feux de métaux (classe D) nécessitent des agents extincteurs spéciaux : sable sec, poudre graphite ou poudre spéciale D. L''eau est extrêmement dangereuse sur ces feux car certains métaux (magnésium, sodium) réagissent violemment avec l''eau en produisant de l''hydrogène (gaz explosif) et en aggravant l''incendie. Le CO2 et la mousse sont également contre-indiqués. La poudre D agit par smothering (étouffement) sans réaction chimique.', 2, null::integer[], array['theme4','seq1','Classes de feu','La combustion']::text[], 18),
('ssiap1-q19', 'ssiap1-partie1', 'quiz', 'Un feu dans une friteuse professionnelle (huile de cuisson surchauffée) correspond à quelle classe ?', 'La classe F a été créée pour les feux impliquant des huiles et graisses de cuisson (végétales ou animales) à haute température. Ces feux nécessitent des extincteurs spécifiques classe F (à base d''acétate de potassium). L''eau ou la mousse classique est dangereuse sur ce type de feu car l''eau se vaporise instantanément au contact de l''huile surchauffée et projette des gouttelettes d''huile enflammée (phénomène de ''crépitement''). La classe F est distincte de la classe B car les huiles de cuisson ont un comportement spécifique.', 3, null::integer[], array['theme4','seq1','Classes de feu','La combustion']::text[], 19)
on conflict (id) do update set
  type=excluded.type, question=excluded.question, explanation=excluded.explanation,
  correct_answer=excluded.correct_answer, correct_answers=excluded.correct_answers,
  tags=excluded.tags, display_order=excluded.display_order, updated_at=now();
delete from public.question_options where question_id in ('ssiap1-q0','ssiap1-q1','ssiap1-q2','ssiap1-q3','ssiap1-q4','ssiap1-q5','ssiap1-q6','ssiap1-q7','ssiap1-q8','ssiap1-q9','ssiap1-q10','ssiap1-q11','ssiap1-q12','ssiap1-q13','ssiap1-q14','ssiap1-q15','ssiap1-q16','ssiap1-q17','ssiap1-q18','ssiap1-q19');
insert into public.question_options (question_id, option_index, option_text) values
('ssiap1-q0', 0, 'Combustible, comburant, énergie d''activation'),
('ssiap1-q0', 1, 'Combustible, oxygène, eau'),
('ssiap1-q0', 2, 'Chaleur, fumée, flamme'),
('ssiap1-q0', 3, 'Carbone, hydrogène, oxygène'),
('ssiap1-q1', 0, 'La réaction en chaîne'),
('ssiap1-q1', 1, 'La fumée'),
('ssiap1-q1', 2, 'L''azote'),
('ssiap1-q1', 3, 'La pression atmosphérique'),
('ssiap1-q2', 0, '11 %'),
('ssiap1-q2', 1, '15 %'),
('ssiap1-q2', 2, '21 %'),
('ssiap1-q2', 3, '5 %'),
('ssiap1-q3', 0, 'Ignition'),
('ssiap1-q3', 1, 'Pyrolyse'),
('ssiap1-q3', 2, 'Sublimation'),
('ssiap1-q3', 3, 'Carbonisation'),
('ssiap1-q4', 0, 'La température à laquelle le liquide s''enflamme spontanément sans apport de flamme'),
('ssiap1-q4', 1, 'La température minimale à laquelle le liquide émet suffisamment de vapeurs pour former un mélange inflammable avec l''air'),
('ssiap1-q4', 2, 'La température d''ébullition du liquide'),
('ssiap1-q4', 3, 'La température à laquelle le liquide explose'),
('ssiap1-q5', 0, 'Une combustion lente avec dégagement de fumée noire et sans flamme'),
('ssiap1-q5', 1, 'Une combustion rapide avec émission de flammes et forte dégagement de chaleur'),
('ssiap1-q5', 2, 'Une combustion sans oxygène produisant uniquement de la chaleur'),
('ssiap1-q5', 3, 'Une réaction chimique endothermique'),
('ssiap1-q6', 0, 'Par déplacement de masses d''air chaud vers le haut'),
('ssiap1-q6', 1, 'Par contact direct entre matières, de molécule à molécule'),
('ssiap1-q6', 2, 'Par ondes électromagnétiques à travers le vide'),
('ssiap1-q6', 3, 'Par projection de particules enflammées'),
('ssiap1-q7', 0, 'Par le transfert de chaleur par ondes infrarouges'),
('ssiap1-q7', 1, 'Par le déplacement de masses de gaz et de fumées chauds'),
('ssiap1-q7', 2, 'Par le contact direct entre matériaux conducteurs'),
('ssiap1-q7', 3, 'Par la projection d''escarbilles et braises'),
('ssiap1-q8', 0, 'Il nécessite un support matériel pour se propager'),
('ssiap1-q8', 1, 'Il se propage uniquement dans les liquides'),
('ssiap1-q8', 2, 'Il se propage par ondes électromagnétiques et peut traverser le vide'),
('ssiap1-q8', 3, 'Il n''est efficace qu''à courte distance'),
('ssiap1-q9', 0, 'Convection'),
('ssiap1-q9', 1, 'Conduction'),
('ssiap1-q9', 2, 'Rayonnement'),
('ssiap1-q9', 3, 'Projection'),
('ssiap1-q10', 0, 'Les locaux en contrebas par conduction'),
('ssiap1-q10', 1, 'Les niveaux supérieurs et horizontalement sous les plafonds par convection'),
('ssiap1-q10', 2, 'Uniquement dans la pièce d''origine'),
('ssiap1-q10', 3, 'Les locaux proches par rayonnement exclusivement'),
('ssiap1-q11', 0, 'Les brûlures directes par les flammes'),
('ssiap1-q11', 1, 'L''intoxication aux fumées et gaz toxiques'),
('ssiap1-q11', 2, 'L''effondrement des structures'),
('ssiap1-q11', 3, 'La déshydratation'),
('ssiap1-q12', 0, 'Il est visible et odorant, ce qui retarde l''évacuation'),
('ssiap1-q12', 1, 'Il est incolore, inodore et a une forte affinité pour l''hémoglobine'),
('ssiap1-q12', 2, 'Il provoque des brûlures cutanées'),
('ssiap1-q12', 3, 'Il détruit uniquement les voies respiratoires'),
('ssiap1-q13', 0, 'Monoxyde de carbone (CO) et eau'),
('ssiap1-q13', 1, 'Dioxyde de carbone (CO2) et eau (H2O)'),
('ssiap1-q13', 2, 'Acide cyanhydrique (HCN) et CO'),
('ssiap1-q13', 3, 'Suie et gaz carbonique'),
('ssiap1-q14', 0, 'Elle produit uniquement de la chaleur'),
('ssiap1-q14', 1, 'Elle est plus lente que la combustion du bois'),
('ssiap1-q14', 2, 'Elle libère des gaz toxiques spécifiques comme l''acide cyanhydrique ou le chlorure d''hydrogène'),
('ssiap1-q14', 3, 'Elle ne produit pas de fumée'),
('ssiap1-q15', 0, 'Classe A'),
('ssiap1-q15', 1, 'Classe B'),
('ssiap1-q15', 2, 'Classe C'),
('ssiap1-q15', 3, 'Classe D'),
('ssiap1-q16', 0, 'Classe A'),
('ssiap1-q16', 1, 'Classe B'),
('ssiap1-q16', 2, 'Classe C'),
('ssiap1-q16', 3, 'Classe F'),
('ssiap1-q17', 0, 'Classe A'),
('ssiap1-q17', 1, 'Classe B'),
('ssiap1-q17', 2, 'Classe C'),
('ssiap1-q17', 3, 'Classe D'),
('ssiap1-q18', 0, 'Eau pulvérisée'),
('ssiap1-q18', 1, 'CO2 (dioxyde de carbone)'),
('ssiap1-q18', 2, 'Poudre spéciale D (sable, poudre métallique)'),
('ssiap1-q18', 3, 'Mousse'),
('ssiap1-q19', 0, 'Classe A'),
('ssiap1-q19', 1, 'Classe B'),
('ssiap1-q19', 2, 'Classe C'),
('ssiap1-q19', 3, 'Classe F');
commit;
