begin;
-- SSIAP 3 — Analyse des risques et amélioration continue (partie 5, sub 1/1, 6 questions)
insert into public.modules (id, level, title, subtitle, icon, color, display_order, is_active)
values ('ssiap3-partie5', 3, 'Analyse des risques et amélioration continue', '6 questions', '🎯', 'from-purple-500 to-pink-600', 4, true)
on conflict (id) do update set title=excluded.title, subtitle=excluded.subtitle, icon=excluded.icon, color=excluded.color, display_order=excluded.display_order;
insert into public.questions (
  id, module_id, type, question, explanation, correct_answer, correct_answers, tags, display_order
) values
('ssiap3-q20', 'ssiap3-partie5', 'quiz', 'Qu''est-ce que l''analyse des modes de défaillance, de leurs effets et de leur criticité (AMDEC) appliquée à la sécurité incendie ?', 'L''AMDEC (Analyse des Modes de Défaillance, de leurs Effets et de leur Criticité) est une méthode d''analyse préventive des risques applicable aux systèmes complexes de sécurité incendie. Pour chaque composant (détecteur, valve d''arrêt sprinkler, alimentation électrique du SSI), on identifie : les modes de défaillance possibles (court-circuit, encrassement, coupure de câble) ; les effets sur la sécurité globale si cette défaillance survient (zone non surveillée, extinction non déclenchable) ; la criticité = probabilité de défaillance × gravité de l''effet. Cette analyse permet de prioriser la maintenance (concentrer les efforts sur les composants critiques), de justifier les redondances et d''identifier les points faibles du système. Le SSIAP 3 peut utiliser cette approche pour argumenter ses décisions techniques auprès de la direction.', 1, null::integer[], array['theme1','seq1','AMDEC et méthodes d''analyse systémique','Méthodes d''analyse des risques']::text[], 0),
('ssiap3-q21', 'ssiap3-partie5', 'quiz', 'Le SSIAP 3 analyse le retour d''expérience d''un incendie survenu dans un établissement similaire au sien dans une autre ville. Comment utilise-t-il cet enseignement ?', 'Le retour d''expérience (REX) externe est une source d''apprentissage précieuse que le SSIAP 3 doit exploiter systématiquement : analyser le rapport d''incident (cause initiale, facteurs favorisants, points de défaillance, erreurs humaines ou organisationnelles) ; identifier les similitudes avec son propre établissement (même type de construction, mêmes matériaux, même configuration d''évacuation) ; prendre proactivement les mesures correctives : mise à jour du POI, renforcement d''un point faible identifié, formation du personnel sur un risque spécifique, vérification d''un équipement similaire. Attendre une obligation réglementaire pour agir après un signal d''alarme externe est une faute professionnelle. Les grandes catastrophes (Incendie du Parc Belvedere, Kiss-nightclub) ont conduit à des évolutions réglementaires mais le SSIAP 3 doit anticiper.', 1, null::integer[], array['theme2','seq2','REX et veille sécurité','Retour d''expérience et amélioration continue']::text[], 1),
('ssiap3-q22', 'ssiap3-partie5', 'multiple-select', 'Dans le cadre d''une approche d''amélioration continue du service SSIAP, quelle démarche le SSIAP 3 peut-il mettre en œuvre ? (plusieurs réponses possibles)', 'L''amélioration continue dans un service SSIAP de niveau 3 s''appuie sur plusieurs leviers : pilotage par les indicateurs (taux de fausses alarmes, délais de levée de doute, taux de conformité des équipements, temps de réponse aux anomalies) permettant de mesurer objectivement le progrès ; audits internes périodiques (revue des procédures, vérification des pratiques terrain) pour détecter les dérives avant qu''elles ne deviennent des non-conformités ; benchmarking avec des pairs (partage de pratiques lors de réseaux professionnels SSIAP, conférences) ; culture de remontée d''information (les agents de terrain sont les premiers observateurs des dysfonctionnements, il faut les encourager à les signaler sans crainte). Se contenter du minimum réglementaire est insuffisant pour un chef de service de haut niveau.', null, array[0,1,2,3]::integer[], array['theme2','seq2','REX et veille sécurité','Retour d''expérience et amélioration continue']::text[], 2),
('ssiap3-q41', 'ssiap3-partie5', 'multiple-select', 'Le SSIAP 3 doit réaliser une étude de danger dans le cadre d''une demande d''autorisation ICPE. Quels sont les éléments clés de cette étude ?', 'L''étude de danger (EdD) est le document technique central des demandes d''autorisation ICPE à haut risque. Elle comprend : l''inventaire et la caractérisation des substances dangereuses présentes (nature, quantité, propriétés physico-chimiques, toxicité) ; l''identification et l''analyse des scénarios d''accident majeur (scénarios de référence : incendie de nappe, BLEVE, explosion de nuage de gaz, fuite toxique) avec modélisation des effets (distances d''effets létaux, irréversibles, significatifs) ; l''évaluation de l''acceptabilité des risques résiduels pour les populations et l''environnement au regard des seuils réglementaires ; les mesures de maîtrise des risques (barrières de sécurité, redondances, procédures d''urgence) réduisant la probabilité et/ou la gravité des accidents. Le bilan commercial est sans objet dans une étude de danger.', null, array[0,1,2,3]::integer[], array['theme3','seq3','Études de danger ICPE','Études de dangers']::text[], 3),
('ssiap3-q42', 'ssiap3-partie5', 'quiz', 'Qu''est-ce que le nœud papillon (bow-tie) dans l''analyse des risques incendie et comment le SSIAP 3 l''utilise-t-il ?', 'Le nœud papillon (bow-tie) est un outil graphique d''analyse des risques très utilisé dans la sécurité des procédés et de plus en plus dans la sécurité incendie. Sa structure en papillon représente : à gauche : l''arbre des causes (fault tree) - toutes les causes pouvant conduire à l''événement redouté central (ex : départ de feu dans un local de stockage) avec les barrières de prévention réduisant la probabilité ; au centre : l''événement redouté central (l''incendie déclaré) ; à droite : l''arbre des conséquences (event tree) - toutes les conséquences possibles de l''événement avec les barrières de protection réduisant leur gravité (détection, alarme, extinction, évacuation). Le SSIAP 3 l''utilise pour visualiser et communiquer les risques à la direction, identifier les barrières critiques manquantes et justifier les investissements.', 1, null::integer[], array['theme4','seq1','Outils d''analyse des risques avancés','Méthodes d''analyse des risques']::text[], 4),
('ssiap3-q43', 'ssiap3-partie5', 'multiple-select', 'Le SSIAP 3 analyse les statistiques d''incendies dans les ERP français sur 5 ans. Quelles conclusions peut-il en tirer pour son établissement ? (plusieurs réponses possibles)', 'L''analyse statistique des incendies (données BSPP, SDIS, CNPP, rapports IRSN) est un outil stratégique pour le SSIAP 3 : identification des établissements et zones à plus fort risque historique (les parkings, cuisines, locaux électriques concentrent une proportion élevée des départs de feu) permettant d''adapter l''intensité des contrôles ; analyse des causes les plus fréquentes (défauts électriques, imprudences, malveillance) pour cibler les actions de prévention sur les sources de risque réelles ; évaluation comparative de l''efficacité des équipements (les ERP équipés de sprinklers ont des sinistres limités en extension) renforçant les arguments pour leur installation ; support argumentaire pour convaincre la direction d''investir dans la sécurité avec des chiffres objectifs. L''argument inverse - réduire les effectifs parce que les sinistres sont rares - est un raisonnement dangereux : la rareté est en partie due à la qualité de la prévention.', null, array[0,1,2,4]::integer[], array['theme2','seq2','REX et veille sécurité','Retour d''expérience et amélioration continue']::text[], 5)
on conflict (id) do update set
  type=excluded.type, question=excluded.question, explanation=excluded.explanation,
  correct_answer=excluded.correct_answer, correct_answers=excluded.correct_answers,
  tags=excluded.tags, display_order=excluded.display_order, updated_at=now();
delete from public.question_options where question_id in ('ssiap3-q20','ssiap3-q21','ssiap3-q22','ssiap3-q41','ssiap3-q42','ssiap3-q43');
insert into public.question_options (question_id, option_index, option_text) values
('ssiap3-q20', 0, 'Une méthode d''entraînement sportif pour les agents SSIAP'),
('ssiap3-q20', 1, 'Une méthode d''analyse systématique qui identifie pour chaque composant du système de sécurité (SSI, sprinklers, etc.) les modes de défaillance possibles, leurs effets sur la sécurité globale et leur niveau de criticité (probabilité × gravité)'),
('ssiap3-q20', 2, 'Une norme de certification des extincteurs'),
('ssiap3-q20', 3, 'Une procédure d''évacuation d''urgence'),
('ssiap3-q20', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap3-q21', 0, 'Il n''est pas concerné par les sinistres d''autres établissements'),
('ssiap3-q21', 1, 'Il analyse les causes et le déroulement du sinistre, identifie les similitudes avec son établissement, et prend proactivement les mesures préventives adaptées'),
('ssiap3-q21', 2, 'Il attend que la réglementation évolue avant d''agir'),
('ssiap3-q21', 3, 'Il communique uniquement l''information à ses agents sans prendre de décision'),
('ssiap3-q21', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap3-q22', 0, 'Mesurer régulièrement les indicateurs de performance (taux de fausses alarmes, délais de levée de doute)'),
('ssiap3-q22', 1, 'Organiser des audits internes périodiques du service'),
('ssiap3-q22', 2, 'Benchmarker les pratiques avec d''autres établissements similaires'),
('ssiap3-q22', 3, 'Encourager les remontées d''information des agents sur les dysfonctionnements'),
('ssiap3-q22', 4, 'Se satisfaire de la conformité réglementaire minimale sans chercher à progresser'),
('ssiap3-q41', 0, 'Identification et caractérisation des substances dangereuses présentes'),
('ssiap3-q41', 1, 'Analyse des scénarios d''accident majeur (incendie, explosion, dispersion toxique)'),
('ssiap3-q41', 2, 'Évaluation des effets sur les populations riveraines et l''environnement'),
('ssiap3-q41', 3, 'Définition des mesures de maîtrise des risques (MMR)'),
('ssiap3-q41', 4, 'Présentation du bilan commercial de l''exploitation'),
('ssiap3-q42', 0, 'Une technique de présentation PowerPoint pour les commissions de sécurité'),
('ssiap3-q42', 1, 'Une méthode graphique représentant d''un côté les causes pouvant mener à un événement redouté et de l''autre les conséquences, avec les barrières de prévention et de protection associées'),
('ssiap3-q42', 2, 'Un type de nœud de cravate réglementaire pour les inspections officielles'),
('ssiap3-q42', 3, 'Une procédure d''évacuation spécifique aux tunnels'),
('ssiap3-q42', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap3-q43', 0, 'Identifier les types d''ERP et les zones les plus touchées pour adapter ses contrôles'),
('ssiap3-q43', 1, 'Comprendre les causes les plus fréquentes (électricité, malveillance, imprudences) pour cibler sa prévention'),
('ssiap3-q43', 2, 'Mesurer l''efficacité relative des équipements de protection (sprinklers vs extincteurs vs détection seule)'),
('ssiap3-q43', 3, 'Justifier une réduction des effectifs SSIAP puisque les statistiques montrent peu de sinistres'),
('ssiap3-q43', 4, 'Alimenter ses argumentaires auprès de la direction pour prioriser les investissements');
commit;
