begin;
-- SSIAP 1 — Le feu et ses conséquences (partie 1, sub 2/3, 20 questions)
insert into public.questions (
  id, module_id, type, question, explanation, correct_answer, correct_answers, tags, display_order
) values
('ssiap1-q20', 'ssiap1-partie1', 'quiz', 'Qu''est-ce que la Limite Inférieure d''Explosivité (LIE) d''un gaz inflammable ?', 'La LIE (Limite Inférieure d''Explosivité) est la concentration minimale d''un gaz ou vapeur dans l''air en dessous de laquelle le mélange est trop pauvre pour s''enflammer (mélange pauvre). La LSE (Limite Supérieure d''Explosivité) est la concentration au-delà de laquelle le mélange est trop riche pour s''enflammer. Entre la LIE et la LSE se trouve la zone explosive ou inflammable. Exemple pour le méthane : LIE = 5 %, LSE = 15 %.', 1, null::integer[], array['theme5','seq1','Limites d''inflammabilité LIE/LSE','La combustion']::text[], 20),
('ssiap1-q21', 'ssiap1-partie1', 'quiz', 'Un local présente une concentration en propane de 12 %. Sachant que la LIE du propane est de 2,1 % et la LSE de 9,5 %, quelle est la situation ?', 'Avec 12 % de propane dans l''air, la concentration dépasse la LSE de 9,5 %. Le mélange est trop riche pour s''enflammer directement. Cependant, la situation reste extrêmement dangereuse : si de l''air frais entre (ventilation, ouverture d''une porte), la concentration peut redescendre dans la zone explosive (entre LIE 2,1 % et LSE 9,5 %) et créer un risque d''explosion. Il faut évacuer, ne pas créer d''étincelle et alerter les secours.', 2, null::integer[], array['theme5','seq1','Limites d''inflammabilité LIE/LSE','La combustion']::text[], 21),
('ssiap1-q22', 'ssiap1-partie1', 'quiz', 'Qu''est-ce qu''un backdraft ?', 'Le backdraft est une explosion ou déflagration soudaine provoquée par l''apport d''oxygène (air frais) dans un local confiné où les fumées et gaz combustibles se sont accumulés lors d''un incendie sous-ventilé. Les signes précurseurs sont : portes et fenêtres chaudes, fumée noire et dense sortant par les interstices, verre des fenêtres noirci, absence apparente de flammes. L''ouverture d''une porte ou d''une fenêtre peut déclencher une explosion violente projetant des flammes. C''est un danger mortel pour les sapeurs-pompiers.', 1, null::integer[], array['theme6','seq2','Backdraft, flashover, phénomènes dangereux','Phénomènes particuliers']::text[], 22),
('ssiap1-q23', 'ssiap1-partie1', 'quiz', 'Le flashover (embrasement généralisé éclair) se produit lorsque :', 'Le flashover est l''embrasement généralisé et quasi-simultané de tous les matériaux combustibles présents dans un local. Il se produit quand les gaz chauds sous le plafond atteignent environ 500-600 °C ou quand le rayonnement thermique au niveau du sol atteint 20 kW/m². Le flashover marque le passage d''un incendie localisé à un incendie généralisé. En quelques secondes, la température du local peut dépasser 1000 °C. Il est mortel et constitue un risque majeur pour les sapeurs-pompiers.', 1, null::integer[], array['theme6','seq2','Backdraft, flashover, phénomènes dangereux','Phénomènes particuliers']::text[], 23),
('ssiap1-q24', 'ssiap1-partie1', 'quiz', 'BLEVE est l''acronyme de « Boiling Liquid Expanding Vapour Explosion ». Ce phénomène concerne :', 'Le BLEVE (Boiling Liquid Expanding Vapour Explosion) est l''explosion d''un récipient (citerne, bouteille de GPL) contenant un liquide sous pression (comme le propane liquide) soumis à un apport de chaleur. La chaleur surchauffe le liquide au-delà de son point d''ébullition normal, provoquant une vaporisation instantanée et explosive lors de la rupture du récipient. Si le gaz libéré est inflammable, une boule de feu géante (fireball) se forme. C''est l''un des accidents les plus violents dans l''industrie pétro-chimique.', 1, null::integer[], array['theme6','seq2','Backdraft, flashover, phénomènes dangereux','Phénomènes particuliers']::text[], 24),
('ssiap1-q25', 'ssiap1-partie1', 'quiz', 'Quels sont les signes précurseurs d''un backdraft que l''agent SSIAP doit reconnaître ?', 'Les signes précurseurs d''un backdraft sont caractéristiques : 1) La porte est chaude (ne jamais ouvrir une porte chaude sans précaution) ; 2) Fumée noire et dense sortant par les interstices ; 3) Absence apparente de flammes (le feu couve sous les fumées) ; 4) Vitres noircies ; 5) Parfois, ''respiration'' de la fumée (rentrée/sortie rythmée). Face à ces signes, l''agent SSIAP doit immédiatement évacuer la zone, ne pas ouvrir la porte et alerter les pompiers.', 1, null::integer[], array['theme6','seq2','Backdraft, flashover, phénomènes dangereux','Phénomènes particuliers']::text[], 25),
('ssiap1-q26', 'ssiap1-partie1', 'quiz', 'À quelle température les structures en acier commencent-elles à perdre significativement leur résistance mécanique ?', 'Les structures en acier commencent à perdre significativement leur résistance mécanique à partir de 550 °C environ. À 700 °C, l''acier a perdu environ 70 % de sa résistance initiale. À 1000 °C, la perte est quasi totale. C''est pourquoi les structures métalliques doivent être protégées (peintures intumescentes, encoffrement, faux-plafonds coupe-feu) pour résister au feu pendant la durée réglementaire. Cette caractéristique explique l''effondrement de certains bâtiments à ossature métallique lors d''incendies importants.', 2, null::integer[], array['theme7','seq3','Effets du feu sur les structures','Conséquences sur les personnes et les biens']::text[], 26),
('ssiap1-q27', 'ssiap1-partie1', 'quiz', 'Pourquoi le béton peut-il éclater lors d''un incendie ?', 'Le béton peut éclater lors d''un incendie par un phénomène appelé ''écaillage thermique'' ou spalling. Ce phénomène est dû à la vaporisation brutale de l''eau contenue dans le béton sous l''effet de la chaleur rapide, créant une pression interne qui fait éclater le matériau. Les différences de dilatation thermique entre la pâte de ciment et les granulats contribuent également à cet éclatement. Les bétons modernes à haute performance, plus denses, sont particulièrement vulnérables à ce phénomène.', 1, null::integer[], array['theme7','seq3','Effets du feu sur les structures','Conséquences sur les personnes et les biens']::text[], 27),
('ssiap1-q28', 'ssiap1-partie1', 'quiz', 'Un feu se déclare dans un local. Quelles sont les conséquences possibles pour les occupants ?', 'Les conséquences d''un incendie pour les personnes sont multiples : 1) Intoxication aux fumées et gaz toxiques (CO, HCN, HCl...) - principale cause de décès ; 2) Brûlures par contact direct avec les flammes ou matériaux chauds ; 3) Effets thermiques des gaz chauds sur les voies respiratoires ; 4) Panique entraînant des blessures lors de l''évacuation (bousculades, chutes) ; 5) Effets psychologiques (traumatismes). La prévention et l''évacuation organisée sont essentielles pour limiter ces conséquences.', 1, null::integer[], array['theme7','seq3','Effets du feu sur les structures','Conséquences sur les personnes et les biens']::text[], 28),
('ssiap1-q29', 'ssiap1-partie1', 'quiz', 'L''auto-inflammation est la capacité d''un matériau à s''enflammer spontanément. Quelle en est la cause ?', 'L''auto-inflammation (ou ignition spontanée) se produit lorsqu''un matériau combustible est porté à sa température d''auto-inflammation sans apport d''une flamme ou d''une étincelle externe. Elle peut se produire par accumulation de chaleur (oxydation lente d''un tas de chiffons imprégnés d''huile siccative, foin humide), par échauffement prolongé d''une surface (tuyau de chauffage contre une poutre en bois), ou par rayonnement thermique intense. Le stockage de matières organiques doit tenir compte de ce risque.', 2, null::integer[], array['theme7','seq3','Effets du feu sur les structures','Conséquences sur les personnes et les biens']::text[], 29),
('ssiap1-q77', 'ssiap1-partie1', 'multiple-select', 'Parmi les propositions suivantes, lesquelles sont des modes de propagation de la chaleur lors d''un incendie ? (plusieurs réponses possibles)', 'Les quatre modes de propagation de la chaleur lors d''un incendie sont : la conduction (transfert par contact matériel), la convection (déplacement de masses gazeuses chaudes), le rayonnement (ondes électromagnétiques infrarouges) et la projection (transport de brandons enflammés). La précipitation n''est pas un mode de propagation thermique. L''oxydation est la réaction chimique de la combustion, non un mode de propagation.', null, array[0,1,3,5]::integer[], array['theme2','seq1','Modes de propagation de la chaleur','La combustion']::text[], 30),
('ssiap1-q78', 'ssiap1-partie1', 'multiple-select', 'Quelles affirmations concernant le triangle du feu sont CORRECTES ? (plusieurs réponses possibles)', 'Les affirmations correctes : supprimer le combustible (débroussaillage, coupure de gaz) éteint bien le feu. Supprimer l''énergie d''activation (refroidissement par eau) éteint aussi le feu. La mousse agit principalement par étouffement en séparant le combustible du comburant (oxygène). En revanche, le feu ne peut pas brûler sans comburant quelle que soit la température. L''eau agit principalement par refroidissement (suppression de l''énergie) et non par suppression du comburant.', null, array[0,2,4]::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 31),
('ssiap1-q79', 'ssiap1-partie1', 'quiz', 'Quel est le quatrième élément du tétraèdre du feu selon la proposition suivante qui identifie un élément INEXISTANT dans cette théorie ?', 'Le tétraèdre du feu comporte exactement quatre éléments : combustible, comburant, énergie d''activation et réaction en chaîne. La pression atmosphérique, la teneur en azote, la densité de l''air et l''humidité ambiante influencent les conditions de combustion mais ne font pas partie de la définition du tétraèdre du feu. Aucune des propositions ne correspond au quatrième élément réel (la réaction en chaîne), donc ''Aucune de ces réponses n''est correcte'' est la bonne réponse.', 4, null::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 32),
('ssiap1-q80', 'ssiap1-partie1', 'multiple-select', 'La combustion lente (couvante) se caractérise par : (plusieurs réponses possibles)', 'La combustion lente (ou couvante) se caractérise par l''absence de flammes visibles, la présence de braises incandescentes et un dégagement de fumée dense (souvent blanche ou grise). Elle peut durer très longtemps et reprendre en combustion vive en cas d''apport d''air. Elle ne produit pas de flammes bleues (caractéristiques des flammes de gaz). Une explosion n''est pas inévitable mais possible si les gaz de combustion s''accumulent (risque de backdraft).', null, array[0,1,3]::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 33),
('ssiap1-q81', 'ssiap1-partie1', 'multiple-select', 'Quels gaz toxiques peut-on trouver dans les fumées d''un incendie impliquant des matières plastiques ? (plusieurs réponses possibles)', 'Les fumées d''incendie de matières plastiques contiennent de nombreux gaz toxiques : le CO (monoxyde de carbone, produit par toute combustion incomplète), l''HCN (acide cyanhydrique, produit par la combustion des polyuréthanes et matières azotées), l''HCl (chlorure d''hydrogène, produit par la combustion du PVC), et le NO2 (dioxyde d''azote, très irritant). L''oxygène pur n''est pas un produit de combustion, au contraire, la combustion consomme l''oxygène. D''autres gaz toxiques peuvent aussi être présents selon les matériaux (phosgène, styrène, etc.).', null, array[0,1,3,4]::integer[], array['theme3','seq1','Produits de la combustion et effets','La combustion']::text[], 34),
('ssiap1-q82', 'ssiap1-partie1', 'quiz', 'Quelle classe de feu correspond à un feu de magnésium en poudre ?', 'Le magnésium est un métal combustible (classe D). Les feux de métaux (classe D) comprennent le magnésium, l''aluminium en poudre, le titane, le sodium, le potassium, le lithium. Ils nécessitent des agents extincteurs spéciaux (poudre D, sable sec). L''eau, le CO2 et la mousse sont contre-indiqués et peuvent aggraver ces feux. La classe A concerne les solides ordinaires, B les liquides, C les gaz, F les huiles de cuisson.', 3, null::integer[], array['theme4','seq1','Classes de feu','La combustion']::text[], 35),
('ssiap1-q83', 'ssiap1-partie1', 'multiple-select', 'Pour éteindre un feu de classe C (gaz), quelles sont les actions prioritaires à mener ? (plusieurs réponses possibles)', 'Pour un feu de gaz : la priorité absolue est de couper l''alimentation en gaz (fermer le robinet, le détendeur ou la vanne principale). Il ne faut jamais éteindre les flammes sans avoir coupé le gaz car cela accumulerait le gaz qui pourrait exploser au contact de la moindre source d''ignition. Une fois le gaz coupé, ventiler le local pour évacuer les gaz résiduels. L''arrosage à l''eau sans couper le gaz est inefficace. L''utilisation immédiate d''un extincteur CO2 sur les flammes sans couper le gaz est contre-indiqué.', null, array[0,2,3]::integer[], array['theme4','seq1','Classes de feu','La combustion']::text[], 36),
('ssiap1-q84', 'ssiap1-partie1', 'quiz', 'Un feu se déclare dans une bibliothèque (livres, revues, rayonnages bois). De quelle(s) classe(s) s''agit-il ?', 'Les livres, revues et rayonnages en bois sont des solides d''origine organique produisant des braises lors de leur combustion : c''est typiquement un feu de classe A. Il n''y a pas de liquide inflammable ni de gaz impliqué dans ce scénario. L''extincteur à eau pulvérisée est le plus adapté pour les feux de classe A car il refroidit en profondeur et évite la reprise. La poudre ABC peut être utilisée mais laisse des résidus qui endommagent les collections.', 0, null::integer[], array['theme4','seq1','Classes de feu','La combustion']::text[], 37),
('ssiap1-q111', 'ssiap1-partie1', 'quiz', 'Quel est le rôle de l''agent extincteur dans un extincteur à poudre ABC ?', 'La poudre ABC (bicarbonate de sodium ou phosphate d''ammonium) agit par deux mécanismes : l''inhibition de la réaction en chaîne (action sur le tétraèdre du feu, côté réaction en chaîne) en détruisant les radicaux libres, et l''étouffement partiel en formant un écran entre les flammes et le combustible. Son efficacité polyvalente (A, B, C) la rend idéale pour les extincteurs portatifs d''usage général. Inconvénients : résidus importants, corrosive pour certains matériaux, dégrade les équipements électroniques.', 1, null::integer[], array['theme1','seq1','Le feu - triangle et tétraèdre','La combustion']::text[], 38),
('ssiap1-q112', 'ssiap1-partie1', 'multiple-select', 'Quels sont les signes précurseurs d''un flashover que l''agent SSIAP peut observer depuis l''extérieur d''un local ? (plusieurs réponses possibles)', 'Avant le flashover, on peut observer : des flammes apparaissant en partie haute des ouvertures (les gaz chauds sous plafond commencent à brûler), des fumées noires très denses s''échappant sous pression (signe de combustion intense), des bruits de crépitement et craquement intenses. Le local ne paraît jamais calme avant un flashover. L''éclair lumineux caractéristique se produit AU MOMENT du flashover, non avant. Face à ces signes, l''agent SSIAP doit immédiatement s''éloigner, ne jamais ouvrir la porte, et alerter les pompiers.', null, array[0,1,2]::integer[], array['theme6','seq2','Backdraft, flashover, phénomènes dangereux','Phénomènes particuliers']::text[], 39)
on conflict (id) do update set
  type=excluded.type, question=excluded.question, explanation=excluded.explanation,
  correct_answer=excluded.correct_answer, correct_answers=excluded.correct_answers,
  tags=excluded.tags, display_order=excluded.display_order, updated_at=now();
delete from public.question_options where question_id in ('ssiap1-q20','ssiap1-q21','ssiap1-q22','ssiap1-q23','ssiap1-q24','ssiap1-q25','ssiap1-q26','ssiap1-q27','ssiap1-q28','ssiap1-q29','ssiap1-q77','ssiap1-q78','ssiap1-q79','ssiap1-q80','ssiap1-q81','ssiap1-q82','ssiap1-q83','ssiap1-q84','ssiap1-q111','ssiap1-q112');
insert into public.question_options (question_id, option_index, option_text) values
('ssiap1-q20', 0, 'La pression minimale à laquelle le gaz explose'),
('ssiap1-q20', 1, 'La concentration minimale de gaz dans l''air en dessous de laquelle le mélange n''est pas inflammable'),
('ssiap1-q20', 2, 'La température à laquelle le gaz s''enflamme spontanément'),
('ssiap1-q20', 3, 'La quantité maximale de gaz stockable en sécurité'),
('ssiap1-q21', 0, 'Le mélange est trop pauvre, aucun risque'),
('ssiap1-q21', 1, 'Le mélange est dans la zone explosive, danger immédiat'),
('ssiap1-q21', 2, 'Le mélange est trop riche, pas de risque d''inflammation directe mais dangereux si la concentration diminue'),
('ssiap1-q21', 3, 'Le local est parfaitement ventilé'),
('ssiap1-q22', 0, 'Un embrasement généralisé éclair dans une pièce confinée'),
('ssiap1-q22', 1, 'Une explosion de fumées riches en CO et gaz combustibles lors de l''apport soudain d''air frais'),
('ssiap1-q22', 2, 'La propagation rapide des flammes sur les parois'),
('ssiap1-q22', 3, 'L''effondrement thermique d''une structure métallique'),
('ssiap1-q23', 0, 'Une flamme nue entre en contact avec un gaz'),
('ssiap1-q23', 1, 'La température dans un local atteint un seuil où tous les matériaux combustibles s''enflamment simultanément'),
('ssiap1-q23', 2, 'Un liquide inflammable se répand sur le sol'),
('ssiap1-q23', 3, 'Un court-circuit électrique provoque une étincelle'),
('ssiap1-q24', 0, 'L''explosion d''un local rempli de poussières combustibles'),
('ssiap1-q24', 1, 'L''explosion d''un récipient contenant un liquide sous pression sous l''effet de la chaleur'),
('ssiap1-q24', 2, 'La propagation ultrarapide des flammes dans un tunnel'),
('ssiap1-q24', 3, 'L''embrasement des fumées au plafond'),
('ssiap1-q25', 0, 'Flammes visibles à travers les vitres, odeur de brûlé, alarme incendie déclenchée'),
('ssiap1-q25', 1, 'Porte chaude au toucher, fumée noire et dense sortant par les joints, absence de flammes visibles, vitres noircies'),
('ssiap1-q25', 2, 'Sol mouillé, absence de fumée, bruit de craquement'),
('ssiap1-q25', 3, 'Sprinklers déclenchés, alarme générale, présence de pompiers'),
('ssiap1-q26', 0, '200 °C'),
('ssiap1-q26', 1, '350 °C'),
('ssiap1-q26', 2, '550 °C'),
('ssiap1-q26', 3, '1000 °C'),
('ssiap1-q27', 0, 'Parce qu''il fond à haute température'),
('ssiap1-q27', 1, 'En raison de la vaporisation rapide de l''humidité contenue et des différences de dilatation thermique'),
('ssiap1-q27', 2, 'Parce que les armatures métalliques fondent en premier'),
('ssiap1-q27', 3, 'Le béton n''éclate jamais en cas d''incendie'),
('ssiap1-q28', 0, 'Uniquement des brûlures superficielles'),
('ssiap1-q28', 1, 'Intoxication aux fumées et gaz toxiques, brûlures, effets thermiques, panique et blessures lors de l''évacuation'),
('ssiap1-q28', 2, 'Exclusivement des dommages matériels'),
('ssiap1-q28', 3, 'Aucun risque si les sprinklers sont actifs'),
('ssiap1-q29', 0, 'Un contact avec une flamme nue'),
('ssiap1-q29', 1, 'Une étincelle électrique'),
('ssiap1-q29', 2, 'L''échauffement du matériau jusqu''à sa température d''auto-inflammation sans apport de source d''allumage externe'),
('ssiap1-q29', 3, 'L''humidité ambiante'),
('ssiap1-q77', 0, 'La conduction'),
('ssiap1-q77', 1, 'La convection'),
('ssiap1-q77', 2, 'La précipitation'),
('ssiap1-q77', 3, 'Le rayonnement'),
('ssiap1-q77', 4, 'L''oxydation'),
('ssiap1-q77', 5, 'La projection'),
('ssiap1-q78', 0, 'La suppression du combustible éteint le feu'),
('ssiap1-q78', 1, 'Le feu peut brûler sans comburant si la température est suffisante'),
('ssiap1-q78', 2, 'La suppression de l''énergie d''activation éteint le feu'),
('ssiap1-q78', 3, 'L''eau agit principalement en supprimant le comburant'),
('ssiap1-q78', 4, 'La mousse agit principalement par étouffement (suppression du comburant)'),
('ssiap1-q79', 0, 'La pression atmosphérique'),
('ssiap1-q79', 1, 'La teneur en azote'),
('ssiap1-q79', 2, 'La densité de l''air'),
('ssiap1-q79', 3, 'L''humidité ambiante'),
('ssiap1-q79', 4, 'Aucune de ces réponses n''est correcte'),
('ssiap1-q80', 0, 'L''absence de flammes visibles'),
('ssiap1-q80', 1, 'La présence de braises et incandescence'),
('ssiap1-q80', 2, 'Une température très élevée avec flammes bleues'),
('ssiap1-q80', 3, 'Un dégagement de fumée dense'),
('ssiap1-q80', 4, 'Une explosion immédiate inévitable'),
('ssiap1-q81', 0, 'Monoxyde de carbone (CO)'),
('ssiap1-q81', 1, 'Acide cyanhydrique (HCN)'),
('ssiap1-q81', 2, 'Oxygène pur (O2)'),
('ssiap1-q81', 3, 'Chlorure d''hydrogène (HCl)'),
('ssiap1-q81', 4, 'Dioxyde d''azote (NO2)'),
('ssiap1-q82', 0, 'Classe A'),
('ssiap1-q82', 1, 'Classe B'),
('ssiap1-q82', 2, 'Classe C'),
('ssiap1-q82', 3, 'Classe D'),
('ssiap1-q82', 4, 'Classe F'),
('ssiap1-q83', 0, 'Couper l''alimentation en gaz avant tout'),
('ssiap1-q83', 1, 'Arroser le feu à l''eau pour le refroidir'),
('ssiap1-q83', 2, 'Ne jamais éteindre les flammes sans avoir coupé le gaz'),
('ssiap1-q83', 3, 'Ventiler le local pour évacuer le gaz résiduel'),
('ssiap1-q83', 4, 'Utiliser immédiatement l''extincteur CO2 sur les flammes'),
('ssiap1-q84', 0, 'Classe A uniquement'),
('ssiap1-q84', 1, 'Classe B uniquement'),
('ssiap1-q84', 2, 'Classe A et B'),
('ssiap1-q84', 3, 'Classe C'),
('ssiap1-q84', 4, 'Classe F'),
('ssiap1-q111', 0, 'Refroidir le combustible en absorbant la chaleur'),
('ssiap1-q111', 1, 'Inhiber la réaction en chaîne et étouffer le feu par formation d''un écran'),
('ssiap1-q111', 2, 'Diluer l''oxygène de l''air autour du foyer'),
('ssiap1-q111', 3, 'Précipiter chimiquement les gaz toxiques'),
('ssiap1-q111', 4, 'Créer un film imperméable sur le combustible'),
('ssiap1-q112', 0, 'Flammes sortant sous la porte et en partie haute des ouvertures'),
('ssiap1-q112', 1, 'Fumées noires denses s''échappant sous haute pression'),
('ssiap1-q112', 2, 'Bruits de crépitement et de craquement intenses'),
('ssiap1-q112', 3, 'Le local paraît vide et calme'),
('ssiap1-q112', 4, 'Éclair de lumière intense visible sous la porte');
commit;
